const names = [
  { index: "1", name: "Un mystérieux guerrier" },
  { index: "2", name: "Le Passé de Son Goku" },
  { index: "3", name: "Une équipe de choc" },
  { index: "4", name: "Quand les ennemis s’allient" },
  { index: "5", name: "Son Goku sacrifie sa vie" },
  { index: "6", name: "Pour une victoire définitive" },
  { index: "7", name: "L’Entraînement de Son Gohan" },
  { index: "8", name: "La Métamorphose de Son Gohan" },
  { index: "9", name: "Le Robot" },
  { index: "10", name: "Un compagnon pour Son Gohan" },
  { index: "11", name: "Une courte escale" },
  { index: "12", name: "Un chemin sans fin" },
  { index: "13", name: "Le Passage secret" },
  { index: "14", name: "Hospitalité princière" },
  { index: "15", name: "La Tempête" },
  { index: "16", name: "Le Village abandonné" },
  { index: "17", name: "La Cité des guerriers" },
  { index: "18", name: "La Fin du voyage" },
  { index: "19", name: "La Loi de l’apesanteur" },
  { index: "20", name: "La Légende des Guerriers de l’espace" },
  { index: "21", name: "L’Arrivée de l’ennemi" },
  { index: "22", name: "Des graines très étranges" },
  { index: "23", name: "Une tactique monstrueuse" },
  { index: "24", name: "Un acte de courage" },
  { index: "25", name: "La Force du désespoir" },
  { index: "26", name: "La Trêve" },
  { index: "27", name: "Un retour très attendu" },
  { index: "28", name: "Une double perte" },
  { index: "29", name: "L’insurpassable technique de Kaio" },
  { index: "30", name: "La Troisième Attaque" },
  { index: "31", name: "La Métamorphose du dernier guerrier" },
  { index: "32", name: "Au-delà de la dernière chance" },
  { index: "33", name: "Le Don de la force" },
  { index: "34", name: "Une lourde responsabilité" },
  { index: "35", name: "Une étonnante transformation" },
  { index: "36", name: "Une nouvelle destination" },
  { index: "37", name: "Voyage au bout du monde" },
  { index: "38", name: "Départ pour la planète Namek" },
  { index: "39", name: "Prisonniers dans l’espace" },
  { index: "40", name: "Destination Namek" },
  { index: "41", name: "Des amis très attentionnés" },
  { index: "42", name: "l’ennemi se réveille" },
  { index: "43", name: "Le Dernier Piège" },
  { index: "44", name: "Un nouvel ennemi" },
  { index: "45", name: "Une puissance extraordinaire" },
  { index: "46", name: "Jusqu’au bout de l’univers" },
  { index: "47", name: "Les Nameks contre le tyran" },
  { index: "48", name: "Un soldat impitoyable" },
  { index: "49", name: "Une terrible révélation" },
  { index: "50", name: "Un incident de parcours" },
  { index: "51", name: "Des nouvelles de Kaio" },
  { index: "52", name: "Le Troisième Adversaire" },
  { index: "53", name: "La Transformation du 3e adversaire" },
  { index: "54", name: "Rencontre avec le chef des Nameks" },
  { index: "55", name: "Une guérison miraculeuse" },
  { index: "56", name: "Qui rira le dernier ?" },
  { index: "57", name: "Jour de chance pour l’ennemi" },
  { index: "58", name: "L’Armée secrète du tyran" },
  { index: "59", name: "Bonne chance Bulma !" },
  { index: "60", name: "Les Déboires de Bulma" },
  { index: "61", name: "L’armée secrète arrive" },
  { index: "62", name: "Une troupe de choc" },
  { index: "63", name: "Sous le pouvoir de l’ennemi" },
  { index: "64", name: "Un souffle destructeur" },
  { index: "65", name: "Sangohan contre l’invincible soldat" },
  { index: "66", name: "Un guerrier légendaire" },
  { index: "67", name: "Sangoku aux prises avec les ennemis" },
  { index: "68", name: "Le Capitaine des forces spéciales" },
  { index: "69", name: "Le Défi du capitaine giynu" },
  { index: "70", name: "Freezer à la recherche du mot magique" },
  { index: "71", name: "La Métamorphose" },
  { index: "72", name: "Les Sept Boules de cristal enfin retrouvées" },
  { index: "73", name: "Sous l’apparence de Sangoku" },
  { index: "74", name: "Une erreur fatale" },
  { index: "75", name: "La Formule magique" },
  { index: "76", name: "Les Trois Vœux enfin réalisés" },
  { index: "77", name: "L’union fait la force" },
  { index: "78", name: "Une force insurmontable" },
  { index: "79", name: "La Riposte de Sangohan" },
  { index: "80", name: "L’Arrivée de Petit-Cœur" },
  { index: "81", name: "Freezer contre Satan Petit-Cœur" },
  { index: "82", name: "Seconde transformation" },
  { index: "83", name: "Doit-on sauver Vegeta ?" },
  { index: "84", name: "La Perte d’un allié précieux" },
  { index: "85", name: "Le Retour de Sangoku" },
  { index: "86", name: "Une fin tragique pour Vegeta" },
  { index: "87", name: "Sangoku tiendra-t-il la promesse ?" },
  { index: "88", name: "Une lutte interminable" },
  { index: "89", name: "La Promesse rompue" },
  { index: "90", name: "Tentative d’intimidation" },
  { index: "91", name: "L’Attaque de Kaio" },
  { index: "92", name: "Un atout pour la victoire" },
  { index: "93", name: "Les Grandes Forces de l’univers" },
  { index: "94", name: "La Phase finale" },
  { index: "95", name: "L’Apparition d’un guerrier légendaire" },
  { index: "96", name: "Une terrible vengeance" },
  { index: "97", name: "Un dénouement difficile" },
  { index: "98", name: "La Force totale" },
  { index: "99", name: "Le Souhait de Kaio" },
  { index: "100", name: "Un fils courageux" },
  { index: "101", name: "Le Dernier Souhait" },
  { index: "102", name: "Une lueur d’espoir" },
  { index: "103", name: "Les Dernières Minutes avant l’explosion" },
  { index: "104", name: "La Fin du tyran" },
  { index: "105", name: "La Défaite de Freezer" },
  { index: "106", name: "L’Explosion d’un héros" },
  { index: "107", name: "Sangoku est vivant!" },
  { index: "108", name: "Le Successeur du tout puissant" },
  { index: "109", name: "Le Poison diabolique" },
  { index: "110", name: "Le Champ de bataille au paradis" },
  { index: "111", name: "Coup de colère ou coup de grâce" },
  { index: "112", name: "Petit-Cœur redevient Satan" },
  { index: "113", name: "Un pouvoir grandissant" },
  { index: "114", name: "Le Mystère du firmament" },
  { index: "115", name: "Un tour diabolique" },
  { index: "116", name: "La Fin de la magie noire" },
  { index: "117", name: "En âge de se marier" },
  { index: "118", name: "Freezer contre-attaque" },
  { index: "119", name: "Le Mystérieux Sauveur" },
  { index: "120", name: "Mauvaise surprise pour Freezer" },
  { index: "121", name: "Qui est ce mystérieux guerrier ?" },
  { index: "122", name: "Le Secret bien gardé !" },
  { index: "123", name: "La Nouvelle Technique de Sangoku" },
  { index: "124", name: "La Grande Préparation" },
  { index: "125", name: "Une nouvelle épreuve pour Sangoku" },
  { index: "126", name: "L’Arrivée des cyborgs" },
  { index: "127", name: "La Rencontre avec les cyborgs" },
  { index: "128", name: "La Botte secrète des cyborgs" },
  { index: "129", name: "Le Retour de Vegeta" },
  { index: "130", name: "Le Secret" },
  { index: "131", name: "Qui sont les cyborgs ?" },
  { index: "132", name: "À la recherche du laboratoire" },
  { index: "133", name: "Le cauchemar devient réalité" },
  { index: "134", name: "Le Dernier cyborgs" },
  { index: "135", name: "Un cyborg sans peur et sans reproches" },
  { index: "136", name: "Un combat inégal" },
  { index: "137", name: "La Décision de Petit-Cœur" },
  { index: "138", name: "Sangoku est à l’abri" },
  { index: "139", name: "Le mauvais présage" },
  {
    index: "140",
    name: "Le passager de la seconde machine à voyager dans le temps",
  },
  { index: "141", name: "L’union fait la force" },
  { index: "142", name: "Un monstre aux pouvoirs effrayants" },
  { index: "143", name: "Un quatrième cyborg" },
  { index: "144", name: "L’erreur de Petit-Cœur" },
  { index: "145", name: "Le secret de la naissance de Cell" },
  { index: "146", name: "Le réveil de Sangoku" },
  { index: "147", name: "Une lueur d’espoir" },
  { index: "148", name: "Les cyborgs repérés" },
  { index: "149", name: "Tout près du but" },
  { index: "150", name: "La créature invincible" },
  { index: "151", name: "Un adversaire de taille" },
  { index: "152", name: "Les robots ne sont pas de taille" },
  { index: "153", name: "La bouée de sauvetage" },
  { index: "154", name: "Le bout du tunnel" },
  { index: "155", name: "L’apogée de Végéta" },
  { index: "156", name: "À genoux devant Végéta" },
  { index: "157", name: "L’arrogance de Végéta" },
  { index: "158", name: "Le choix de Krilin" },
  { index: "159", name: "Prélude avant la terreur" },
  { index: "160", name: "La terreur en marche" },
  { index: "161", name: "Végéta en danger !" },
  { index: "162", name: "Trunks fait des étincelles" },
  { index: "163", name: "Trunks au secours de Végéta" },
  { index: "164", name: "Trunks le survivant du futur" },
  { index: "165", name: "La terrible decision de Cell" },
  { index: "166", name: "Pourquoi un tournoi ?" },
  { index: "167", name: "Le spectacle continue" },
  { index: "168", name: "Le retour de Sangoku" },
  { index: "169", name: "Ailleurs" },
  { index: "170", name: "La fausse alerte" },
  { index: "171", name: "Photo de famille" },
  { index: "172", name: "L’assaut contre Cell" },
  { index: "173", name: "Un nouveau Dieu" },
  { index: "174", name: "Les boules de cristal" },
  { index: "175", name: "Les vingt dernières minutes" },
  { index: "176", name: "Les disciples d’Hercule" },
  { index: "177", name: "Premier round" },
  { index: "178", name: "Le grand jeu" },
  { index: "179", name: "La tactique secrète" },
  { index: "180", name: "Sangoku abandonne" },
  { index: "181", name: "Le dernier participant" },
  { index: "182", name: "Le secret de Sangohan" },
  { index: "183", name: "La mort de C-16" },
  { index: "184", name: "Les monstres miniatures" },
  { index: "185", name: "Bravo Sangohan" },
  { index: "186", name: "Cell K.O." },
  { index: "187", name: "La fin du cauchemar ?" },
  { index: "188", name: "Le sacrifice" },
  { index: "189", name: "La terreur" },
  { index: "190", name: "Tel père, tel fils" },
  { index: "191", name: "Le jour de la délivrance" },
  { index: "192", name: "La paix est revenue" },
  { index: "193", name: "Le 2e souhait" },
  { index: "194", name: "Le cauchemar du monde futur" },
  { index: "195", name: "Les habitants de l’autre monde" },
  { index: "196", name: "Encore un tournoi ?" },
  { index: "197", name: "Les quarts de finale" },
  { index: "198", name: "La finale de tous les dangers" },
  { index: "199", name: "Le nouveau champion" },
  { index: "200", name: "Le premier jour d’école" },
  { index: "201", name: "Le guerrier intergalactique" },
  { index: "202", name: "Romance" },
  { index: "203", name: "Videl en mauvaise posture" },
  { index: "204", name: "Face à face" },
  { index: "205", name: "Un championnat qui s’annonce mal" },
  { index: "206", name: "Tel père, tel fils" },
  { index: "207", name: "Comment taquiner les oiseaux ?" },
  { index: "208", name: "Rappel des troupes" },
  { index: "209", name: "Comme au bon vieux temps" },
  { index: "210", name: "Petit Trunks deviendra grand" },
  { index: "211", name: "Trunks contre Sangoten" },
  { index: "212", name: "Que le meilleur gagne !" },
  { index: "213", name: "Hercule, le faux héros !" },
  { index: "214", name: "Tirage au sort" },
  { index: "215", name: "L’abandon de Petit-Cœur" },
  { index: "216", name: "L’adversaire de Videl" },
  { index: "217", name: "La première défaite" },
  { index: "218", name: "Sangohan est démasqué" },
  { index: "219", name: "La fin du mystère" },
  { index: "220", name: "La course poursuite" },
  { index: "221", name: "Le premier sous-sol" },
  { index: "222", name: "La surprise du 2e sous-sol" },
  { index: "223", name: "Sangoku est inébranlable" },
  { index: "224", name: "Le tournoi reprend" },
  { index: "225", name: "Le guerrier démasqué" },
  { index: "226", name: "Un échange de bons procédés" },
  { index: "227", name: "Sangohan à l’épreuve !" },
  { index: "228", name: "La face cachée de Végéta" },
  { index: "229", name: "La terrible confrontation" },
  { index: "230", name: "La revanche de Végéta" },
  { index: "231", name: "Végéta s’explique" },
  { index: "232", name: "Une apparition attendue" },
  { index: "233", name: "Des apparences trompeuses" },
  { index: "234", name: "Attention, danger !" },
  { index: "235", name: "Le biscuit géant" },
  { index: "236", name: "Le défi de Végéta" },
  { index: "237", name: "Le sacrifice d’un père" },
  { index: "238", name: "Tout recommence à zéro" },
  { index: "239", name: "Deux absences inexpliquées" },
  { index: "240", name: "Un seul souhait" },
  { index: "241", name: "La douloureuse nouvelle" },
  { index: "242", name: "L’épée sacrée du royaume des Dieux" },
  { index: "243", name: "Deux fortes têtes" },
  { index: "244", name: "Le chantage continue" },
  { index: "245", name: "Un coup de bluff ?" },
  { index: "246", name: "Boo se révolte" },
  { index: "247", name: "La fin de la permission de Sangoku" },
  { index: "248", name: "Le temps des adieux" },
  { index: "249", name: "Des adieux et des retrouvailles" },
  { index: "250", name: "L’épée cassée" },
  { index: "251", name: "Péché d’orgueil" },
  { index: "252", name: "Le doyen des dieux" },
  { index: "253", name: "Le monstre et le chiot" },
  { index: "254", name: "Une accalmie" },
  { index: "255", name: "Trois Boubou différents" },
  { index: "256", name: "Une visite inattendue" },
  { index: "257", name: "Les dernières secondes de répit" },
  { index: "258", name: "Une drôle de tactique" },
  { index: "259", name: "Les super fantômes kamikazes" },
  { index: "260", name: "La porte entre les deux dimensions" },
  { index: "261", name: "Une partie de volley qui tourne mal" },
  { index: "262", name: "Le choc des titans" },
  { index: "263", name: "Une lueur d’espoir" },
  { index: "264", name: "La mystérieuse réapparition de Dendee" },
  { index: "265", name: "Une erreur fatale" },
  { index: "266", name: "Le retour à la vie" },
  { index: "267", name: "Les boucles magiques" },
  { index: "268", name: "Le refus de Vegeta" },
  { index: "269", name: "La naissance d’un super héros" },
  { index: "270", name: "On n’est pas hors de danger" },
  { index: "271", name: "L’étrange attitude de Vegeku" },
  { index: "272", name: "Une erreur qui risque de coûter cher" },
  { index: "273", name: "Un drôle de labyrinthe" },
  { index: "274", name: "Gare aux mirages" },
  { index: "275", name: "Le monstre à deux têtes" },
  { index: "276", name: "La sortie de secours" },
  { index: "277", name: "Prochaine victime : la Terre" },
  { index: "278", name: "La tragédie continue" },
  { index: "279", name: "La menace qui pèse sur l’autre-monde" },
  { index: "280", name: "Sangoku joue son va-tout" },
  { index: "281", name: "La minute de vérité" },
  { index: "282", name: "Une intervention providentielle" },
  { index: "283", name: "Le dragon de la planète Namek" },
  { index: "284", name: "La stratégie du dernier espoir" },
  { index: "285", name: "L’ingratitude des Terriens" },
  { index: "286", name: "Sangoku passe à l’attaque" },
  { index: "287", name: "Boo et les billets débarquent" },
  { index: "288", name: "Le bonheur retrouvé" },
  { index: "289", name: "La troisième génération" },
  { index: "290", name: "Une vieille connaissance" },
  { index: "291", name: "Sangoku commence une nouvelle vie" },
];

export default names;
