const episodes = [
  { name: "La Fin du commencement et le début de la fin", index: "1" },
  { name: "Retrouvailles avec la sorcière", index: "2" },
  { name: "Une vie qui commence de zéro dans un autre monde", index: "3" },
  { name: "Dans l'intimité du manoir Roswaal", index: "4" },
  { name: "Au loin, le matin promis", index: "5" },
  { name: "Le Cliquetis de la chaîne", index: "6" },
  { name: "Retour à la case départ pour Subaru Natsuki", index: "7" },
  { name: "Sèche tes larmes après avoir pleuré sans répit", index: "8" },
  { name: "Le Sens du courage", index: "9" },
  { name: "Une méthode d'ogre", index: "10" },
  { name: "Rem", index: "11" },
  { name: "Retour à la capitale", index: "12" },
  { name: "Subaru Natsuki, chevalier autoproclamé", index: "13" },
  { name: "La Maladie du désespoir", index: "14" },
  { name: "Au bord de la folie", index: "15" },
  { name: "Les Désirs d'un porc", index: "16" },
  { name: "Couvert de honte", index: "17" },
  { name: "De zéro", index: "18" },
  { name: "Chasse à la baleine blanche", index: "19" },
  { name: "Wilhelm van Astrea", index: "20" },
  { name: "Un pari contre le désespoir", index: "21" },
  { name: "Éclair de paresse", index: "22" },
  { name: "Diabolique paresse", index: "23" },
  { name: "Le chevalier autoproclamé et le chevalier modèle", index: "24" },
  { name: "Une simple histoire", index: "25" },
  { name: "Les serments de chacun", index: "26" },
  { name: "La prochaine destination", index: "27" },
  { name: "Des retrouvailles tant attendues", index: "28" },
  { name: "Parents et enfant", index: "29" },
  { name: "Un pas en avant", index: "30" },
  { name: "L'Évangile de la fillette", index: "31" },
  { name: "Un ami", index: "32" },
  { name: "La valeur d'une vie", index: "33" },
  { name: "LOVE LOVE LOVE YOU", index: "34" },
  { name: "Je connais l'enfer", index: "35" },
  { name: "Le goût de la mort", index: "36" },
  { name: "La réception des sorcières", index: "37" },
  { name: "Un son accablant", index: "38" },
  { name: "STRAIGHT BET", index: "39" },
  { name: "Otto Suwen - Une raison de croire", index: "40" },
  { name: "La pierre de Kwain ne peut être soulevée sans aide", index: "41" },
  { name: "L'itinéraire de la mémoire", index: "42" },
  { name: "Le jour où Alpha d’Orion a ri", index: "43" },
  { name: "Le permafrost de la forêt d'Elior", index: "44" },
  {
    name: "Le commencement du Sanctuaire, et le début de sa chute",
    index: "45",
  },
  { name: "Des retrouvailles bestiales", index: "46" },
  { name: "Le bonheur reflété à la surface de l'eau", index: "47" },
  { name: "L'amour du sang et des entrailles", index: "48" },
  { name: "Choisis-moi", index: "49" },
  { name: "De fous pas de danse sous la lune", index: "50" },
  { name: "Malice théâtrale", index: "51" },
];

export default episodes;
