const names = [
  { name: "Ils sont marrants, les seconde de cette année", index: "1" },
  { name: "Je veux faire des plaquages", index: "2" },
  { name: "Le plus important", index: "3" },
  { name: "Que dois-je faire ?", index: "4" },
  { name: "Ce qui manque", index: "5" },
  { name: "Tout donner", index: "6" },
  { name: "Je veux apprendre à tout faire", index: "7" },
  { name: "La baballe", index: "8" },
  { name: "Vous avez progressé", index: "9" },
  { name: "J’ai mangé trop de glace pilée", index: "10" },
  { name: "Tu n'es pas doué", index: "11" },
  { name: "Entraînement conjoint", index: "12" },
  { name: "Objectif Ryôgoku", index: "13" },
  { name: "Le jour X", index: "14" },
  { name: "Coéquipiers", index: "15" },
  { name: "Vous vous êtes préparés", index: "16" },
  { name: "Le stage d'été", index: "17" },
  { name: "Apprends", index: "18" },
  { name: "Je ne pleure pas", index: "19" },
  { name: "Tu n'es pas heureux", index: "20" },
  { name: "Porte-bonheur", index: "21" },
  { name: "Ton territoire", index: "22" },
  { name: "Mon pote me l'a appris", index: "23" },
  { name: "Un adversaire absolument injouable", index: "24" },
  { name: "All out", index: "25" },
];

export default names;
