const episodes = [
  { name: "Stone World", index: "1" },
  { name: "King of the Stone World", index: "2" },
  { name: "Les Armes de la Science", index: "3" },
  { name: "Allumons un signal de fumée", index: "4" },
  { name: "Stone World The Beginning", index: "5" },
  { name: "Les Deux nations du monde de pierre", index: "6" },
  { name: "2 millions d'années en lieu sûr", index: "7" },
  { name: "Stone Road", index: "8" },
  { name: "Nous brandirons la lumière de la science", index: "9" },
  { name: "Une alliance frivole", index: "10" },
  { name: "Clear World", index: "11" },
  { name: "J'assurerai tes arrières, et toi, les miens", index: "12" },
  { name: "Le Guerrier masqué", index: "13" },
  { name: "Master of Flame", index: "14" },
  { name: "2 millions d'années cristallisées", index: "15" },
  { name: "Histoire du temps jadis", index: "16" },
  { name: "Cents nuits et mille cieux", index: "17" },
  { name: "Stone Wars", index: "18" },
  { name: "En route vers l'ère moderne", index: "19" },
  { name: "L'Ère de l'énergie cinétique", index: "20" },
  { name: "Club de travaux manuels spartiate", index: "21" },
  { name: "The Treasure", index: "22" },
  { name: "Déferlante scientifique", index: "23" },
  { name: "Que nos voix portent vers l'infini", index: "24" },
  { name: "Stone Wars Beginning", index: "25" },
  { name: "Hot Line", index: "26" },
  { name: "Un coup de fil du défunt", index: "27" },
  { name: "Tous à l'attaque", index: "28" },
  { name: "Steam Gorilla", index: "29" },
  { name: "Prison Break", index: "30" },
  { name: "Une mission ultra-secrète", index: "31" },
  { name: "Final Battle", index: "32" },
  { name: "Ceux que l'on brise et ceux que l'on sauve", index: "33" },
  { name: "Le duo le plus fort de l'humanité", index: "34" },
  { name: "Prologue of Dr. Stone", index: "35" },
  { name: "New World Map", index: "36" },
  { name: "Désirs = Justice", index: "37" },
  { name: "Premier contact", index: "38" },
  { name: "Les yeux de la science", index: "39" },
  { name: "Perseus, le navire de la science", index: "40" },
  { name: "Treasure Box", index: "41" },
  { name: "La lumière de l'espoir et du désespoir", index: "42" },
  { name: "Notre atout est dans le navire de la science", index: "43" },
  { name: "La science de la beauté", index: "44" },
  { name: "Science Wars", index: "45" },
  { name: "Le miracle, tu l'accompliras de tes mains", index: "46" },
  { name: "Le royaume de la science contre-attaque", index: "47" },
  { name: "Le vrai visage de Medusa", index: "48" },
  { name: "Jeu de négociation cérébral", index: "49" },
  { name: "La bataille en trois dimensions", index: "50" },
  { name: "Guerre totale", index: "51" },
  { name: "JOKER", index: "52" },
  { name: "L'éclat de la destruction", index: "53" },
  { name: "Last Man Standing", index: "54" },
  { name: "First Dream", index: "55" },
  { name: "L'île aux trésors", index: "56" },
  { name: "Beyond the New World", index: "57" },
  { name: "Dr. Stone: Ryusui", index: "58" },
];

export default episodes;
