const episodes = [
  { index: '1', name: 'Asta et Yuno' },
  { index: '2', name: 'Le Serment' },
  { index: '3', name: 'En route pour la capitale !' },
  { index: '4', name: 'Le Test de Recrutement' },
  { index: '5', name: 'Premiers Pas' },
  { index: '6', name: 'Le Taureau Noir' },
  { index: '7', name: 'La seconde Recrue' },
  { index: '8', name: 'Première Mission' },
  { index: '9', name: 'La Bête' },
  { index: '10', name: 'Le Défenseur' },
  { index: '11', name: 'Visite à la Basse-Ville' },
  { index: '12', name: 'Rencontre avec l’Empereur-Mage' },
  { index: '13', name: 'Rencontre avec l’Empereur-Mage : Suite' },
  { index: '14', name: 'Donjon' },
  { index: '15', name: 'Le Mage de Diamond' },
  { index: '16', name: 'Solidarité' },
  { index: '17', name: 'Le Destructeur' },
  { index: '18', name: 'Réminescences' },
  { index: '19', name: 'Effondrement et sauvetage' },
  { index: '20', name: 'Rassemblement à la cité royale' },
  { index: '21', name: 'La cité royale s’embrase' },
  { index: '22', name: 'Des sorts à la pelle' },
  { index: '23', name: 'Le Lion flamboyant' },
  { index: '24', name: 'Blackout' },
  { index: '25', name: 'Dans l’adversité' },
  { index: '26', name: 'Comme un animal blessé' },
  { index: '27', name: 'Lumière' },
  { index: '28', name: 'L’élu de mon cœur' },
  { index: '29', name: 'La voie' },
  { index: '30', name: 'Magie de miroir' },
  { index: '31', name: 'Poursuite dans la neige' },
  { index: '32', name: 'Pousses de trèfle' },
  { index: '33', name: 'Un jour", aimer quelqu’un' },
  { index: '34', name: 'Magie de lumière VS Magie de ténèbres' },
  { index: '35', name: 'Lumière punitive' },
  { index: '36', name: 'Trois yeux' },
  { index: '37', name: 'Le sans-magie' },
  { index: '38', name: 'La réunion des capitaines' },
  { index: '39', name: 'Le salut des trois feuilles' },
  { index: '40', name: 'Les taureaux noirs à la plage' },
  { index: '41', name: 'La fille de l’eau' },
  { index: '42', name: 'Le sanctuaire englouti' },
  { index: '43', name: 'Sanctuary Battle Royale' },
  { index: '44', name: 'L’enflammé et l’électrisé' },
  { index: '45', name: 'Obstiné' },
  { index: '46', name: 'L’éveil' },
  { index: '47', name: 'Ma seule arme' },
  { index: '48', name: 'Espoir VS désespoir' },
  { index: '49', name: 'Au-delà des limites' },
  { index: '50', name: 'Au bout du combat", la fin du désespoir' },
  { index: '51', name: 'La preuve' },
  { index: '52', name: 'Le plus fort l’emporte' },
  { index: '53', name: 'Derrière le masque' },
  { index: '54', name: 'Plus jamais' },
  { index: '55', name: 'Un homme nommé Fanzell' },
  { index: '56', name: 'Un homme nommé Fanzell : suite' },
  { index: '57', name: 'Infiltration' },
  { index: '58', name: 'Dans le feu de l’action' },
  { index: '59', name: 'Les flammes de la haine' },
  { index: '60', name: 'Pénitence' },
  { index: '61', name: 'Le monde promis' },
  { index: '62', name: 'Mutuellement' },
  { index: '63', name: 'Moins que rien' },
  { index: '64', name: 'Le fil rouge du destin' },
  { index: '65', name: 'Retour au bercail' },
  { index: '66', name: 'Le secret de l’œil maléfique' },
  { index: '67', name: 'Un double rencard animé' },
  { index: '68', name: 'Combat à mort ? Yami contre Jack' },
  { index: '69', name: 'La fille épineuse' },
  { index: '70', name: 'Deux nouvelles stars' },
  { index: '71', name: 'La lionne invaincue' },
  { index: '72', name: 'Le feu de Saint-Elme' },
  { index: '73', name: 'La sélection des chevaliers royaux' },
  { index: '74', name: 'La floraison promise' },
  { index: '75', name: 'Un combat acharné' },
  { index: '76', name: 'Le Mage X' },
  { index: '77', name: 'Règlement de Compte' },
  { index: '78', name: 'Piège de Gueux' },
  { index: '79', name: 'Racaille VS Boule de Muscles' },
  { index: '80', name: 'Le Cadet Prodige VS L’Ainé Raté' },
  { index: '81', name: 'Un Destin Tragique' },
  { index: '82', name: 'Mini Clover – Le Cauchemar de Charmy' },
  { index: '83', name: 'Grave-toi ça dans le Crâne' },
  { index: '84', name: 'Les Grands Vainqueurs' },
  { index: '85', name: 'Mis à Nu' },
  { index: '86', name: 'Yami et Vangeance' },
  { index: '87', name: 'La composition des chevaliers royaux' },
  { index: '88', name: 'A l’assaut de l’antre de l’ennemi' },
  { index: '89', name: 'Le Siège du Taureau Noir' },
  { index: '90', name: 'Un Combat Magique Titanesque' },
  { index: '91', name: 'Mereoleona VS Ryah le Perfide' },
  { index: '92', name: 'L’Empereur-Mage VS Le chef de l’œil maléfique' },
  { index: '93', name: 'Julius Novachrono' },
  { index: '94', name: 'Un Nouvel Avenir' },
  { index: '95', name: 'Réincarnations' },
  { index: '96', name: 'Le Capitaine du Taureau Noir VS La Rose écarlate' },
  { index: '97', name: 'Infériorité Écrasante' },
  { index: '98', name: 'Le Lion Endormi' },
  { index: '99', name: 'La survie à tout prix' },
  { index: '100', name: 'Je ne perdrai pas face à toi' },
  { index: '101', name: 'Les Vies de Hadge' },
  { index: '102', name: 'Deux Miracles' },
  { index: '103', name: 'Libération Karmique' },
  { index: '104', name: 'Foudres de la Colère vs Camarades' },
  { index: '105', name: 'Sourires et Larmes' },
  { index: '106', name: 'Vengeance ou Rédemption' },
  { index: '107', name: 'Combat Décisif à la Cité Royale' },
  { index: '108', name: 'La Princesse qui Virevoltait au Combat' },
  { index: '109', name: 'Les Frères Mages Spatiaux' },
  { index: '110', name: 'Le Taureau Noir Enragé déboule' },
  { index: '111', name: 'La Prunelle dans le Miroir' },
  { index: '112', name: 'Un Humain Digne de Confiance' },
  { index: '113', name: 'Le Palais des Ombres' },
  { index: '114', name: 'Le Dernier Arrivé' },
  { index: '115', name: 'Le Cerveau' },
  { index: '116', name: 'L’Ennemi Ultime' },
  { index: '117', name: 'L’Heure de Briser le Sceau' },
  { index: '118', name: 'Retrouvailles par-delà l’Espace-Temps' },
  { index: '119', name: 'Le Coup Final' },
  { index: '120', name: 'L’Aube' },
  { index: '121', name: 'Trois Problèmes' },
  { index: '122', name: 'D’un Noir Éclatant' },
  { index: '123', name: 'Les Souvenirs de Nero : Première Partie' },
  { index: '124', name: 'Les Souvenirs de Nero : Deuxième Partie' },
  { index: '125', name: 'Retour au QG' },
  { index: '126', name: 'La Déclaration de la Rose Bleue' },
  { index: '127', name: 'Indices' },
  { index: '128', name: 'En Route vers le Royaume de Heart' },
  { index: '129', name: 'Le Démon Megicula' },
  { index: '130', name: 'Les Caitaines à Nouveau Réunis' },
  { index: '131', name: 'Une Détermination Renouvelée' },
  { index: '132', name: 'Le Réveil du Lion' },
  { index: '133', name: 'Le Réveil du Lion : Suite' },
  { index: '134', name: 'Les Convives' },
  { index: '135', name: 'Le Véritable Élu de mon Coeur' },
  { index: '136', name: 'Le Conte des Abysses Noires' },
  {
    index: '137',
    name: 'Charmy", un Appétit Centenaire", et Gordon", une Solitude Millénaire',
  },
  { index: '138', name: 'Le Successeur de Zara' },
  { index: '139', name: 'Retour au Pays des Sorcières' },
  { index: '140', name: 'La Requête de Julius' },
  { index: '141', name: 'Une famille en Or' },
  { index: '142', name: 'Ceux qui Sont Restés' },
  { index: '143', name: 'Une Balance Déréglée' },
  { index: '144', name: 'Ceux qui veulent Anéantir les Démons' },
  { index: '145', name: 'Sauvetage' },
  { index: '146', name: 'Ceux qui vénèrent les Démons' },
  { index: '147', name: 'L’Énérgie du Désespoir' },
  { index: '148', name: 'La Lumière qui éclaire les Ténèbres' },
  { index: '149', name: 'Deux Choses Recherchées' },
  { index: '150', name: 'Le Défi des Jeunes Filles' },
  { index: '151', name: 'Le Choc ! L’Affrontement des Capitaines' },
  { index: '152', name: 'Tournés vers l’Avenir' },
  { index: '153', name: 'Les Élus' },
  { index: '154', name: 'Le Vice-Capitaine Langris' },
  { index: '155', name: 'Les Cinq Gardiens Élementaires' },
  { index: '156', name: 'L’Éveil du Pouvoir' },
  { index: '157', name: 'Le Trèfle à Cinq Feuilles' },
  { index: '158', name: 'Le Prélude de l’Espoir et du Désespoir' },
  { index: '159', name: 'Le Lac Paisible et l’Ombre de la Forêt' },
  { index: '160', name: 'Le Messager du Royaume de Spade' },
  { index: '161', name: 'Le Pouvoir de Zenon' },
  { index: '162', name: 'Le Déclenchement de la Grande Guerre' },
  { index: '163', name: 'Dante contre le Capitaine du Taureau Noir' },
  { index: '164', name: 'Heart", Champ de Bataille' },
  { index: '165', name: 'La Guerre Sainte de l’Eau' },
  { index: '166', name: 'Le Capitaine Yami Sukehiro' },
  { index: '167', name: 'Le Serment Noir' },
  { index: '168', name: 'La Marque des Plus Forts' },
  { index: '169', name: 'Le Rituel d’Asservissement du Démon' },
  { index: '170', name: 'Un Avenir Lointain' },
];

export default episodes;
