const names = [
  { index: "1", name: "Un cocktail dangereux" },
  { name: "Tuez-moi, s’il vous plaît", index: "2" },
  { name: "Le dernier combat", index: "3" },
  { name: "Bienvenue en enfer", index: "4" },
  { name: "Un triste anniversaire", index: "5" },
  { name: "La délivrance", index: "6" },
  { name: "La petite fille sur la balançoire", index: "7" },
  { name: "Coup double", index: "8" },
  { name: "Des jeux dangereux", index: "9" },
  { name: "Un professeur spécial", index: "10" },
  { name: "La tulipe noire", index: "11" },
  { name: "Encore un enfant", index: "12" },
  { name: "Le coup de foudre", index: "13" },
  { name: "Une mariée à 16 ans", index: "14" },
  { name: "Le chevalier blanc", index: "15" },
  { name: "L’hôtesse de l’air", index: "16" },
  { name: "Le premier baiser", index: "17" },
  { name: "Prémonition", index: "18" },
  { name: "Un beau souvenir", index: "19" },
  { name: "Une dure journée", index: "20" },
  { name: "Un pari dangereux", index: "21" },
  { name: "Un amour compliqué", index: "22" },
  { name: "Une mariée qui tombe du ciel", index: "23" },
  { name: "Une infirmière dévouée", index: "24" },
  { name: "Un beau calibre", index: "25" },
  { name: "Un premier amour", index: "26" },
  { name: "Une très belle histoire (1/2)", index: "27" },
  { name: "Une très belle histoire (2/2)", index: "28" },
  { name: "Un juste prix", index: "29" },
  { name: "Un rival peu dangereux", index: "30" },
  { name: "Double travail", index: "31" },
  { name: "Une affaire de professionnels", index: "32" },
  { name: "Première mélodie d’amour", index: "33" },
  { name: "Un papa surprise", index: "34" },
  { name: "Une grande journaliste", index: "35" },
  { name: "Au secours je t’aime", index: "36" },
  { name: "Une fille d’honneur (1/2)", index: "37" },
  { name: "Une fille d’honneur (2/2)", index: "38" },
  { name: "Une princesse encombrante", index: "39" },
  { name: "La larme de Cléôpatre", index: "40" },
  { name: "Belle et obstinée (1/2)", index: "41" },
  { name: "Le meilleur père du monde (2/2)", index: "42" },
  { name: "Les trois grains de beauté", index: "43" },
  { name: "Un héros exemplaire", index: "44" },
  { name: "Les trois sœurs", index: "45" },
  { name: "Le crime ne paie pas", index: "46" },
  { name: "Nicky a des problèmes", index: "47" },
  { name: "La jolie veuve", index: "48" },
  { name: "Une sœur encombrante", index: "49" },
  { name: "Un anniversaire terrible (1/2)", index: "50" },
  { name: "Un anniversaire terrible (2/2)", index: "51" },
  { name: "La jeune fiancée de Nicky (1/2)", index: "52" },
  { name: "La jeune fiancée de Nicky (2/2)", index: "53" },
  { name: "Laura est en danger (1/2)", index: "54" },
  { name: "Laura est en danger (2/2)", index: "55" },
  { name: "Contes d’auteur", index: "56" },
  { name: "Un beau modèle", index: "57" },
  { name: "Mission au paradis", index: "58" },
  { name: "Un policier efficace", index: "59" },
  { name: "Un beau motard", index: "60" },
  { name: "La princesse amoureuse (1/2)", index: "61" },
  { name: "La princesse amoureuse (2/2)", index: "62" },
  { name: "Le grand combat", index: "63" },
  { name: "La fausse dent", index: "64" },
  { name: "L’amour est plus fort que l’argent", index: "65" },
  { name: "Une vengeance tardive (1/2)", index: "66" },
  { name: "Une vengeance tardive (2/2)", index: "67" },
  { name: "La belle étrangère (1/2)", index: "68" },
  { name: "La belle étrangère (2/2)", index: "69" },
  { name: "Laura, au travail", index: "70" },
  { name: "Laura perd la mémoire", index: "71" },
  { name: "Tireurs d’élite", index: "72" },
  { name: "La belle photographe (1/2)", index: "73" },
  { name: "La belle photographe (2/2)", index: "74" },
  { name: "La ninja de charme", index: "75" },
  { name: "Un témoin de charme (1/2)", index: "76" },
  { name: "Un témoin de charme (2/2)", index: "77" },
  { name: "La réhabilitation d’un héros (1/2)", index: "78" },
  { name: "La réhabilitation d’un héros (2/2)", index: "79" },
  { name: "Une affaire de cœur", index: "80" },
  { name: "Balade en mer", index: "81" },
  { name: "Adieu l’ami (1/2)", index: "82" },
  { name: "Adieu l’ami (2/2)", index: "83" },
  { name: "Les fausses plaques (1/2)", index: "84" },
  { name: "Les fausses plaques (2/2)", index: "85" },
  { name: "Une élève douée", index: "86" },
  { name: "Nicky a bon goût", index: "87" },
  { name: "Joyeux Noël (1/2)", index: "88" },
  { name: "Joyeux Noël (2/2)", index: "89" },
  { name: "La fiancée de Mammouth (1/2)", index: "90" },
  { name: "La fiancée de Mammouth (2/2)", index: "91" },
  { name: "Un don précieux (1/2)", index: "92" },
  { name: "Un don précieux (2/2)", index: "93" },
  { name: "L’épreuve (1/2)", index: "94" },
  { name: "L’épreuve (2/2)", index: "95" },
  { name: "Une jeune veuve trop sage (1/2)", index: "96" },
  { name: "Une jeune veuve trop sage (2/2)", index: "97" },
  { name: "La petite infirme (1/2)", index: "98" },
  { name: "La petite infirme (2/2)", index: "99" },
  { name: "Chantage atomique (1/2)", index: "100" },
  { name: "Chantage atomique (2/2)", index: "101" },
  { name: "La boule de cristal", index: "102" },
  { name: "La sœur de Laura (1/2)", index: "103" },
  { name: "La sœur de Laura (2/2)", index: "104" },
  { name: "Des soupirants empressés (1/2)", index: "105" },
  { name: "Des soupirants empressés (2/2)", index: "106" },
  { name: "L’agence immobilière (1/2)", index: "107" },
  { name: "Le porte-bonheur (2/2)", index: "108" },
  { name: "Le petit roi (1/2)", index: "109" },
  { name: "Le petit roi (2/2)", index: "110" },
  { name: "Tour de magie", index: "111" },
  { name: "Le grand amour (1/3)", index: "112" },
  { name: "Un grand amour (2/3)", index: "113" },
  { name: "Un grand amour (3/3)", index: "114" },
  { name: "La belle écologiste", index: "115" },
  { name: "La belle avocate", index: "116" },
  { name: "Un mariage de raison", index: "117" },
  { name: "Petit jeu dangereux (1/2)", index: "118" },
  { name: "Petit jeu dangereux (2/2)", index: "119" },
  { name: "Mammouth est jaloux", index: "120" },
  { name: "La belle océanographe", index: "121" },
  { name: "Une élève douée", index: "122" },
  { name: "Sale temps", index: "123" },
  { name: "Un Noël très blanc (1/2)", index: "124" },
  { name: "Un Noël très blanc (2/2)", index: "125" },
  { name: "Vendetta d’amour (1/2)", index: "126" },
  { name: "Vendetta d’amour (2/2)", index: "127" },
  { name: "Une beauté tombée du ciel", index: "128" },
  { name: "Un policier zélé", index: "129" },
  { name: "La princesse cascadeuse", index: "130" },
  { name: "Une femme avisée", index: "131" },
  { name: "Un fantôme de charme (1/2)", index: "132" },
  { name: "Un fantôme de charme (2/2)", index: "133" },
  { name: "Une journée comme une autre", index: "134" },
  { name: "Une vieille haine (1/2)", index: "135" },
  { name: "L’injustice évitée (2/2)", index: "136" },
  { name: "Cendrillon Laura", index: "137" },
  { name: "Un homme très pressé", index: "138" },
  { name: "Le collier", index: "139" },
  { name: "L’ange exterminateur", index: "140" },
];

export default names;
