const episodes = [
  { name: "Undertaker", index: "1" },
  { name: "Spearhead", index: "2" },
  { name: "Je veux pas mourir", index: "3" },
  { name: "Leur véritable nom", index: "4" },
  { name: "À vos côtés", index: "5" },
  { name: "Jusqu'à la fin", index: "6" },
  { name: "Vous vous souviendrez de nous ?", index: "7" },
  { name: "Partons", index: "8" },
  { name: "Adieu", index: "9" },
  { name: "Merci", index: "10" },
  { name: "On arrive", index: "11" },
  { name: "Bienvenue", index: "12" },
  { name: "Il est trop tard pour ça", index: "13" },
  { name: "On compte sur toi", index: "14" },
  { name: "Ravie de vous revoir", index: "15" },
  { name: "Tant pis", index: "16" },
  { name: "Je ne l'oublierai pas", index: "17" },
  { name: "En réalité", index: "18" },
  { name: "Il vaudrait mieux pour nous", index: "19" },
  { name: "Ensemble jusqu'à la mort", index: "20" },
  { name: "C'est tout ce qu'il me reste", index: "21" },
  { name: "Shin", index: "22" },
  { name: "Handler-1", index: "23" },
];

export default episodes;
