const names = [
  { name: "Rêve et Réalité", index: "1" },
  { name: "Idiots et Intelligents", index: "2" },
  { name: "Parents et Enfants", index: "3" },
  { name: "Temps et Clé", index: "4" },
  { name: "Été et Story-boards", index: "5" },
  { name: "Carotte et Bâton", index: "6" },
  { name: "Larmes et Larmes", index: "7" },
  { name: "Anxiété et Espoirs", index: "8" },
  { name: "Regrets et Compréhension", index: "9" },
  { name: "10 et 2", index: "10" },
  { name: "Chocolats et NEXT!", index: "11" },
  { name: "Festin et Fin du collège", index: "12" },
  { name: "Premiers résultats et Résultats harmonisés", index: "13" },
  { name: "Combat et Imitation", index: "14" },
  { name: "Débuts et Impatience", index: "15" },
  { name: "Mur et Baiser", index: "16" },
  { name: "Grosse tête et Gentillesse", index: "17" },
  { name: "Jalousie et Amour", index: "18" },
  { name: "Deux et Un", index: "19" },
  { name: "Collaboration et Conditions", index: "20" },
  { name: "Littérature et Musique", index: "21" },
  { name: "Union et Rupture", index: "22" },
  { name: "Mardi et Vendredi", index: "23" },
  { name: "Téléphone et Veille au soir", index: "24" },
  { name: "Oui et Non", index: "25" },
  { name: "Silence et Festin", index: "26" },
  { name: "Anthologie et Album", index: "27" },
  { name: "Fenêtre et Neige", index: "28" },
  { name: "Mesure choc et Patience", index: "29" },
  { name: "Humour et Nouvelles", index: "30" },
  { name: "Maladie et Motivation", index: "31" },
  { name: "La vie et la mort, et Le calme", index: "32" },
  { name: "Rappel et Appel", index: "33" },
  { name: "Redémarrage et Chute", index: "34" },
  { name: "Gags et Sérieux", index: "35" },
  { name: "Manga et Jeunesse", index: "36" },
  { name: "Expérience et Données", index: "37" },
  { name: "Alliance et Condisciple", index: "38" },
  { name: "Doute et Confiance", index: "39" },
  { name: "Singe et Mariage", index: "40" },
  { name: "Prince et Messie", index: "41" },
  { name: "Amis à part et Province", index: "42" },
  { name: "Réclamation et Cri", index: "43" },
  { name: "Liens et Étoiles", index: "44" },
  { name: "Adoration et Refus", index: "45" },
  { name: "Caprices et Conseils", index: "46" },
  { name: "Indice et Mieux", index: "47" },
  { name: "Victoire et Défaite", index: "48" },
  { name: "Expression et Imagination", index: "49" },
  { name: "Vote et Face", index: "50" },
  { name: "Entêtement et Décision", index: "51" },
  { name: "Tous les soirs et Fusion", index: "52" },
  { name: "Apothéose et Code", index: "53" },
  { name: "Aisance et Piège", index: "54" },
  { name: "Step et Watch", index: "55" },
  { name: "Punch et Envol", index: "56" },
  { name: "Photo-souvenir et Salle de classe", index: "57" },
  { name: "Objectif et Appréciation", index: "58" },
  { name: "Confiance et Résolution", index: "59" },
  { name: "Considérations et Provocations", index: "60" },
  { name: "Agacement et Renversement de situation", index: "61" },
  { name: "Passion et Cuisante défaite", index: "62" },
  { name: "Imitation et Inconscient", index: "63" },
  { name: "Successif et Entrave", index: "64" },
  { name: "Premières pages et Pages centrales", index: "65" },
  { name: "Dernier chapitre et Commentaires", index: "66" },
  { name: "Zombies et Démons", index: "67" },
  { name: "Hebdomadaire et Mensuel", index: "68" },
  { name: "Rallonge et Coup sec", index: "69" },
  { name: "Bouffée d'air et Fête", index: "70" },
  { name: "Thermes et Volonté réaffirmée", index: "71" },
  { name: "Rectificatif et Déclaration", index: "72" },
  { name: "Micro et Script", index: "73" },
  { name: "Façon d'être et Façon de finir", index: "74" },
  { name: "Rêve et Réalité", index: "75" },
];

export default names;
