const names = [
  { name: "Shinra Kusakabe s'engage dans la Fire Force", index: "1" },
  { name: "Le Cœur d'un membre de la Fire Force", index: "2" },
  { name: "Le tournoi des nouvelles recrues", index: "3" },
  { name: "Le Héros et la Princesse", index: "4" },
  { name: "Début des hostilités", index: "5" },
  { name: "La Promesse de Hibana", index: "6" },
  { name: "Début de l'enquête sur la 1re brigade", index: "7" },
  { name: "L'Insecte des flammes", index: "8" },
  { name: "Un mal de plus en plus grand", index: "9" },
  { name: "Promesse", index: "10" },
  {
    name: "La formation de la 8e brigade - Un redoutable pompier",
    index: "11",
  },
  { name: "La nuit avant la bataille d'Asakusa", index: "12" },
  { name: "Piège", index: "13" },
  { name: "Des flammes au service de l'humanité", index: "14" },
  { name: "Le Rêve d'un forgeron", index: "15" },
  { name: "Nous sommes une famille", index: "16" },
  { name: "Noir, blanc et gris", index: "17" },
  { name: "Le Secret de l'allumage", index: "18" },
  { name: "Vers les souterrains", index: "19" },
  { name: "Avec fierté", index: "20" },
  { name: "Connexion", index: "21" },
  { name: "Obstination", index: "22" },
  { name: "Sourire", index: "23" },
  { name: "Passé enflammé", index: "24" },
  { name: "Un combat de pompiers - Un combat d'hommes", index: "25" },
  { name: "Les Flammes de la folie", index: "26" },
  { name: "Une nouvelle braise", index: "27" },
  { name: "Recherche dans les flammes", index: "28" },
  { name: "Le Kata du démon - Le plan", index: "29" },
  { name: "Choix", index: "30" },
  { name: "En route vers l'oasis", index: "31" },
  { name: "Le Mal rôde", index: "32" },
  { name: "Cœur", index: "33" },
  { name: "La Dame en noir", index: "34" },
  { name: "Antihéros", index: "35" },
  { name: "L'Ombre née de la lumière divine", index: "36" },
  { name: "Deux borgnes face à face", index: "37" },
  { name: "Le Dieu de la mort", index: "38" },
  { name: "Affrontement à trois", index: "39" },
  { name: "Explosion de sentiments", index: "40" },
  { name: "Sois faible, petit !", index: "41" },
  { name: "La Souffrance d'une sainte - Un homme appelé Assault", index: "42" },
  { name: "La Famille Oze", index: "43" },
  { name: "Arme de destruction", index: "44" },
  { name: "Corps à corps", index: "45" },
  { name: "Situation désespérée", index: "46" },
  { name: "Le Chat de feu", index: "47" },
  { name: "Les Signes d'un grand changement", index: "48" },
];

export default names;
