const names = [
    { "name": "Quelque part ailleurs", "index": "1" },
    { "name": "Épée", "index": "2" },
    { "name": "Troll", "index": "3" },
    { "name": "Un véritable guerrier", "index": "4" },
    { "name": "Le Fils du Troll", "index": "5" },
    { "name": "Le voyage commence", "index": "6" },
    { "name": "Les Normands", "index": "7" },
    { "name": "Au-delà de la mer", "index": "8" },
    { "name": "La Bataille du pont de Londres", "index": "9" },
    { "name": "Ragnarok", "index": "10" },
    { "name": "Un pari", "index": "11" },
    { "name": "Le pays sur la rive lointaine", "index": "12" },
    { "name": "Fils de héros", "index": "13" },
    { "name": "La Lumière de l'aube", "index": "14" },
    { "name": "Après Yule", "index": "15" },
    { "name": "Histoire de bêtes", "index": "16" },
    { "name": "Servant", "index": "17" },
    { "name": "Hors du berceau", "index": "18" },
    { "name": "Un front uni", "index": "19" },
    { "name": "Couronne", "index": "20" },
    { "name": "Réunion", "index": "21" },
    { "name": "Loup solitaire", "index": "22" },
    { "name": "Erreur de jugement", "index": "23" },
    { "name": "FIN DU PROLOGUE", "index": "24" },
    { "name": "Esclaves", "index": "25" },
    { "name": "La ferme de Ketil", "index": "26" },
    { "name": "Le serpent", "index": "27" },
    { "name": "L'éveil", "index": "28" },
    { "name": "La voie du sang", "index": "29" },
    { "name": "Je veux un cheval", "index": "30" },
    { "name": "Ketil au poing de fer", "index": "31" },
    { "name": "Un homme vide", "index": "32" },
    { "name": "Le serment", "index": "33" },
    { "name": "La malédiction de la couronne", "index": "34" },
    { "name": "Le roi et l'épée", "index": "35" },
    { "name": "Pour cet amour perdu", "index": "36" },
    { "name": "Sombres nuages", "index": "37" },
    { "name": "Liberté", "index": "38" },
    { "name": "La tempête", "index": "39" },
    { "name": "Une raison idéale", "index": "40" },
    { "name": "Le chemin du retour", "index": "41" },
    { "name": "Le premier recours", "index": "42" },
    { "name": "La bataille du domaine de Ketil", "index": "43" },
    { "name": "Douleur", "index": "44" },
    { "name": "Le courage", "index": "45" },
    { "name": "L'empereur rebelle", "index": "46" },
    { "name": "Les deux chemins", "index": "47" },
    { "name": "Retour au pays", "index": "48" }
]

export default names;