const names = [
  { name: "Daï, le petit héros", index: "1" },
  { name: "Daï et la princesse Léona", index: "2" },
  { name: "Le Précepteur du héros", index: "3" },
  { name: "La Résurrection de Hadlar", index: "4" },
  { name: "L'Insigne d'Avan", index: "5" },
  { name: "Crocodine, le roi des carnassiers", index: "6" },
  { name: "La Résolution de Maam", index: "7" },
  { name: "L'Attaque des carnassiers", index: "8" },
  { name: "Un Éclat de courage", index: "9" },
  { name: "En Route vers Papnica", index: "10" },
  { name: "Hyunckel à l'épée démoniaque", index: "11" },
  { name: "Notre Superfoudre", index: "12" },
  { name: "Le Moment de vérité", index: "13" },
  { name: "Flazzard, le commandant de feu et de glace", index: "14" },
  { name: "La Terrible barrière", index: "15" },
  { name: "L'Archimage Matoriv", index: "16" },
  { name: "Le Sauveur immortel", index: "17" },
  { name: "Hyunckel contre Hadlar", index: "18" },
  { name: "L'Ultime arcane de l'école Avan", index: "19" },
  { name: "Avant de pouvoir tout trancher", index: "20" },
  { name: "La Décision de Maam", index: "21" },
  { name: "Faisons les magasins", index: "22" },
  { name: "Le Chevalier dragon", index: "23" },
  { name: "Baran, le maître chevalier dragon", index: "24" },
  { name: "La Terreur de l'aura draconique", index: "25" },
  { name: "L'Attaque des guerriers dragons", index: "26" },
  { name: "Larhart, le chevaucheur des terres", index: "27" },
  { name: "Le Secret de Daï", index: "28" },
  { name: "La Fureur de Baran", index: "29" },
  { name: "La Détermination de Popp", index: "30" },
  { name: "Le Père contre le fils", index: "31" },
  { name: "L'Adieu au père", index: "32" },
  { name: "Les Calculs de Zaboéra", index: "33" },
  { name: "Tournoi d'arts martiaux à Romos", index: "34" },
  { name: "Incident en finale", index: "35" },
  { name: "L'Archifiélon contre Chiu", index: "36" },
  { name: "Tout sur un instant", index: "37" },
  { name: "Le Sommet", index: "38" },
  { name: "Rochedémon débarque", index: "39" },
  { name: "Ténèbres, maître contre disciple.", index: "40" },
  { name: "L'Épée suprême", index: "41" },
  { name: "Les Mortes Terres", index: "42" },
  { name: "Le Choc des épées titanesques", index: "43" },
  { name: "Le Héros disparu dans les glaces", index: "44" },
  { name: "Le Guerrier d'orichalque", index: "45" },
  { name: "Le Sort d'annihilation ultime, Medroa", index: "46" },
  { name: "En Route pour la dernière bataille", index: "47" },
  { name: "La Garde rapprochée de Hadlar", index: "48" },
  { name: "Coteries face à face", index: "49" },
  { name: "Le Commando des carnassiers", index: "50" },
  { name: "L'Arcane suprême de l'école d'Avan", index: "51" },
  { name: "Dragons père et fils, à l'attaque", index: "52" },
  { name: "Le Défi de Hadlar", index: "53" },
  { name: "Hadlar contre Baran", index: "54" },
  { name: "Le Cœur noir", index: "55" },
  { name: "Volonté transmise", index: "56" },
  { name: "Le Dieu du monde des ténèbres", index: "57" },
  { name: "Un Sauveteur inattendu", index: "58" },
  { name: "Les Survivants", index: "59" },
  { name: "Daï et Popp", index: "60" },
  { name: "Avan le héros", index: "61" },
  { name: "La Grotte de la purification", index: "62" },
  { name: "Héritage sacré", index: "63" },
  { name: "La Veille du combat", index: "64" },
  { name: "Hyunckel dans les ténèbres", index: "65" },
  { name: "La Lumière aux cinq couleurs", index: "66" },
  { name: "Le haut sort de purification menacé", index: "67" },
  { name: "L'Ultime défi", index: "68" },
  { name: "Conflit au nom de l'amour", index: "69" },
  { name: "La Victoire ou l'annihilation", index: "70" },
  { name: "Le Duel des vrais dragons", index: "71" },
  { name: "Le Dernier coup porté", index: "72" },
  { name: "L'Espoir au milieu des flammes", index: "73" },
  { name: "Le Retour du grand héros", index: "74" },
  { name: "Les Arcanes de purification", index: "75" },
  { name: "La Justice va de l'avant", index: "76" },
  { name: "L'Autre héros", index: "77" },
  { name: "Le Survivant de l'enfer", index: "78" },
  { name: "Hym aux cheveux d'argent", index: "79" },
  { name: "Échec et mat", index: "80" },
  { name: "Duel au jardin d'albâtre", index: "81" },
  { name: "L'Héritière de la justice", index: "82" },
  { name: "Les Dernières volontés de Baran", index: "83" },
  { name: "Que se dresse le chevalier du destin", index: "84" },
  { name: "L'Empereur du mal, Vearn", index: "85" },
  { name: "Le Piège de Killvearn", index: "86" },
  { name: "Attaque décisive", index: "87" },
  { name: "La Robe des ténèbres", index: "88" },
  { name: "L'Arcane de gel du temps", index: "89" },
  { name: "Myst et Kill", index: "90" },
  { name: "La Vérité sur Vearn", index: "91" },
  { name: "La Garde démoniaque du ciel et de la terre", index: "92" },
  { name: "Les joyaux des iris", index: "93" },
  { name: "Au nom de nos liens", index: "94" },
  { name: "Ultime renversement", index: "95" },
  { name: "Comme un éclair", index: "96" },
  { name: "La larme des dieux", index: "97" },
  { name: "La décision de Daï", index: "98" },
  { name: "S'emparer de la victoire", index: "99" },
  { name: "Adieu, surface que j'ai tant aimée", index: "100" },
];

export default names;
