const names = [
  { name: "Hier sera un autre jour", index: "01" },
  { name: "La vengeance aux deux visages", index: "02" },
  { name: "Porte-sabres à louer [1/2]", index: "03" },
  { name: "Porte-sabres à louer [2/2]", index: "04" },
  { name: "Délire artistique", index: "05" },
  { name: "L'étranger à la touffe rouge", index: "06" },
  { name: "Le port de la drogue à Osaka", index: "07" },
  { name: "La légende de l'Est", index: "08" },
  { name: "Le pique-nique du Beatnick", index: "09" },
  { name: "Folie meurtrière", index: "10" },
  { name: "Les jeux de l'amour", index: "11" },
  { name: "Souvenirs en vrac", index: "12" },
  { name: "Les flibustiers de la nuit [1/2]", index: "13" },
  { name: "Les flibustiers de la nuit [2/2]", index: "14" },
  { name: "Fausse monnaie et petite pépée", index: "15" },
  { name: "La montagne du désespoir [1/2]", index: "16" },
  { name: "Berceuse pour un damné [2/2]", index: "17" },
  { name: "La guerre des mots", index: "18" },
  { name: "Mésentente cordiale", index: "19" },
  { name: "La complainte du piège [1/2]", index: "20" },
  { name: "La complainte du piège [2/2]", index: "21" },
  { name: "Quatrième dimension", index: "22" },
  { name: "Le blues du baseball", index: "23" },
  { name: "Drôle d'endroit pour une rencontre [1/3]", index: "24" },
  { name: "Rencontre du troisième type [2/3]", index: "25" },
  { name: "Le Samurai qui ne sentait plus rien [3/3]", index: "26" },
];

export default names;
