const episodes = [
  { name: "Mission 01 - L'opération « Strix »", index: "1" },
  { name: "Mission 02 - Trouver quelqu'un pour jouer la mère", index: "2" },
  { name: "Mission 03 - Préparer l'entretien", index: "3" },
  { name: "Mission 04 - L'entretien à l'école de prestige", index: "4" },
  { name: "Mission 05 - Le résultat de l'entretien", index: "5" },
  { name: "Mission 06 - L'opération ami-ami", index: "6" },
  { name: "Mission 07 - Le second fils de la cible", index: "7" },
  {
    name: "Mission 08 - Le subterfuge pour tromper la police secrète",
    index: "8",
  },
  { name: "Mission 09 - Prouver que l'on est fous amoureux", index: "9" },
  { name: "Mission 10 - L'opération spéciale ballon prisonnier", index: "10" },
  { name: "Mission 11 - La stella", index: "11" },
  { name: "Mission 12 - Le parc aux manchots", index: "12" },
  { name: "Mission 13 - Le projet Apple", index: "13" },
  { name: "Mission 14 - Désarmer la bombe à retardement", index: "14" },
  { name: "Mission 15 - Une nouvelle famille", index: "15" },
  { name: "Mission 16 - Terreur en cuisine", index: "16" },
  { name: "Mission 17 - L'opération Griffou", index: "17" },
  { name: "Mission 18 - Cours particuliers", index: "18" },
  { name: "Mission 19 - Le plan pour se venger de Desmond", index: "19" },
  { name: "Mission 20 - L'inspection de la clinique", index: "20" },
  { name: "Mission 21 - Nocturna", index: "21" },
  {
    name: "Mission 22 - Campbelldon, le tournoi de tennis clandestin",
    index: "22",
  },
  { name: "Mission 23 - Une constance inébranlable", index: "23" },
  { name: "Mission 24 - À la fois mère et épouse", index: "24" },
  { name: "Mission 25 - Première approche", index: "25" },
  { name: "Prendre père et mère en filature", index: "26" },
  { name: "Le plan de survie de Bond", index: "27" },
  { name: "Entre mission et famille", index: "28" },
  { name: "La pâtisserie de la sagesse", index: "29" },
  { name: "La traversée de la frontière", index: "30" },
  { name: "La croisière de luxe qui donne des frissons", index: "31" },
  { name: "À qui peut profiter cette mission ?", index: "32" },
  { name: "La symphonie du paquebot", index: "33" },
  { name: "Le coup de main qui change le futur", index: "34" },
  { name: "La station balnéaire", index: "35" },
  { name: "Berlint love", index: "36" },
  { name: "Un membre de la famille", index: "37" },
];

export default episodes;
