const episodes = [
  { index: "1", name: "Une mère et ses enfants" },
  { index: "2", name: "La troisième option" },
  { index: "3", name: "Une série adaptée d'un manga" },
  { index: "4", name: "Acteur" },
  { index: "5", name: "Téléréalité de rencontre" },
  { index: "6", name: "Ego-surfing" },
  { index: "7", name: "Buzz" },
  { index: "8", name: "Première fois" },
  { index: "9", name: "B Komachi" },
  { index: "10", name: "Pression" },
  { index: "11", name: "Idoles" },
  { index: "12", name: "Tokyo Blade" },
  { index: "13", name: "Chassé-croisé" },
  { index: "14", name: "Réécriture" },
  { index: "15", name: "Jouer avec ses tripes" },
  { index: "16", name: "Lever de rideau" },
  { index: "17", name: "Grandir" },
  { index: "18", name: "Soleil" },
  { index: "19", name: "Déclencheur" },
  { index: "20", name: "Rêve" },
  { index: "21", name: "Libération" },
  { index: "22", name: "Liberté" },
  { index: "23", name: "Réunion" },
  { index: "24", name: "Souhait" },
];

export default episodes;
