const episodes = [
  { index: "1", name: "On demande le docteur Tenma" },
  { index: "2", name: "Pouvoirs et responsabilités" },
  { index: "3", name: "Un châtiment excessif" },
  { index: "4", name: "Sauvé et dangereux" },
  { index: "5", name: "La jeune fille d'Heidelberg" },
  { index: "6", name: "L'article manquant" },
  { index: "7", name: "Tragédie" },
  { index: "8", name: "Recherché" },
  { index: "9", name: "Un maître de guerre" },
  { index: "10", name: "Le cambrioleur entremetteur" },
  { index: "11", name: "Les salauds ne meurent jamais" },
  { index: "12", name: "Un orphelinat modèle" },
  { index: "13", name: "Un médecin de campagne" },
  { index: "14", name: "Sans amour on est rien du tout" },
  { index: "15", name: "Be My Baby" },
  { index: "16", name: "La confession de Wolf" },
  { index: "17", name: "Tête de Turcs" },
  { index: "18", name: "Un restauratueur professionnel" },
  { index: "19", name: "L'ombre de Johann" },
  { index: "20", name: "Comme une ombre sur la route" },
  { index: "21", name: "Des vacances heureuses" },
  { index: "22", name: "Le piège de Runge" },
  { index: "23", name: "Les confidences d'Eva" },
  { index: "24", name: "Le repaire du gangster" },
  { index: "25", name: "Un fauteuil pour deux" },
  { index: "26", name: "Un privé… d'alcool" },
  { index: "27", name: "Retrouvailles filiales" },
  { index: "28", name: "Une pelote d'affaire" },
  { index: "29", name: "L'exécution" },
  { index: "30", name: "La décision" },
  { index: "31", name: "Au grand jour" },
  { index: "32", name: "Le sanctuaire" },
  { index: "33", name: "Le jeu de la mort" },
  { index: "34", name: "Hindenburg la rouge" },
  { index: "35", name: "Aveuglés par l'amour ou la haine" },
  { index: "36", name: "Dernier train avant la sortie" },
  { index: "37", name: "Le monstre sans nom" },
  { index: "38", name: "Le diable dans les yeux" },
  { index: "39", name: "L'enfer dans les yeux" },
  { index: "40", name: "Grimmer" },
  { index: "41", name: "Encore un bonbon inspecteur" },
  { index: "42", name: "Le retour du Super Steiner" },
  { index: "43", name: "Encore un bonbon inspecteur" },
  { index: "44", name: "Une confiance aveugle" },
  { index: "45", name: "L'image du monstre" },
  { index: "46", name: "Guet-apens" },
  { index: "47", name: "Aux portes du souvenir" },
  { index: "48", name: "Vacances à Prague" },
  { index: "49", name: "Cruel était son nom" },
  { index: "50", name: "L'enquête se corse" },
  { index: "51", name: "Mobilisation" },
  { index: "52", name: "Drôle d'endroit pour une rencontre" },
  { index: "53", name: "Réminiscences" },
  { index: "54", name: "Du sang sur l'asphalte" },
  { index: "55", name: "Le fils de l'espion" },
  { index: "56", name: "Le journal de l'espion" },
  { index: "57", name: "Les morts ont la vie dure" },
  { index: "58", name: "Profession protecteur" },
  { index: "59", name: "Rendez-vous avec la mort" },
  { index: "60", name: "La rédemption ou la mort" },
  { index: "61", name: "Aux portes du souvenir" },
  { index: "62", name: "Les avions en papier" },
  { index: "63", name: "Sans mobile apparent" },
  { index: "64", name: "Le bébé déprime" },
  { index: "65", name: "Sur les traces de Johann" },
  { index: "66", name: "Les origines du monstre" },
  { index: "67", name: "Je suis tu" },
  { index: "68", name: "Un village sans histoire" },
  { index: "69", name: "Coups de feu dans les montagnes" },
  { index: "70", name: "Du sang sous la pluie" },
  { index: "71", name: "La colère de Super-Steiner" },
  { index: "72", name: "La maison du vampire" },
  { index: "73", name: "En attendant l'apocalypse" },
  { index: "74", name: "Monster VS Monster" },
];

export default episodes;
