const names = [
  { name: "L'attaque de l'ange", index: "1" },
  { name: "Plafonds inconnus", index: "2" },
  { name: "Le téléphone ne sonne pas", index: "3" },
  { name: "La pluie, après la fuite", index: "4" },
  { name: "Rei, par-delà son cœur", index: "5" },
  { name: "Combat décisif à Tokyo-3", index: "6" },
  { name: "Construit par l'homme", index: "7" },
  { name: "L'arrivée d'Asuka au Japon", index: "8" },
  { name: "Juste un instant, les cœurs, à l'unisson", index: "9" },
  { name: "Magmadiver", index: "10" },
  { name: "Dans les ténèbres immobiles", index: "11" },
  { name: "De la valeur d'un miracle", index: "12" },
  { name: "L'ange. La pénétration", index: "13" },
  { name: "Seele, trône de l'âme", index: "14" },
  { name: "Mensonges et silence", index: "15" },
  { name: "La désespérance, et après...", index: "16" },
  { name: "Le quatrième qualifié", index: "17" },
  { name: "Le droit de vie ou de mort", index: "18" },
  { name: "La guerre d'un homme", index: "19" },
  { name: "Forme du cœur, miroir des gens", index: "20" },
  { name: "Nerv, la naissance", index: "21" },
  { name: "Humain, au moins d'aspect", index: "22" },
  { name: "Larmes", index: "23" },
  { name: "Le dernier messager", index: "24" },
  { name: "Un monde s'achève", index: "25" },
  { name: "La bête qui criait « moi » au centre du monde", index: "26" },
];

export default names;
