const names = [
  { name: "Un chat domestique, un dieu errant et une queue", index: "1" },
  { name: "Comme de la neige", index: "2" },
  { name: "Désastre provoqué", index: "3" },
  { name: "Là où se trouve le bonheur", index: "4" },
  { name: "Frontière", index: "5" },
  { name: "Quelqu’un d’effrayant", index: "6" },
  { name: "Doutes et destinée", index: "7" },
  { name: "Franchir la ligne", index: "8" },
  { name: "Nom", index: "9" },
  { name: "Des êtres méprisables", index: "10" },
  { name: "Dieu délaissé", index: "11" },
  { name: "Dans son souvenir", index: "12" },
  { name: "Rejeter son nom posthume", index: "13" },
  { name: "Un souvenir d’elle", index: "14" },
  { name: "Des liens mensongers", index: "15" },
  { name: "Un vœu", index: "16" },
  { name: "Bénédiction et malédiction", index: "17" },
  { name: "Ce que tu dois faire", index: "18" },
  { name: "Comment prier un dieu", index: "19" },
  { name: "Le dieu des calamités", index: "20" },
  { name: "Le bruit du fil qui se rompt", index: "21" },
  { name: "Un tel souhait du passé", index: "22" },
  { name: "Retour des enfers", index: "23" },
  { name: "Ta voix qui m’appelle", index: "24" },
  { name: "Le message des divinités du bonheur", index: "25" },
];

export default names;
