const names = [
  { index: "1", name: "Izuku Midoriya : Origine" },
  { index: "2", name: "Ce qu’il faut pour être un héros" },
  { index: "3", name: "Muscles rugissants" },
  { index: "4", name: "Ligne de départ" },
  { index: "5", name: "Ce que je peux faire pour le moment" },
  { index: "6", name: "Rage, espèce d’intello" },
  { index: "7", name: "Deku vs. Kacchan" },
  { index: "8", name: "Ligne de départ de Bakugo" },
  { index: "9", name: "Ouais, fais juste de ton mieux, Iida !" },
  { index: "10", name: "Rencontre avec l’inconnu" },
  { index: "11", name: "Game Over" },
  { index: "12", name: "All Might" },
  { index: "13", name: "Dans chacun de nos coeurs" },
  { index: "14", name: "C’est l’idée, Ochaco." },
  { index: "15", name: "Festival des sports rugissants" },
  { index: "16", name: "A leur manière" },
  { index: "17", name: "Stratégie, stratégie, stratégie" },
  { index: "18", name: "Finale de la bataille de cavalerie" },
  { index: "19", name: "Le garçon né avec tout" },
  { index: "20", name: "Victoire ou défaite" },
  { index: "21", name: "Battez-vous, challengers !" },
  { index: "22", name: "Bakugo contre Uraraka" },
  { index: "23", name: "Shoto Todoroki : Origine" },
  { index: "24", name: "Battez-vous, Iida" },
  { index: "25", name: "Todoroki vs. Bakugo" },
  { index: "26", name: "Il est temps de choisir des noms" },
  { index: "27", name: "Bizarre ! Apparition de Gran Torino" },
  { index: "28", name: "Midoriya et Shigaraki" },
  { index: "29", name: "Hero Killer : Tache contre les étudiants de l’U.A." },
  { index: "30", name: "Climax" },
  { index: "31", name: "Les suites de « Hero Killer : Tache  »" },
  { index: "32", name: "Les stages de tout le monde" },
  { index: "33", name: "Écoutez bien ! Un conte du passé" },
  { index: "34", name: "Préparez-vous pour les examens finaux" },
  { index: "35", name: "Yaoyorozu : Rising" },
  { index: "36", name: "Décaper le vernis" },
  { index: "37", name: "Katsuki Bakugo : Origine" },
  { index: "38", name: "Rencontre" },
  { index: "39", name: "Début du jeu" },
  { index: "40", name: "Les chattes sauvages" },
  { index: "41", name: "Kota" },
  { index: "42", name: "Mon Héros" },
  { index: "43", name: "Conduis-le à la maison, Iron Fist ! !!" },
  { index: "44", name: "Roaring Upheaval" },
  { index: "45", name: "Quel rebondissement !" },
  { index: "46", name: "De Iida à Midoriya" },
  { index: "47", name: "Tous pour un" },
  { index: "48", name: "Symbole de la paix" },
  { index: "49", name: "Un pour tous" },
  { index: "50", name: "La fin du début, le début de la fin" },
  { index: "51", name: "Emménagement dans les dortoirs" },
  { index: "52", name: "Créer ces mouvements ultimes" },
  { index: "53", name: "Le test" },
  { index: "54", name: "Shiketsu High Lurking" },
  { index: "55", name: "Classe 1-A" },
  { index: "56", name: "RUSH !" },
  { index: "57", name: "Exercices de sauvetage" },
  { index: "58", name: "Episode spécial : Sauver le monde avec amour !" },
  { index: "59", name: "Quelle est la Grande Idée ?" },
  { index: "60", name: "Une discussion à propos de votre bizarrerie" },
  { index: "61", name: "Deku vs. Kacchan 2" },
  { index: "62", name: "Une saison pour les rencontres" },
  { index: "63", name: "Incomparable" },
  { index: "64", name: "Le scoop sur la classe 1-A de l’U.A." },
  { index: "65", name: "Révision" },
  { index: "66", name: "Un garçon rencontre…" },
  { index: "67", name: "Combattre le destin" },
  { index: "68", name: "Allons-y, Gutsy Red Riot" },
  { index: "69", name: "Une discussion désagréable" },
  { index: "70", name: "GO !!" },
  { index: "71", name: "Suneater of the Big Three" },
  { index: "72", name: "Red Riot" },
  { index: "73", name: "Equipe d’intérimaires" },
  { index: "74", name: "Lemillion" },
  { index: "75", name: "Unforeseen Hope" },
  { index: "76", name: "Infinite 100%" },
  { index: "77", name: "Futur brillant" },
  { index: "78", name: "Flammes fumantes" },
  { index: "79", name: "Gagner le cœur de ces enfants" },
  { index: "80", name: "Secours pour les stagiaires en licence" },
  { index: "81", name: "Fête de l’école" },
  {
    index: "82",
    name: "La préparation du festival de l’école est la partie la plus amusante",
  },
  { index: "83", name: "Conseils en or impériaux" },
  { index: "84", name: "Deku contre le gentil criminel" },
  { index: "85", name: "Début du Festival de l’école !" },
  { index: "86", name: "Laissez-vous aller ! Festival des écoles !" },
  { index: "87", name: "Tableau d’affichage des héros japonais" },
  { index: "88", name: "Son départ" },
  { index: "89", name: "Toutes les mains sur le pont ! Classe 1-A" },
  { index: "90", name: "Vestiges" },
  { index: "91", name: "Clash ! Classe A contre Classe B !" },
  { index: "92", name: "Fais en sorte que ça arrive, Shinso !" },
  { index: "93", name: "Opération Nouveaux Mouvements d’Improvisation" },
  { index: "94", name: "Prévoyance" },
  { index: "95", name: "Match 3" },
  { index: "96", name: "Conclusion du Match 3" },
  { index: "97", name: "L’oiseau du matin !" },
  { index: "98", name: "Ce qui est hérité" },
  { index: "99", name: "Notre bagarre" },
  { index: "100", name: "Le nouveau pouvoir et Tous pour un" },
  { index: "101", name: "Passez un joyeux Noël !" },
  { index: "102", name: "En route pour l’agence Endeavor !" },
  { index: "103", name: "Une chose à la fois" },
  { index: "104", name: "Ça fait longtemps que je ne t’ai pas vu, Selkie" },
  { index: "105", name: "La famille infernale Todoroki" },
  { index: "106", name: "Les impardonnables" },
  { index: "107", name: "Tu voulais tellement être un héros" },
  { index: "108", name: "My Villain Academia" },
  { index: "109", name: "Renaissance" },
  { index: "110", name: "Sad man’s parade" },
  { index: "111", name: "Tenko Shimura : Les Origines" },
  { index: "112", name: "Tomura Shigaraki : Les Origines" },
  { index: "113", name: "Sous un ciel d’azur" },
  { index: "114", name: "Un premier acte discret" },
  { index: "115", name: "Mirko, la numéro cinq" },
  { index: "116", name: "One’s Justice" },
  { index: "117", name: "L’Héritier" },
  { index: "118", name: "Destruction massive" },
  { index: "119", name: "Rencontre (2)" },
  { index: "120", name: "Catastrophe ambulante" },
  { index: "121", name: "Alliance des super-vilains vs Yuei" },
  { index: "122", name: "Katsuki Bakugo : l’envol" },
  { index: "123", name: "Ces personnes dans nos têtes" },
  { index: "124", name: "Danse macabre" },
  { index: "125", name: "Les fils de l’espoir" },
  { index: "126", name: "Le dernier numéro" },
  { index: "127", name: "L’enfer sur terre" },
  { index: "128", name: "Le Tartare" },
  { index: "129", name: "L’enfer des Todoroki (2)" },
  { index: "130", name: "Un feu mal éteint" },
  { index: "131", name: "Izuku Midoriya et Tomura Shigaraki" },
  { index: "132", name: "À fond" },
  { index: "133", name: "L’agent du mal" },
  { index: "134", name: "La sublime lady Nagant" },
  { index: "135", name: "Des amis" },
  { index: "136", name: "Deku vs la 2de A" },
  { index: "137", name: "Cri du cœur" },
  { index: "138", name: "Connexion" },
  { index: "139", name: "Izuku Midoriya: Mind (récapitulatif)" },
  { index: "140", name: "Toshinori Yagi: Embers (récapitulatif)" },
  { index: "141", name: "Heroes: Thoughts (récapitulatif)" },
  { index: "142", name: "Tomura Shigaraki : Destruction (récapitulatif)" },
  { index: "143", name: "Une tornade de puissance venue de l'ouest" },
  { index: "144", name: "Spectre" },
  { index: "145", name: "Super-vilain" },
  { index: "146", name: "Comment nous sommes devenus des héros" },
  { index: "147", name: "Let you down" },
  { index: "148", name: "Division" },
  { index: "149", name: "Inflation" },
  { index: "150", name: "Deux poings incadescents" },
  { index: "151", name: "Figurants" },
  { index: "152", name: "La supernova d'un héros blessé" },
  { index: "153", name: "Light fades to rain" },
  { index: "154", name: "Défenseurs et attaquants" },
];

export default names;
