const episodes = [
  { name: "Entre un monde et l'autre", index: "1" },
  { name: "Junior, roi des enfers", index: "2" },
  { name: "Une amitié à la vie à la mort", index: "3" },
  { name: "Preuve d'amour", index: "4" },
  { name: "Retour à la vie", index: "5" },
  { name: "Les trois démons", index: "6" },
  { name: "Le secret de Kurama", index: "7" },
  { name: "Le monstre aux cent yeux", index: "8" },
  { name: "La chasse est ouverte !", index: "9" },
  { name: "Duel dans les ténèbres", index: "10" },
  { name: "Une bataille éprouvante", index: "11" },
  { name: "La défaite de Kuwabara", index: "12" },
  { name: "Yusuke contre Rando", index: "13" },
  { name: "Le défi du château maléfique", index: "14" },
  { name: "Kurama ou le combat de la rose", index: "15" },
  { name: "Kuwabara et l'épée astrale", index: "16" },
  { name: "Byakko, le dévoreur d'énergie", index: "17" },
  { name: "Le combat de Hiei", index: "18" },
  { name: "Suzaku, le dernier des Shiseiju !", index: "19" },
  { name: "Le combat maléfique", index: "20" },
  { name: "Yusuke contre-attaque", index: "21" },
  { name: "Yukina, la princesse triste", index: "22" },
  { name: "Les messagers des ténèbres", index: "23" },
  { name: "Les Sanki-Shû", index: "24" },
  { name: "La force des sentiments", index: "25" },
  { name: "L'invitation au Tournoi", index: "26" },
  { name: "Le tournoi des arts martiaux de l'ombre", index: "27" },
  { name: "La première rencontre", index: "28" },
  { name: "Du sang sur le ring", index: "29" },
  { name: "Le feu du Dragon Noir", index: "30" },
  { name: "La technique de l'ivrogne", index: "31" },
  { name: "Rencontre mortelle", index: "32" },
  { name: "Le défi des huit finalistes", index: "33" },
  { name: "Le jour de la bataille", index: "34" },
  { name: "Un guerrier fascinant", index: "35" },
  { name: "L'épreuve de la lumière", index: "36" },
  { name: "L'équipe de Masho, les ninjas des ténèbres", index: "37" },
  { name: "Le masque", index: "38" },
  { name: "La colère de Yusuke", index: "39" },
  { name: "Jin, le maître du vent", index: "40" },
  { name: "Un résultat inattendu", index: "41" },
  { name: "La force de l'amour", index: "42" },
  { name: "Le visage du guerrier masqué", index: "43" },
  { name: "L'ultime épreuve", index: "44" },
  { name: "L'onde du Dragon Noir", index: "45" },
  { name: "La transformation de Momotaro", index: "46" },
  { name: "Le légendaire Yoko Kurama", index: "47" },
  { name: "Le point de non-retour", index: "48" },
  { name: "La force illimitée de Genkai", index: "49" },
  { name: "Le défi de Suzuki", index: "50" },
  { name: "Le retour de Toguro", index: "51" },
  { name: "Mortelles retrouvailles", index: "52" },
  { name: "Au-delà de la tristesse", index: "53" },
  { name: "En route pour la finale !", index: "54" },
  { name: "Le réveil de Yoko", index: "55" },
  { name: "Le grand sacrifice", index: "56" },
  { name: "Le mystère de l'armure", index: "57" },
  { name: "L'ultime technique", index: "58" },
  { name: "Un adversaire terrifiant", index: "59" },
  { name: "Le grand pari de Sakyo", index: "60" },
  { name: "Le combat des chefs", index: "61" },
  { name: "Toguro monte en puissance", index: "62" },
  { name: "Une puissance sans limite", index: "63" },
  { name: "L'explication finale", index: "64" },
  { name: "Les adieux de Monsieur Sakyo", index: "65" },
  { name: "Le dernier vœu de Toguro", index: "66" },
  { name: "Nouveau prologue", index: "67" },
  { name: "Le manoir de la quatrième dimension", index: "68" },
  { name: "La ruse de Kurama", index: "69" },
  { name: "Le véritable objectif", index: "70" },
  { name: "La porte des ténèbres", index: "71" },
  { name: "Le visage de l'ennemi", index: "72" },
  { name: "L'effrayant Docteur Kamiya", index: "73" },
  { name: "Et de un !", index: "74" },
  { name: "Embuscade sous la pluie", index: "75" },
  { name: "Le chapitre noir", index: "76" },
  { name: "Un passé sanglant", index: "77" },
  { name: "L'assaut du démon", index: "78" },
  { name: "Course contre la montre", index: "79" },
  { name: "Le pouvoir du tireur", index: "80" },
  { name: "Un univers virtuel", index: "81" },
  { name: "La force cachée de l'ennemi", index: "82" },
  { name: "Une décision héroïque", index: "83" },
  { name: "La colère de Kurama", index: "84" },
  { name: "Duel des détectives", index: "85" },
  { name: "Dure réalité pour Yusuke", index: "86" },
  { name: "Junior et l'anneau anti-maléfice", index: "87" },
  { name: "L'énergie divine", index: "88" },
  { name: "Requiem pour Yusuke", index: "89" },
  { name: "Dans les ténèbres", index: "90" },
  { name: "Le réveil d'un Mazoku", index: "91" },
  { name: "L'étoffe des combattants", index: "92" },
  { name: "Shinobu tire sa révérence", index: "93" },
  { name: "Les uns et les autres", index: "94" },
  { name: "Le destin rattrape Yusuke", index: "95" },
  { name: "Les étranges visiteurs des ténèbres", index: "96" },
  { name: "Au revoir mes amis", index: "97" },
  { name: "Rencontre avec Raizen", index: "98" },
  { name: "Souvenir de naissance", index: "99" },
  { name: "Le secret du troisième œil", index: "100" },
  { name: "Après mille années de séparation", index: "101" },
  { name: "La force meurtrière de Yoko", index: "102" },
  { name: "La mort de Raizen", index: "103" },
  { name: "La proposition de Yusuke", index: "104" },
  { name: "Les épreuves éliminatoires", index: "105" },
  { name: "Entre père et fils", index: "106" },
  { name: "Les déceptions du premier tour", index: "107" },
  { name: "L'adieu au passé", index: "108" },
  { name: "La confrontation entre Hiei et Mokuro", index: "109" },
  { name: "Le doute s'immisce", index: "110" },
  { name: "L'unification des ténèbres", index: "111" },
  { name: "L'héritage", index: "112" },
];

export default episodes;
