const episodes = [
  { name: "Sur la pente aux cerisiers", index: "1" },
  { name: "Le premier pas", index: "2" },
  { name: "Après les larmes", index: "3" },
  { name: "Recrutement", index: "4" },
  { name: "Sculptures à perte de vue", index: "5" },
  { name: "La fête du lycée des sœurs Ibuki", index: "6" },
  { name: "Sentiments en forme d'étoile", index: "7" },
  { name: "Le vent se dissipant au crépuscule", index: "8" },
  { name: "Jusqu'au bout du rêve", index: "9" },
  { name: "Le défi du petit génie", index: "10" },
  { name: "Le capriccio après les cours", index: "11" },
  { name: "Un monde dissimulé", index: "12" },
  { name: "Le Jardin des souvenirs", index: "13" },
  { name: "Theory of everything", index: "14" },
  { name: "Un léger problème", index: "15" },
  { name: "3 on 3", index: "16" },
  { name: "En son absence", index: "17" },
  { name: "Le secret d'une remontée", index: "18" },
  { name: "Son nouveau quotidien", index: "19" },
  { name: "Les secrets du passé", index: "20" },
  { name: "Les préparatifs de la fête", index: "21" },
  { name: "Les ombres qui la hantent", index: "22" },
  { name: "Adieux à l'été", index: "23" },
  { name: "Sur la piste d'un amour fictif", index: "24" },
  { name: "Cœurs en désunion", index: "25" },
  { name: "Avec le même sourire", index: "26" },
  { name: "Une saison avec toi", index: "27" },
  { name: "Toujours à tes côtés", index: "28" },
  { name: "Là où est sa place", index: "29" },
  { name: "Un combat valeureux", index: "30" },
  { name: "En plein milieu de la pente", index: "31" },
  { name: "La saison du commencement", index: "32" },
  { name: "La fête promise", index: "33" },
  { name: "Événement imprévu", index: "34" },
  { name: "Fin d'études", index: "35" },
  { name: "Une nouvelle famille", index: "36" },
  { name: "Poignants vestiges d'été", index: "37" },
  { name: "Ténèbres teintées de blanc", index: "38" },
  { name: "Tragédie estivale", index: "39" },
  { name: "Aux confins de la Terre", index: "40" },
  { name: "À la maison", index: "41" },
  { name: "Espiègle brise marine", index: "42" },
  { name: "La fin du Monde", index: "43" },
  { name: "La paume d'une petite main", index: "44" },
];
export default episodes;
