const names = [
  { index: "1", name: "Ryomen Sukuna" },
  { index: "2", name: "Pour moi-même" },
  { index: "3", name: "La bâtisseuse" },
  { index: "4", name: "Naissance de la matrice – Partie 1" },
  { index: "5", name: "Naissance de la matrice – Partie 2" },
  { index: "6", name: "Après la pluie" },
  { index: "7", name: "Attaque surprise" },
  { index: "8", name: "Ennui" },
  { index: "9", name: "Petit poisson et retour de bâton" },
  { index: "10", name: "Altération absolue" },
  { index: "11", name: "Reflet sur l’eau" },
  { index: "12", name: "Pour toi, un jour" },
  { index: "13", name: "À demain" },
  { index: "14", name: "Le tournoi – épreuve par équipes (0)" },
  { index: "15", name: "Le tournoi – épreuve par équipes (1)" },
  { index: "16", name: "Le tournoi – épreuve par équipes (2)" },
  { index: "17", name: "Le tournoi – épreuve par équipes (3)" },
  { index: "18", name: "Le sage" },
  { index: "19", name: "Rayon noir" },
  { index: "20", name: "Hors norme" },
  { index: "21", name: "Le match de base-ball" },
  { index: "22", name: "Instinct grégaire" },
  { index: "23", name: "Instinct grégaire – Partie 2" },
  { index: "24", name: "Complices" },
  { index: "25", name: "Trésor caché" },
  { index: "26", name: "Trésor caché (2)" },
  { index: "27", name: "Trésor caché (3)" },
  { index: "28", name: "Trésor caché (4)" },
  { index: "29", name: "Mort prématurée" },
  { index: "30", name: "L'explication" },
  { index: "31", name: "La veille de la fête" },
  { index: "32", name: "Le drame de Shibuya" },
  { index: "33", name: "Le drame de Shibuya - Ouverture" },
  { index: "34", name: "Confusion" },
  { index: "35", name: "Invocation de l'âme" },
  { index: "36", name: "Lame émoussée" },
  { index: "37", name: "Les écailles rouges" },
  { index: "38", name: "Oscillations" },
  { index: "39", name: "Oscillations (2)" },
  { index: "40", name: "Un coup de tonnerre" },
  { index: "41", name: "Un coup de tonnerre (2)" },
  { index: "42", name: "Le bien et le mal" },
  { index: "43", name: "Le bien et le mal (2)" },
  { index: "44", name: "Le bien et le mal (3)" },
  { index: "45", name: "Métamorphose" },
  { index: "46", name: "Métamorphose (2)" },
  { index: "47", name: "Le drame de Shibuya - Fermeture" },
];

export default names;
