const episodes = [
  { name: "Le Majordome habile", index: 1 },
  { name: "Le Plus fort des Majordomes", index: 2 },
  { name: "Le Majordome omnipotent", index: 3 },
  { name: "Le Majordome est extravagant", index: 4 },
  { name: "Rencontre avec un Majordome", index: 5 },
  { name: "Le Majordome aux funérailles", index: 6 },
  { name: "Le Majordome s'amuse", index: 7 },
  { name: "Le Majordome dompteur", index: 8 },
  { name: "Le Majordome illusionniste", index: 9 },
  { name: "Le Majordome sur glace", index: 10 },
  { name: "Le Majordome imposteur", index: 11 },
  { name: "Le Majordome se sent seul", index: 12 },
  { name: "Le Majordome et les Parasites", index: 13 },
  { name: "Ce Majordome, quel talent !", index: 14 },
  { name: "Majordome contre Majordome", index: 15 },
  { name: "Le Majordome et le Château abandonné", index: 16 },
  { name: "Le Majordome touché par la grâce", index: 17 },
  { name: "Le Majordome sur tous les fronts", index: 18 },
  { name: "Le Majordome emprisonné", index: 19 },
  { name: "Le Majordome fugitif", index: 20 },
  { name: "Le Majordome recruteur", index: 21 },
  { name: "Le Majordome se rebiffe", index: 22 },
  { name: "Le Majordome incendiaire", index: 23 },
  { name: "Le Majordome volubile", index: 24 },
  { name: "Le Majordome se donne en spectacle", index: 25 },
  { name: "Le Majordome en noir", index: 26 },
  { name: "Le Majordome solitaire", index: 27 },
  { name: "Le Majordome et la femme", index: 28 },
  { name: "Le Majordome terroriste", index: 29 },
  { name: "Pas de Majordome sans fumée", index: 30 },
  { name: "Le Majordome de la nuit", index: 31 },
  { name: "Le Majordome tueur", index: 32 },
  { name: "Le Majordome s'épanche", index: 33 },
  { name: "Le Majordome faussaire", index: 34 },
  { name: "Le Majordome à néant", index: 35 },
  { name: "Le Majordome à la croisée des chemins", index: 36 },
  { name: "Black Butler", index: 37 },
  { name: "Le majordome fait les présentations", index: 38 },
  { name: "Le majordome sur scène", index: 39 },
  { name: "Le majordome est embauché", index: 40 },
  { name: "Le majordome a un collègue", index: 41 },
  { name: "Le majordome volant", index: 42 },
  { name: "Le majordome négocie", index: 43 },
  { name: "Le majordome cajole", index: 44 },
  { name: "Le majordome sourit", index: 45 },
  { name: "Le majordome serein", index: 46 },
  { name: "Le majordome s'exécute", index: 47 },
];

export default episodes;
