const episodes = [
  { index: '1', name: 'Un départ et des amis' },
  { index: '2', name: 'L’épreuve de l’épreuve' },
  { index: '3', name: 'Il faut se battre pour y arriver' },
  { index: '4', name: 'Espoirs et ambitions' },
  { index: '5', name: 'Hisoka est sournois' },
  { index: '6', name: 'Une épreuve étonnante' },
  { index: '7', name: 'Combat décisif à bord du dirigeable' },
  { index: '8', name: 'La majorité l’emporte' },
  { index: '9', name: 'Attention aux prisonniers' },
  { index: '10', name: 'L’occasion fait le larron' },
  { index: '11', name: 'Un pari de maboul' },
  { index: '12', name: 'Un dernier choix pour la route' },
  { index: '13', name: 'Des nouvelles de Gon' },
  { index: '14', name: 'Toucher sa cible' },
  { index: '15', name: 'Tromperies à la chaîne' },
  { index: '16', name: 'Défaite et humiliation' },
  { index: '17', name: 'Piège dans la grotte' },
  { index: '18', name: 'Un entretien décisif' },
  { index: '19', name: 'Victoire impossible, défaite impossible' },
  { index: '20', name: 'Un développement inattendu' },
  { index: '21', name: 'Problème entre frères' },
  { index: '22', name: 'Un dangereux chien de garde' },
  { index: '23', name: 'Les devoirs d’un garde' },
  { index: '24', name: 'La famille Zoldik' },
  { index: '25', name: 'Tu ne le verras pas si tu ne la vois pas' },
  { index: '26', name: 'Avant et après' },
  { index: '27', name: 'Entrée dans l’arène' },
  { index: '28', name: 'Nen et Nen' },
  { index: '29', name: 'Éveil et potentiel' },
  { index: '30', name: 'Combat acharné et querelle' },
  { index: '31', name: 'Destinée et ténacité' },
  { index: '32', name: 'Une victoire stupéfiante' },
  { index: '33', name: 'Une menace insignifiante' },
  { index: '34', name: 'Revanche à armes égales' },
  { index: '35', name: 'Examen véritablement réussi' },
  { index: '36', name: 'Une énorme dette et un petit coup de pied' },
  { index: '37', name: 'Jin et Gon' },
  { index: '38', name: 'La réponse de mon père' },
  { index: '39', name: 'Souhait et serment' },
  { index: '40', name: 'Coopération entre utilisateurs de nen' },
  { index: '41', name: 'Le rassemblement des héros' },
  { index: '42', name: 'Défendre et attaquer' },
  { index: '43', name: 'Une farce tragique' },
  { index: '44', name: 'Préparation au combat' },
  { index: '45', name: 'Contrainte et promesse' },
  { index: '46', name: 'Poursuite et attente' },
  { index: '47', name: 'Condition et serment' },
  { index: '48', name: 'Des yeux bien affutés' },
  { index: '49', name: 'Analyse et poursuite' },
  { index: '50', name: 'Camarades et sabre !' },
  { index: '51', name: 'Un champ de bataille impitoyable!' },
  { index: '52', name: 'Attaque et impact!' },
  { index: '53', name: 'Feinte et stratagème!' },
  { index: '54', name: 'Fausse prédiction?' },
  { index: '55', name: 'Camarades et supercherie!' },
  { index: '56', name: 'Bien-aimée et désastre!' },
  { index: '57', name: 'Initiative et instructions!' },
  { index: '58', name: 'Adieu et révolver!' },
  { index: '59', name: 'Enchères et impatience!' },
  { index: '60', name: 'Règles et commencement!' },
  { index: '61', name: 'Invitation et meilleur ami!' },
  { index: '62', name: 'Réalité et pierres précieuses!' },
  { index: '63', name: 'Un maître impitoyable!' },
  { index: '64', name: 'Progrès et chantage!' },
  { index: '65', name: 'Poing diabolique et pierre-papier-ciseaux!' },
  { index: '66', name: 'Capture et stratagème!' },
  { index: '67', name: '15 et 15!' },
  { index: '68', name: 'Pirates et déductions!' },
  { index: '69', name: 'Confrontation acharnée!' },
  { index: '70', name: 'Volonté et amitié!' },
  { index: '71', name: 'Négociation et transaction!' },
  { index: '72', name: 'Occasion et poursuite!' },
  { index: '73', name: 'Folie et victoire!' },
  { index: '74', name: 'Vainqueurs et vaincus!' },
  { index: '75', name: 'L’ami de Jin et le véritable ami!' },
  { index: '76', name: 'Retrouvailles et compréhension' },
  { index: '77', name: 'Inquiétude et apparition' },
  { index: '78', name: 'Prolifération rapide!' },
  { index: '79', name: 'No Good N.G.L' },
  { index: '80', name: 'Aveu et Désastre!' },
  { index: '81', name: 'Début des combats' },
  { index: '82', name: 'La roulette de Kaito!' },
  { index: '83', name: 'Évolution par influence' },
  { index: '84', name: 'Éveil du destin!' },
  { index: '85', name: 'Ombre et lumière!' },
  { index: '86', name: 'Promesse et réunion!' },
  { index: '87', name: 'Duel et fuite!' },
  { index: '88', name: 'Pierre-papier-ciseaux et point faible!' },
  { index: '89', name: 'Gentillesse et force!' },
  { index: '90', name: 'Intérêts et emprise!' },
  { index: '91', name: 'Les forts et les faibles!' },
  { index: '92', name: 'Un souhait et deux serments!' },
  { index: '93', name: 'Rendez-vous avec Pamu!' },
  { index: '94', name: 'Ami et voyage!' },
  { index: '95', name: 'Ressentiment et bizarreries!' },
  { index: '96', name: 'Résidence illégale!' },
  { index: '97', name: 'Combat féroce et élimination!' },
  { index: '98', name: 'Infiltration et sélection' },
  { index: '99', name: 'Combinaison et évolution' },
  { index: '100', name: 'Traque et contre-attaque' },
  { index: '101', name: 'Ikarugo et éclairs' },
  { index: '102', name: 'Pouvoirs et jeux de stratégie' },
  { index: '103', name: 'Échec et mat et anticipation' },
  { index: '104', name: 'Hésitation et embarras' },
  { index: '105', name: 'Détermination et éveil!' },
  { index: '106', name: 'Nov et Morau!' },
  { index: '107', name: 'Retour et retraite' },
  { index: '108', name: 'Le Gungi de Komugi' },
  { index: '109', name: 'Début de la procession, début de la mission' },
  { index: '110', name: 'Crainte et expectative' },
  { index: '111', name: 'Irruption soudaine' },
  { index: '112', name: 'Monstre et monstre' },
  { index: '113', name: 'Un Insecte d’honneur' },
  { index: '114', name: 'Séparation et erreur de calcul' },
  { index: '115', name: 'Devoir et doutes' },
  { index: '116', name: 'Vengeance et soins' },
  { index: '117', name: 'Un affront à laver' },
  { index: '118', name: 'Fausse colère' },
  { index: '119', name: 'Poulpe fort et poulpe faible' },
  { index: '120', name: 'Faux et vrai' },
  { index: '121', name: 'Défaite et honneur' },
  { index: '122', name: 'Principes et nom' },
  { index: '123', name: 'Centipèdes et souvenirs' },
  { index: '124', name: 'Limite et éveil' },
  { index: '125', name: 'Puissance et apogée des arts martiaux' },
  { index: '126', name: 'Le zéro et la rose' },
  { index: '127', name: 'Hostilité et détermination' },
  { index: '128', name: 'Joie sans pareille et amour inconditionnel' },
  { index: '129', name: 'Cible et objectif' },
  { index: '130', name: 'Magie et désespoir' },
  { index: '131', name: 'Colère et lumière' },
  { index: '132', name: 'Avance et activation' },
  { index: '133', name: 'Espérance de vie' },
  { index: '134', name: 'Un seul mot' },
  { index: '135', name: 'Ce jour, cet instant' },
  { index: '136', name: 'Retour à la maison et vrai nom' },
  { index: '137', name: 'Débat entre zodiaques' },
  { index: '138', name: 'Demande et souhait' },
  { index: '139', name: 'Aruka et Nanika' },
  { index: '140', name: 'Élections et batailles' },
  { index: '141', name: 'Prestidigitateur et intendants' },
  { index: '142', name: 'Aiguille et traque' },
  { index: '143', name: 'Crimes et griffes' },
  { index: '144', name: 'Sanction et ovation' },
  { index: '145', name: 'Défaite et retrouvailles' },
  { index: '146', name: 'Président et annulation' },
  { index: '147', name: 'Salut et avenir' },
  { index: '148', name: 'Passé et futur (Avant et après)' },
];

export default episodes;
