const episodes = [
  { name: "After the rain", index: 1 },
  { name: "Fugitive", index: 2 },
  { name: "Distrust", index: 3 },
  { name: "Dissolve", index: 4 },
  { name: "Someday…", index: 5 },
  { name: "Truth", index: 6 },
  { name: "Determination", index: 7 },
  { name: "Freedom", index: 8 },
  { name: "Lament", index: 9 },
  { name: "Vengeance", index: 10 },
  { name: "Showdown", index: 11 },
  { name: "Promise", index: 12 },
  { name: "Recollect", index: 13 },
  { name: "Revenge", index: 14 },
  { name: "Annoyance", index: 15 },
  { name: "Hidden", index: 16 },
  { name: "Parting", index: 17 },
  { name: "Unbreakable", index: 18 },
  { name: "Reunion", index: 19 },
  { name: "Vocation", index: 20 },
  { name: "Blinded", index: 21 },
  { name: "Emergence", index: 22 },
  { name: "Chance", index: 23 },
  { name: "Desperate", index: 24 },
  { name: "Independence", index: 25 },
  { name: "Over the rainbow", index: 26 },
];

export default episodes;
