const names = [
  { name: "En noir et blanc, en couleur", index: "1" },
  { name: "Second rôle", index: "2" },
  { name: "En harmonie avec le printemps", index: "3" },
  { name: "Le début du Voyage", index: "4" },
  { name: "Couvert de nuages", index: "5" },
  { name: "Sur le chemin du retour", index: "6" },
  { name: "Le chuchotement des ombres", index: "7" },
  { name: "Résonne", index: "8" },
  { name: "Réverbération", index: "9" },
  { name: "Le paysage en ta compagnie", index: "10" },
  { name: "L'étincelle de la vie", index: "11" },
  { name: "Brille, petite étoile", index: "12" },
  { name: "Liebesleid", index: "13" },
  { name: "Traces de pas", index: "14" },
  { name: "Menteur", index: "15" },
  { name: "Ressemblances", index: "16" },
  { name: "Crépuscule", index: "17" },
  { name: "Cœurs superposés", index: "18" },
  { name: "Adieu, mon héros", index: "19" },
  { name: "Main dans la main", index: "20" },
  { name: "Neige", index: "21" },
  { name: "Vent de printemps", index: "22" },
];

export default names;
