const names = [
  { name: "La sphère", index: "1" },
  { name: "3/400", index: "2" },
  { name: "La bonne porte", index: "3" },
  { name: "Avril vert", index: "4" },
  { name: "Le dénouement du Jeu de la couronne", index: "5" },
  { name: "Attribution des positions", index: "6" },
  { name: "Repas et cache-cache", index: "7" },
  { name: "Le stratagème de Khun", index: "8" },
  { name: "Graine de démon", index: "9" },
  { name: "Au-delà de la tristesse", index: "10" },
  { name: "Pêche en eaux profondes - Première partie", index: "11" },
  { name: "Pêche en eaux profondes - Deuxième partie", index: "12" },
  { name: "La Tour de Dieu", index: "13" },
  { name: "Last chance", index: "14" },
  { name: "Le plus puissant des réguliers", index: "15" },
  { name: "La chambre digne de confiance", index: "16" },
  { name: "Nouilles et firmament", index: "17" },
  { name: "L'autre équipe", index: "18" },
  { name: "La fleur de Zigena", index: "19" },
  { name: "Mazino le magicien", index: "20" },
  { name: "Elle s'appelle Émilie", index: "21" },
  { name: "Le démon à une aile", index: "22" },
  { name: "La main d'Arlène", index: "23" },
  { name: "Un mur épais et lointain", index: "24" },
  { name: "Une nouvelle épreuve", index: "25" },
  { name: "L'Archimède", index: "26" },
  { name: "Rencontre avec le voyageur", index: "27" },
  { name: "La promesse faite ce jour-là", index: "28" },
];

export default names;
