const episodes = [
  { name: "La fin de l'aventure", index: "1" },
  { name: "Magie ou pas, peu importe", index: "2" },
  { name: "Le zoltraak", index: "3" },
  { name: "Là où reposent les âmes", index: "4" },
  { name: "Mirages", index: "5" },
  { name: "Le héros du village", index: "6" },
  { name: "Un conte de fées", index: "7" },
  { name: "Frieren la fossoyeuse", index: "8" },
  { name: "Aura la guillotine", index: "9" },
  { name: "Une mage redoutable", index: "10" },
  { name: "L'hiver des contrées du nord", index: "11" },
  { name: "Un authentique héros", index: "12" },
  { name: "La haine de son semblable", index: "13" },
  { name: "Le privilège de la jeunesse", index: "14" },
  { name: "L'odeur des ennuis", index: "15" },
  { name: "Compagnons de longévité", index: "16" },
  { name: "Faites bon voyage", index: "17" },
  { name: "L'examen de mage de première classe", index: "18" },
  { name: "Une stratégie empreinte de prudence", index: "19" },
  { name: "Meurtres nécessaires", index: "20" },
  { name: "Le monde de la magie", index: "21" },
  { name: "D'alliés à ennemis", index: "22" },
  { name: "La conquête du donjon", index: "23" },
  { name: "Des copies conformes", index: "24" },
  { name: "Le point faible", index: "25" },
  { name: "Les sommets de la magie", index: "26" },
  { name: "L'âge des hommes", index: "27" },
  { name: "J'aurai honte la prochaine fois", index: "28" },
];

export default episodes;
