const episodes = [
  { name: "Le mal est tapi au fond de nous", index: "1" },
  { name: "La porte de la Géhenne", index: "2" },
  { name: "Aîné et cadet", index: "3" },
  { name: "Le jardin d'Amahara", index: "4" },
  { name: "L'enfant du temple maudit", index: "5" },
  { name: "Le cuisinier fantôme", index: "6" },
  { name: "Entre amis", index: "7" },
  { name: "Il y avait un malade", index: "8" },
  { name: "Trauma", index: "9" },
  { name: "Cait Sith", index: "10" },
  { name: "Le démon des profondeurs", index: "11" },
  { name: "Démons en action", index: "12" },
  { name: "La preuve", index: "13" },
  { name: "Une joyeuse excursion", index: "14" },
  { name: "Sympathie", index: "15" },
  { name: "Un pari", index: "16" },
  { name: "Tentation", index: "17" },
  { name: "Cyclone", index: "18" },
  { name: "Un jour comme un autre", index: "19" },
  { name: "Le masque", index: "20" },
  { name: "Le jardin des secrets", index: "21" },
  { name: "Chasse aux démons", index: "22" },
  { name: "Vérité", index: "23" },
  { name: "Les bâtards de Satan", index: "24" },
  { name: "Ô temps ! Arrête-toi", index: "25" },
  { name: "Début des hostilités", index: "26" },
  { name: "Panier de crabes", index: "27" },
  { name: "Soupçons en chaîne", index: "28" },
  { name: "Sans foi ni loi", index: "29" },
  { name: "Le hasard des rencontres", index: "30" },
  { name: "Paroles mielleuses", index: "31" },
  { name: "Embrasement", index: "32" },
  { name: "De père en fils", index: "33" },
  { name: "Le Chêne et le roseau", index: "34" },
  { name: "Inébranlable", index: "35" },
  { name: "De mille feux", index: "36" },
  { name: "Sans préjugé", index: "37" },
  { name: "Un monde grouillant", index: "38" },
  { name: "L'antre du secret", index: "39" },
  { name: "Le Cross Festival", index: "40" },
  { name: "La taupe", index: "41" },
  { name: "Destin", index: "42" },
  { name: "Plus personne sur qui compter", index: "43" },
  { name: "Égarement", index: "44" },
  { name: "Détermination", index: "45" },
  { name: "À l'aide", index: "46" },
  { name: "Camarades", index: "47" },
  { name: "Pink Spider", index: "48" },
  { name: "Intentions cachées", index: "49" },
];

export default episodes;
