const names = [
  { name: "Ragnarok", index: "1" },
  { name: "Un adversaire à la hauteur", index: "2" },
  { name: "Coup de maître", index: "3" },
  { name: "Joie", index: "4" },
  { name: "Le fichier n° 00000000001", index: "5" },
  { name: "Émulation au sommet", index: "6" },
  { name: "Chassés du paradis", index: "7" },
  { name: "Que la grâce abonde", index: "8" },
  { name: "Le tyran des océans", index: "9" },
  { name: "Le plus grand des perdants", index: "10" },
  { name: "L'hirondelle plonge son regard dans l'abîme", index: "11" },
  { name: "Le Ragnarok continue", index: "12" },
  { name: "Le bien contre le mal", index: "13" },
  { name: "L'indomptable dieu de la guerre", index: "14" },
  { name: "Naissance d'un monstre", index: "15" },
  { name: "Le dernier supplice", index: "16" },
  { name: "Requiem", index: "17" },
  { name: "Motivations contradictoires", index: "18" },
  { name: "Les cent lianes de protection", index: "19" },
  { name: "Le sommet des 1 116", index: "20" },
  { name: "Résonance", index: "21" },
  { name: "Le bord", index: "22" },
  { name: "Le sixième combat", index: "23" },
  { name: "Zéro", index: "24" },
  { name: "La puberté la plus violente de l'histoire", index: "25" },
  { name: "Légende de l'au-delà", index: "26" },
  { name: "La voie de la lumière", index: "27" },
];

export default names;
