const episodes = [
  { name: "Un Désert sans fin", index: 1 },
  { name: "Le Palais divin", index: 2 },
  { name: "Le Chef qui ne sourit jamais", index: 3 },
  { name: "Marie de l’Étoile Polaire", index: 4 },
  { name: "La reine de glace et l'ouragan printanier", index: 5 },
  { name: "Le prédateur carnivore", index: 6 },
  { name: "Donburi paisible et donburi enflammé", index: 7 },
  { name: "Une Symphonie de créativité", index: 8 },
  { name: "La Splendeur cachée des montagnes", index: 9 },
  { name: "La Recette parfaite", index: 10 },
  { name: "Le Magicien venu de l'Est", index: 11 },
  { name: "Mémoires d’un plat", index: 12 },
  { name: "Les Œufs de l'aube", index: 13 },
  { name: "Métamorphose", index: 14 },
  { name: "L'Homme qu'on surnommait 'le démon'", index: 15 },
  { name: "Le Chef qui a parcouru le monde", index: 16 },
  { name: "Fantastique karaage", index: 17 },
  { name: "Le karaage de l'adolescence", index: 18 },
  { name: "Les Élus", index: 19 },
  { name: "L'Ascension du dragon agenouillé", index: 20 },
  { name: "L'Inconnu connu", index: 21 },
  { name: "Tout sauf banal", index: 22 },
  { name: "La Fleur bourgeonnante", index: 23 },
  { name: "Le Festin des guerriers", index: 24 },
  { name: "Les fondamentaux du bento", index: 25 },
  { name: "Côté clair et côté obscur", index: 26 },
  { name: "La génération diamant", index: 27 },
  { name: "Le traqueur", index: 28 },
  { name: "Le secret de la première bouchée", index: 29 },
  { name: "Demain sera un autre jour", index: 30 },
  { name: "Les bêtes s'entre-dévorent", index: 31 },
  { name: "Un combat autour d'une saison", index: 32 },
  { name: "Le sabre qui annonce l'automne", index: 33 },
  { name: "Une nouvelle perle", index: 34 },
  { name: "Les stagiaires", index: 35 },
  { name: "Le retour du magicien", index: 36 },
  { name: "Magnificence", index: 37 },
  { name: "Défier les dix maîtres", index: 38 },
  { name: "Anesthésiant et relevé", index: 39 },
  { name: "Le festival Gekkyô", index: 40 },
  { name: "La meute des lionceaux", index: 41 },
  { name: "Une table dans les ténèbres", index: 42 },
  { name: "La souveraine captive", index: 43 },
  { name: "L'effondrement de l'académie", index: 44 },
  { name: "L'alchimiste", index: 45 },
  { name: "La chasse aux survivants", index: 46 },
  { name: "Un saumon frétillant", index: 47 },
  { name: "Le chevalier blanc de la gastronomie", index: 48 },
  { name: "Celui qui vise les sommets", index: 49 },
  { name: "Les examens de passage", index: 50 },
  { name: "Train Tootsuki au départ", index: 51 },
  { name: "Jeanne D'Arc se dresse", index: 52 },
  { name: "La revanche", index: 53 },
  { name: "Sur la corde raide", index: 54 },
  { name: "Cuisiner pour autrui", index: 55 },
  { name: "Déclaration de guerre", index: 56 },
  { name: "L'apprentissage d'Erina", index: 57 },
  { name: "L'explorateur", index: 58 },
  { name: "Vers la bataille décisive", index: 59 },
  { name: "Pour l'Étoile Polaire", index: 60 },
  { name: "Ce qui pousse les plus forts", index: 61 },
  { name: "Ce que l'on veut protéger", index: 62 },
  { name: "Flash stroboscopique", index: 63 },
  { name: "Le régiment de l'espoir", index: 64 },
  { name: "Viser la victoire!", index: 65 },
  { name: "Vous êtes finis", index: 66 },
  { name: "Une lame unique", index: 67 },
  { name: "Deux reines", index: 68 },
  { name: "Ton profil", index: 69 },
  { name: "1er et 2e sièges", index: 70 },
  { name: "Comment préparer un plat signature", index: 71 },
  { name: "Chant d'espoir", index: 72 },
  { name: "Le nouveau Conseil des Dix", index: 73 },
  { name: "Un parfum d'imprévu", index: 74 },
  { name: "Les escarmouches d'avant-poste du Blue", index: 75 },
  { name: "Un chef dans le noir", index: 76 },
  { name: "Le dernier repas", index: 77 },
  { name: "La bataille de la supérette", index: 78 },
  { name: "Noël en plein été", index: 79 },
  { name: "Couteaux croisés", index: 80 },
  { name: "Une demi-lune ébréchée", index: 81 },
  { name: "Le désespoir du palais divin", index: 82 },
  { name: "Surpasser le père", index: 83 },
  { name: "Le goût de l'échec", index: 84 },
  { name: "Des Joyaux Prodigieux", index: 85 },
  { name: "Food Wars", index: 86 },
];

export default episodes;
