export default [
  { index: '1', name: 'Fairy Tail' },
  { index: '2', name: 'Le Dragon de feu, le Singe et le Taureau' },
  { index: '3', name: 'Infiltrons le manoir d’Everlue !' },
  { index: '4', name: 'Mon cher Kaby' },
  { index: '5', name: 'Le Mage à l’armure' },
  { index: '6', name: 'Fairy Tail, au cœur de la tempête' },
  { index: '7', name: 'Les Flammes et le Vent' },
  { index: '8', name: 'La Meilleure des équipes !' },
  { index: '9', name: 'Natsu mange un village' },
  { index: '10', name: 'Natsu contre Erza' },
  { index: '11', name: 'L’Île maudite' },
  { index: '12', name: 'Les Gouttes de Lune' },
  { index: '13', name: 'Natsu contre les ondes de Yûka' },
  { index: '14', name: 'Le gagnant fait ce qui lui plaît' },
  { index: '15', name: 'La Magie éternelle' },
  { index: '16', name: 'L’Île de Galuna – La Bataille finale' },
  { index: '17', name: 'Burst' },
  { index: '18', name: 'La Mission ! Vers le ciel !' },
  { index: '19', name: 'Changeling' },
  { index: '20', name: 'Natsu et l’Œuf du dragon' },
  { index: '21', name: 'Phantom Lord' },
  { index: '22', name: 'Lucy Heartfilia' },
  { index: '23', name: '15 minutes' },
  { index: '24', name: 'Pour ne pas voir tes larmes' },
  { index: '25', name: 'La fleur qui s’épanouit sous la pluie' },
  { index: '26', name: 'Les Ailes de feu' },
  { index: '27', name: 'Les Deux Chasseurs de dragons' },
  { index: '28', name: 'La Loi des fées' },
  { index: '29', name: 'C’est mon choix' },
  { index: '30', name: 'Next Generation' },
  { index: '31', name: 'L’Étoile tombée des cieux' },
  { index: '32', name: 'Le Roi des constellations' },
  { index: '33', name: 'La Tour du Paradis' },
  { index: '34', name: 'Jellal' },
  { index: '35', name: 'L’appel des ténèbres' },
  { index: '36', name: 'Le jeu du Paradis' },
  { index: '37', name: 'L’armure du cœur' },
  { index: '38', name: 'Destinée' },
  { index: '39', name: 'Une prière pour la lumière sainte' },
  { index: '40', name: 'La Chute de la reine des fées' },
  { index: '41', name: 'Home' },
  { index: '42', name: 'La Bataille de Fairy Tail' },
  { index: '43', name: 'Attaque ton ami pour le sauver' },
  { index: '44', name: 'Le Palais de la foudre' },
  { index: '45', name: 'L’avènement de Satan' },
  { index: '46', name: 'Catastrophe à la cathédrale de Kardia' },
  { index: '47', name: 'Triple Dragon' },
  { index: '48', name: 'Fantasia' },
  { index: '49', name: 'Une rencontre marquée par le destin' },
  { index: '50', name: 'Mission spéciale. Prends garde à l’être aimé' },
  { index: '51', name: 'LOVE & LUCKY' },
  { index: '52', name: 'Équipe de la coalition, parée !' },
  { index: '53', name: 'Oracion Seis entre en scène !' },
  { index: '54', name: 'La Prêtresse Céleste' },
  { index: '55', name: 'La Fillette et le Fantôme' },
  { index: '56', name: 'Le Grand Prix de la mort' },
  { index: '57', name: 'Les Ténèbres' },
  { index: '58', name: 'Duel d’esprits' },
  { index: '59', name: 'L’ancien Jellal' },
  { index: '60', name: 'La marche de la destruction' },
  { index: '61', name: 'Un combat aérien' },
  { index: '62', name: 'Jura, le mage sacré' },
  { index: '63', name: 'Tes paroles plus que tout' },
  { index: '64', name: 'Zéro' },
  { index: '65', name: 'De la part de Pégase' },
  { index: '66', name: 'La force des sentiments' },
  { index: '67', name: 'Je suis avec toi' },
  { index: '68', name: 'Une guilde fondée pour une personne' },
  { index: '69', name: 'L’Appel du dragon' },
  { index: '70', name: 'Natsu contre Grey !' },
  { index: '71', name: 'L’amitié est plus forte que la mort' },
  { index: '72', name: 'Les mages de Fairy Tail' },
  { index: '73', name: 'Les cerisiers arc-en-ciel' },
  { index: '74', name: 'Première grande mission pour Wendy' },
  { index: '75', name: 'Les vingt-quatre heures à pied de Fairy Tail' },
  { index: '76', name: 'Gildarts' },
  { index: '77', name: 'Earthland' },
  { index: '78', name: 'Edolas' },
  { index: '79', name: 'La chasse aux fées' },
  { index: '80', name: 'Les clés de l’espérance' },
  { index: '81', name: 'Fireball' },
  { index: '82', name: 'Soyez les bienvenus' },
  { index: '83', name: 'Extalia' },
  { index: '84', name: 'Envole-toi vers tes amis !' },
  { index: '85', name: 'Code DTE' },
  { index: '86', name: 'Erza contre Erza' },
  { index: '87', name: 'Ce sont des vies !!!!' },
  { index: '88', name: 'Pour la fierté du fleuve étoilé' },
  { index: '89', name: 'Le Harpon du dragon de l’apocalypse' },
  { index: '90', name: 'Le Garçon de cette époque' },
  { index: '91', name: 'Les Sens du Dragon' },
  { index: '92', name: 'Pour les vivants' },
  { index: '93', name: 'Je suis là, devant toi !' },
  { index: '94', name: 'Bye bye Edolas' },
  { index: '95', name: 'Lisanna' },
  { index: '96', name: 'Celui qui anéantit la vie' },
  { index: '97', name: 'Les meilleurs partenaires' },
  { index: '98', name: 'Qui a de la chance ?' },
  { index: '99', name: 'Natsu contre Gildarts' },
  { index: '100', name: 'Mest' },
  { index: '101', name: 'Le mage noir' },
  { index: '102', name: 'L’âme d’acier' },
  { index: '103', name: 'Makarof à l’assaut' },
  { index: '104', name: 'Magie perdue' },
  { index: '105', name: 'Dragon de feu contre Dieu du feu' },
  { index: '106', name: 'Le monde de la grande magie' },
  { index: '107', name: 'L’arc de la matérialisation' },
  { index: '108', name: 'La porte des humains' },
  { index: '109', name: 'Lucy Fire' },
  { index: '110', name: 'L’impasse du désespoir' },
  { index: '111', name: 'Les larmes d’amour et de vie' },
  { index: '112', name: 'Ce que je n’ai pas pu lui dire' },
  { index: '113', name: 'L’arbre de Tenrô' },
  { index: '114', name: 'Erza contre Azuma' },
  { index: '115', name: 'Fureur glaçante' },
  { index: '116', name: 'Le pouvoir de la vie' },
  { index: '117', name: 'Le grondement du tonnerre' },
  { index: '118', name: 'L’homme sans symbole' },
  { index: '119', name: 'Les plus profondes abysses' },
  { index: '120', name: 'Le jour se lève sur l’île de Tenrô' },
  { index: '121', name: 'Le droit d’aimer' },
  { index: '122', name: 'Donnons-nous la main' },
  { index: '123', name: 'Fairy Tail, année X-791' },
  { index: '124', name: 'Sept ans d’absence' },
  { index: '125', name: 'Le bal de la magie' },
  { index: '126', name: 'Ketsupuri, le gang des pires crapules' },
  { index: '127', name: 'La frayeur de Lucy l’invisible' },
  { index: '128', name: 'Le souvenir d’un père' },
  { index: '129', name: 'Natsu contre Luxus ! Le duel des enragés !' },
  { index: '130', name: 'Lucy est traquée' },
  { index: '131', name: 'La fureur de la légion' },
  { index: '132', name: 'La clé du ciel étoilé' },
  { index: '133', name: 'Compagnons de voyage' },
  { index: '134', name: 'La rhapsodie du labyrinthe' },
  { index: '135', name: 'Sur les traces du mythe' },
  { index: '136', name: 'Le retour du diable en personne' },
  { index: '137', name: 'Au-delà des prévisions' },
  { index: '138', name: 'Vers la guerre sainte' },
  { index: '139', name: 'Lancement du compte à rebours !' },
  { index: '140', name: 'Voici Oracion Seis, nouvelle version !' },
  { index: '141', name: 'À la poursuite de l’horloge infinie !' },
  { index: '142', name: 'Désordres de bataille' },
  { index: '143', name: 'Anti-Link' },
  { index: '144', name: 'Le désespoir libéré' },
  { index: '145', name: 'Le cauchemar réel' },
  { index: '146', name: 'La spirale du temps !' },
  { index: '147', name: 'En route vers le château infini !' },
  { index: '148', name: 'Les larmes d’un ange' },
  { index: '149', name: 'J’entends la voix de mes amis' },
  { index: '150', name: 'Lucy et Michelle' },
  { index: '151', name: 'Dents de Sabre ! Sabertooth !' },
  { index: '152', name: 'Nous, on vise le top !' },
  { index: '153', name: 'La chanson des étoiles !' },
  { index: '154', name: 'Juste le temps de se croiser' },
  { index: '155', name: 'Crocus, la cité fleurie !' },
  { index: '156', name: 'Sky Labyrinth' },
  { index: '157', name: 'Nouvelle guilde' },
  { index: '158', name: 'Pluie d’étoiles' },
  { index: '159', name: 'Lucy contre Flare' },
  { index: '160', name: 'Mauvais présage' },
  { index: '161', name: 'Les chariots' },
  { index: '162', name: 'Elfman contre Bacchus' },
  { index: '163', name: 'Mirajane contre Jenny' },
  { index: '164', name: 'Kagura contre Yukino' },
  { index: '165', name: 'La rancœur enveloppée dans les voiles de la nuit' },
  { index: '166', name: 'Pandémonium !' },
  { index: '167', name: '100 contre 1 !' },
  { index: '168', name: 'Luxus contre Alexei' },
  { index: '169', name: 'Wendy contre Cherrya' },
  { index: '170', name: 'Les petits poings' },
  { index: '171', name: 'Bataille navale !' },
  { index: '172', name: 'Le parfum que je te dédie' },
  { index: '173', name: 'La bataille des chasseurs de dragons' },
  { index: '174', name: 'Quatre dragons !' },
  { index: '175', name: 'Natsu contre les dragons jumeaux' },
  { index: '176', name: 'Le roi des dragons' },
  { index: '177', name: 'Le projet Éclipse' },
  { index: '178', name: 'La Stratège des fées' },
  { index: '179', name: 'Grey vs. Rufus' },
  { index: '180', name: 'L’ordre des Loups affamés' },
  { index: '181', name: 'Fairy Tail vs. les bourreaux' },
  { index: '182', name: 'Une mer de lave' },
  { index: '183', name: 'Le pays où nous sommes' },
  { index: '184', name: 'Le Pays d’encore un lendemain' },
  { index: '185', name: 'Erza vs. Kagura' },
  { index: '186', name: 'Un futur lancé vers le désespoir' },
  { index: '187', name: 'La grenouille' },
  { index: '188', name: 'Furieux éclairs !' },
  { index: '189', name: 'Gloria' },
  { index: '190', name: 'Celle qui fermera la porte' },
  { index: '191', name: 'Natsu vs. Rogue' },
  { index: '192', name: 'Pour deux' },
  { index: '193', name: 'Sept dragons' },
  { index: '194', name: 'La magie de Jilkonis' },
  {
    index: '195',
    name: 'Humains vs humains, dragons vs dragons, humains vs dragons',
  },
  { index: '196', name: 'Crime et sacrifice' },
  { index: '197', name: 'Temps de vie' },
  { index: '198', name: 'Prairie d’or' },
  { index: '199', name: 'Le grand bal' },
  { index: '200', name: 'Gouttes de temps' },
  { index: '201', name: 'Cadeau' },
  { index: '202', name: 'Bienvenue chez toi Frosh !' },
  { index: '203', name: 'Moulin Rouge' },
  { index: '204', name: 'Tout pour vous satisfaire !' },
  { index: '205', name: 'Le signal de la révolte' },
  { index: '206', name: 'Panique à la bibliothèque' },
  { index: '207', name: 'Jade se lève !' },
  { index: '208', name: 'Astral Spiritus' },
  { index: '209', name: 'Wendy vs Aquarius. Jouons au parc d’attractions !' },
  { index: '210', name: 'Cartes de la guilde VS Cartes des esprits' },
  { index: '211', name: 'Grey VS Cancer Dance Battle !' },
  { index: '212', name: 'Jubia vs Aries, combat mortel dans le désert !' },
  { index: '213', name: 'Erza vs Sagittarius, la joute finale' },
  { index: '214', name: 'Natsu vs Leo' },
  { index: '215', name: 'Ophiuchus le Serpentaire' },
  { index: '216', name: 'Des étoiles filantes plein le ciel' },
  { index: '217', name: 'La bête céleste' },
  { index: '218', name: 'Croire' },
  { index: '219', name: 'Ce qui tisse la sincérité' },
  { index: '220', name: '413 jours' },
  { index: '221', name: 'Le Dédale Blanc' },
  { index: '222', name: 'Transformation !' },
  { index: '223', name: 'Kemokemo est arrivé !' },
  { index: '224', name: 'L’endroit d’où tu viens' },
  { index: '225', name: 'L’homme de la foudre' },
  { index: '226', name: 'Fairy Tail of the Dead Bôôôôôôôô' },
  { index: '227', name: 'Le matin d’une nouvelle aventure' },
  { index: '228', name: 'Mages vs. chasseurs' },
  { index: '229', name: 'La loi de la régression' },
  { index: '230', name: 'Le retour du démon' },
  { index: '231', name: 'Grey vs Doriate' },
  { index: '232', name: 'La voix de la flamme' },
  { index: '233', name: 'La chanson des fées' },
  { index: '234', name: 'Les neuf portes démoniaques' },
  { index: '235', name: 'Fée vs Enfer' },
  { index: '236', name: 'L’héritage blanc' },
  { index: '237', name: 'Natsu vs Jackal' },
  { index: '238', name: 'Immoralité et criminels' },
  { index: '239', name: 'Jellal vs Oracion Seis' },
  { index: '240', name: 'Là où les prières arrivent' },
  { index: '241', name: 'Réincarnation en démon' },
  { index: '242', name: 'Tuer ou laisser vivre' },
  { index: '243', name: 'Wendy vs Ezer' },
  { index: '244', name: 'Amies pour toujours' },
  { index: '245', name: 'Hell’s Core' },
  { index: '246', name: 'Le roi des Enfers' },
  { index: '247', name: 'Alegria' },
  { index: '248', name: 'L’attaque stellaire' },
  { index: '249', name: 'Roi des esprits vs Roi des enfers' },
  { index: '250', name: 'Erza vs Minerva' },
  { index: '251', name: 'L’histoire d’un gamin' },
  { index: '252', name: 'Grey vs Silver' },
  { index: '253', name: 'La transmission de Silver' },
  { index: '254', name: 'Air' },
  { index: '255', name: 'Acier' },
  { index: '256', name: 'Le dernier duel' },
  { index: '257', name: 'Les ailes du désespoir' },
  { index: '258', name: 'Poing d’acier du dragon de feu' },
  { index: '259', name: '00h00' },
  { index: '260', name: 'La fille dans le cristal' },
  { index: '261', name: 'Le démon absolu' },
  { index: '262', name: 'Memento Mori' },
  { index: '263', name: 'Vol vers Ishgar' },
  { index: '264', name: 'Gouttes de feu' },
  { index: '265', name: 'La force de vivre' },
  { index: '266', name: 'Des fées dans le cœur' },
  { index: '267', name: 'L’aventure commence' },
  { index: '268', name: 'Chasse au trésor' },
  { index: '269', name: 'Danse avec la lame' },
  { index: '270', name: 'Un lac au clair de lune' },
  { index: '271', name: 'Blue Skull' },
  { index: '272', name: 'Le passeur de magie' },
  { index: '273', name: 'Trésor' },
  { index: '274', name: 'Law' },
  { index: '275', name: 'L’aventure éternelle' },
  { index: '276', name: 'Challenger' },
  { index: '277', name: 'Message de Feu' },
  { index: '278', name: 'Le Thanksgiving de Lamia Scale' },
  { index: '279', name: 'Parce qu’il l’aime' },
  { index: '280', name: 'Avatar' },
  { index: '281', name: 'Âpre combat en sous-sol' },
  { index: '282', name: 'Le plan de Purification' },
  { index: '283', name: 'Ikusatsunagi' },
  { index: '284', name: 'Souvenirs' },
  { index: '285', name: 'Le Septième Maître de la guilde' },
  { index: '286', name: 'Les lois de l’espace' },
  { index: '287', name: 'L’Empereur Spriggan' },
  { index: '288', name: 'La terre abandonnée par les Dieux' },
  { index: '289', name: 'Mavis et Zeleph' },
  { index: '290', name: 'Fairy Heart' },
  { index: '291', name: 'La défense de Magnolia' },
  { index: '292', name: 'Étoile du matin' },
  { index: '293', name: 'Pour qui est ce parfum ?' },
  { index: '294', name: 'Natsu vs Zeleph' },
  { index: '295', name: '400 ans d’attente' },
  { index: '296', name: 'Ce que je veux faire' },
  { index: '297', name: 'Jusqu’à la fin de la bataille' },
  { index: '298', name: 'Dans l’immobilité du temps' },
  { index: '299', name: 'Natsu de retour !' },
  { index: '300', name: 'Historias des morts' },
  { index: '301', name: 'Détermination' },
  { index: '302', name: 'Le troisième sceau' },
  { index: '303', name: 'Tous les deux, à jamais !' },
  { index: '304', name: 'Fairy Tail Zero' },
  { index: '305', name: 'Dragnir le blanc' },
  { index: '306', name: 'Le mage de l’hiver' },
  { index: '307', name: 'Grey et Jubia' },
  { index: '308', name: 'Le plus puissant démon des livres de Zeleph' },
  { index: '309', name: 'Les liens brisés' },
  { index: '310', name: 'Plaisir et douleur' },
  { index: '311', name: 'L’esprit de Natsu' },
  { index: '312', name: 'Sting, le Dragon blanc de l’ombre' },
  { index: '313', name: 'Graine de Dragon' },
  { index: '314', name: 'Enchantement suprême' },
  { index: '315', name: 'Dragon ou Démon' },
  { index: '316', name: 'L’atout de Grey' },
  { index: '317', name: 'Avenir sombre' },
  { index: '318', name: 'Je m’appelle…' },
  { index: '319', name: 'Sentiments' },
  { index: '320', name: 'Néo Eclipse' },
  { index: '321', name: 'Je ne vois plus d’amour' },
  { index: '322', name: 'La porte des promesses' },
  { index: '323', name: 'Les flammes du dragon déchaîné' },
  { index: '324', name: 'Lorsque les flammes s’éteignent' },
  { index: '325', name: 'Le monde s’écroule' },
  { index: '326', name: 'Le sort de l’espoir' },
  { index: '327', name: 'Liés par le cœur' },
  { index: '328', name: 'Des compagnons Irremplaçables' },
];
