const names = [
  { name: "Prologue", index: "1" },
  { name: "Changement de place", index: "2" },
  { name: "Après l'école", index: "3" },
  { name: "Rumeurs", index: "4" },
  { name: "Détermination", index: "5" },
  { name: "Amies", index: "6" },
  { name: "Samedi soir", index: "7" },
  { name: "Entraînement solitaire", index: "8" },
  { name: "Une nouvelle amie", index: "9" },
  { name: "Coopération", index: "10" },
  { name: "Spécial ?", index: "11" },
  { name: "Sentiments amoureux", index: "12" },
  { name: "Amour", index: "13" },
  { name: "Kurumi", index: "14" },
  { name: "Rivales", index: "15" },
  { name: "Discussion nocturne", index: "16" },
  { name: "Jour de repos", index: "17" },
  { name: "L'amour de Chizuru", index: "18" },
  { name: "Rêve", index: "19" },
  { name: "Cadeau", index: "20" },
  { name: "Première neige", index: "21" },
  { name: "Noël", index: "22" },
  { name: "Nous deux", index: "23" },
  { name: "Anniversaire", index: "24" },
  { name: "Une nouvelle année", index: "25" },
  { name: "Amour non partagé", index: "26" },
  { name: "La Saint-Valentin", index: "27" },
  { name: "Deuxième année", index: "28" },
  { name: "Oublie", index: "29" },
  { name: "Tu ne comprends pas", index: "30" },
  { name: "Celui que j'aime", index: "31" },
  { name: "Affection et contrariété", index: "32" },
  { name: "Laisse tomber", index: "33" },
  { name: "Pour toi", index: "34" },
  { name: "Confession", index: "35" },
  { name: "À partir de maintenant", index: "36" },
  { name: "Après le festival", index: "37" },
  { name: "La personne qui compte pour moi", index: "38" },
  { name: "Il n'y a aucune raison que je te déteste", index: "39" },
  { name: "Voyage scolaire", index: "40" },
  { name: "Petits amis", index: "41" },
  { name: "La fête de Noël", index: "42" },
  { name: "Un moment de bonheur", index: "43" },
];

export default names;
