const names = [
  { name: "Dans le ciel de Sakura", index: "1" },
  { name: "La jeune fille et le chat bleu", index: "2" },
  { name: "Les aventuriers", index: "3" },
  { name: "Un homme nommé Wise", index: "4" },
  { name: "Choc en vue ! La famille de Sibylle", index: "5" },
  { name: "Le Skull Fairy", index: "6" },
  { name: "Le cuirassé Grand Démon", index: "7" },
  { name: "L'autoroute où siffle le vent", index: "8" },
  { name: "Planète Guilst", index: "9" },
  { name: "Opération évasion toutes nues", index: "10" },
  { name: "Sister Ivly", index: "11" },
  { name: "De nouveaux compagnons", index: "12" },
  { name: "Super planète virtuelle", index: "13" },
  { name: "La jeune fille sur la colline", index: "14" },
  { name: "Shiki, le Kaiju", index: "15" },
  { name: "Feu d'artifice", index: "16" },
  { name: "Le palais de la connaissance", index: "17" },
  { name: "Les mots sont une source de force", index: "18" },
  { name: "Depuis la planète de l'infini", index: "19" },
  { name: "Stones", index: "20" },
  { name: "Reset", index: "21" },
  { name: "La mère des machines", index: "22" },
  { name: "Jusqu'au jour où ça deviendra une force", index: "23" },
  { name: "L'héritier", index: "24" },
  { name: "Ceux qu'on aime", index: "25" },
  { name: "Belial Gore", index: "26" },
  { name: "Element 4", index: "27" },
  { name: "Le vent qui souffle sur Cosmos Sakura", index: "28" },
  { name: "N°29", index: "29" },
  { name: "Médiation", index: "30" },
  { name: "Notre Futur", index: "31" },
  { name: "4 VS 4", index: "32" },
  { name: "Edenzu no Tsurugi", index: "33" },
  { name: "Shiki VS Drakkhen", index: "34" },
  { name: "L'avènement du Grand Démon", index: "35" },
  { name: "EDENS ONE", index: "36" },
  { name: "Choc frontal dans le cosmos", index: "37" },
  { name: "Celle qu'on appelait la pirate", index: "38" },
  { name: "Nadia, amour de ma vie", index: "39" },
  { name: "La machine qui tombe amoureuse", index: "40" },
  { name: "Devenir un chien", index: "41" },
  { name: "La bataille de Foresta", index: "42" },
  { name: "Stardrain", index: "43" },
  { name: "Ma chère breloque", index: "44" },
  { name: "Kiss & Die", index: "45" },
  { name: "Système de fin", index: "46" },
  { name: "Oceans 6", index: "47" },
  { name: "Judgement day", index: "48" },
  { name: "Oasis dans le désert", index: "49" },
  { name: "La grande guerre d'Aoi : ouverture", index: "50" },
];

export default names;
