const names = [
  { name: "Asteroid Blues", index: "1" },
  { name: "Stray Dog Strut", index: "2" },
  { name: "Honky Tonk Women", index: "3" },
  { name: "Gateway Shuffle", index: "4" },
  { name: "Ballad of Fallen Angels", index: "5" },
  { name: "Sympathy For The Devil", index: "6" },
  { name: "Heavy Metal Queen", index: "7" },
  { name: "Waltz For Venus", index: "8" },
  { name: "Jamming With Edward", index: "9" },
  { name: "Ganymede Elegy", index: "10" },
  { name: "Toys in the Attic", index: "11" },
  { name: "Jupiter Jazz (Part 1)", index: "12" },
  { name: "Jupiter Jazz (Part 2)", index: "13" },
  { name: "Bohemian Rhapsody", index: "14" },
  { name: "My Funny Valentine", index: "15" },
  { name: "Black Dog Serenade", index: "16" },
  { name: "Mushroom Samba", index: "17" },
  { name: "Speak Like a Child", index: "18" },
  { name: "Wild Horses", index: "19" },
  { name: "Pierrot le Fou", index: "20" },
  { name: "Boogie Woogie Feng Shui", index: "21" },
  { name: "Cowboy Funk", index: "22" },
  { name: "Brain Scratch", index: "23" },
  { name: "Hard Luck Woman", index: "24" },
  { name: "The Real Folk Blues (Part 1)", index: "25" },
  { name: "The Real Folk Blues (Part 2)", index: "26" },
];

export default names;
