const episodes = [
  { name: "Le garçon sans nom", index: "1" },
  { name: "Une rencontre fatale", index: "2" },
  { name: "Oh mon ami !", index: "3" },
  { name: "Le Roi et l'épée", index: "4" },
  { name: "Un cœur indestructible", index: "5" },
  { name: "Le chemin pour devenir un grand général", index: "6" },
  { name: "Le terrifiant peuple des montagnes", index: "7" },
  { name: "Le rêve de chacun", index: "8" },
  { name: "Maintenant, vers Kanyou !", index: "9" },
  { name: "L'invasion de la capitale royale", index: "10" },
  { name: "Le combat féroce commence", index: "11" },
  { name: "L'épée ultime", index: "12" },
  { name: "Le rugissement de Rankai", index: "13" },
  { name: "Le pouvoir de l'épée", index: "14" },
  { name: "Les qualités d'un Roi", index: "15" },
  { name: "Ryo Fui", index: "16" },
  { name: "La première campagne", index: "17" },
  { name: "La menace des chars", index: "18" },
  { name: "Une bataille ardente", index: "19" },
  { name: "Ouki fait irruption", index: "20" },
  { name: "L'aptitude d'un général", index: "21" },
  { name: "Général intelligent contre général courageux", index: "22" },
  { name: "Histoire nocturne", index: "23" },
  { name: "Une nouvelle épreuve", index: "24" },
  { name: "Nomination", index: "25" },
  { name: "Houken, le Bushin", index: "26" },
  { name: "La naissance de l'unité Hi Shin", index: "27" },
  { name: "La flèche d'Ouki", index: "28" },
  { name: "Changement soudain du cours de la bataille", index: "29" },
  { name: "Le fléau", index: "30" },
  { name: "L'union fait la force", index: "31" },
  { name: "L'unité Hi Shin prend la fuite", index: "32" },
  { name: "Ouki prend les armes", index: "33" },
  { name: "Les protagonistes centraux", index: "34" },
  { name: "Confrontation des grands généraux", index: "35" },
  { name: "Ouki et Kyou", index: "36" },
  { name: "Je suis aux portes de la mort", index: "37" },
  { name: "Succession", index: "38" },
  { name: "Une nouvelle ère", index: "39" },
  { name: "Une bataille silencieuse", index: "40" },
  { name: "Un banquet tumultueux", index: "41" },
  { name: "Le Roi et la fourmi", index: "42" },
  { name: "La troisième force", index: "43" },
  { name: "Un sublime poison", index: "44" },
  { name: "Le Prince maudit", index: "45" },
  { name: "Sei et Shika", index: "46" },
  { name: "Salvation", index: "47" },
  { name: "Un amour brisé", index: "48" },
  { name: "Rassemblement", index: "49" },
  { name: "Le siège de Kourou", index: "50" },
  { name: "Ma façon de me battre", index: "51" },
  { name: "Renpa", index: "52" },
  { name: "Une aura de général", index: "53" },
  { name: "Le général de minuit", index: "54" },
  { name: "Veille de bataille", index: "55" },
  { name: "Premier choc", index: "56" },
  { name: "La ruse de Genpou", index: "57" },
  { name: "La contre-attaque de l'unité Hi Shin", index: "58" },
  { name: "Bandit versus stratège", index: "59" },
  { name: "La proposition de Mouten", index: "60" },
  { name: "Les trois unités unies", index: "61" },
  { name: "Un mur à franchir", index: "62" },
  { name: "Ruse sur ruse", index: "63" },
  { name: "L'étoffe d'un général", index: "64" },
  { name: "La fin a sonné", index: "65" },
  { name: "La dernière stratégie", index: "66" },
  { name: "Une seconde", index: "67" },
  { name: "Mes précieux camarades", index: "68" },
  { name: "Mougou ne fuira pas", index: "69" },
  { name: "Un âge éternel", index: "70" },
  { name: "Victoire et suite", index: "71" },
  { name: "L'arrivée du stratège", index: "72" },
  { name: "Le test de Ten", index: "73" },
  { name: "Le combat de l'esprit", index: "74" },
  { name: "La tempête approche", index: "75" },
  { name: "La scène des intrigants", index: "76" },
  { name: "Une nouvelle légende", index: "77" },
  { name: "Le surgissement de la coalition", index: "78" },
  { name: "Rencontre dans une salle", index: "79" },
  { name: "La bataille de la porte de Kankoku", index: "80" },
  { name: "Les deux champs de bataille", index: "81" },
  { name: "Le jeune général se distingue", index: "82" },
  { name: "Fierté mutuelle", index: "83" },
  { name: "La lande parsemée de fosses", index: "84" },
  { name: "Karin, une femme de caractère", index: "85" },
  { name: "La harangue de Moubu", index: "86" },
  { name: "Le terrible dilemme", index: "87" },
  { name: "La dignité d'un général", index: "88" },
  { name: "L'assaut de l'armée de Karin", index: "89" },
  { name: "Le plus fort", index: "90" },
  { name: "L'homme le plus fort", index: "91" },
  { name: "Derrière la porte de Kankoku", index: "92" },
  { name: "La destination de Riboku", index: "93" },
  { name: "L'incarnation du génie instinctif", index: "94" },
  { name: "La décision d'Ei Sei", index: "95" },
  { name: "Le discours d'Ei Sei", index: "96" },
  { name: "La première nuit", index: "97" },
  { name: "Le secret dévoilé", index: "98" },
  { name: "À bout", index: "99" },
  { name: "Des renforts extraordinaires", index: "100" },
  { name: "Profonde gratitude", index: "101" },
  { name: "Une dance de prêtresse différente", index: "102" },
  { name: "Une autre voie", index: "103" },
  { name: "Les Sept États après la guerre", index: "104" },
  { name: "Une ombre inquiétante", index: "105" },
  { name: "Départ de la force punitive", index: "106" },
  { name: "Le Siège de Tonryû", index: "107" },
  { name: "L’épée et le bouclier", index: "108" },
  { name: "Un nouveau front stratégique", index: "109" },
  { name: "L'appel", index: "110" },
  { name: "Ce que représente Ten", index: "111" },
  { name: "Le nom du comte Shi", index: "112" },
  { name: "L'attention des Sept États", index: "113" },
  { name: "Un quotidien fait d'entraînement", index: "114" },
  { name: "La génération des grands hommes", index: "115" },
  { name: "Intrigues à Kanyou", index: "116" },
  { name: "Un nouveau pays", index: "117" },
  { name: "L'Homme de rien", index: "118" },
  { name: "La cérémonie de la majorité", index: "119" },
  { name: "Aucun des trois camps ne cède rien", index: "120" },
  { name: "La bataille sur la rivière", index: "121" },
  { name: "Couper les ponts", index: "122" },
  { name: "Un pays de rêve", index: "123" },
  { name: "L'unique chance de victoire", index: "124" },
  { name: "Une fuite périlleuse", index: "125" },
  { name: "La charge décisive", index: "126" },
  { name: "La conclusion de la guerre civile", index: "127" },
  { name: "L'heure de l'envol", index: "128" },
  { name: "Les Six Grands Généraux", index: "129" },
  { name: "Les monstres partent au combat", index: "130" },
  { name: "L'odeur du champ de bataille", index: "131" },
  { name: "Kokuyou la nuit", index: "132" },
  { name: "La responsabilité d'un lieutenant", index: "133" },
  { name: "L'implacable traversée", index: "134" },
  { name: "La tournant décisif de Kokuyou", index: "135" },
  { name: "La tragédie de Rigan", index: "136" },
  { name: "L'espace d'un instant", index: "137" },
  { name: "Infortune", index: "138" },
  { name: "Un cri de fierté", index: "139" },
  { name: "Bihei & l'unité Hi-Shin", index: "140" },
  { name: "La nuit décisive", index: "141" },
  { name: "L'honneur de Saitaku", index: "142" },
];

export default episodes;
