const names = [
  { name: "Aladin et Ali Baba", index: "1" },
  { name: "Suite pour labyrinthe", index: "2" },
  { name: "Le magicien de la création", index: "3" },
  { name: "Le Peuple des steppes", index: "4" },
  { name: "L'Explorateur de labyrinthes", index: "5" },
  { name: "La Tribu des guerriers Fanalis", index: "6" },
  { name: "Son nom est Sindbad", index: "7" },
  { name: "Une Promesse intenable", index: "8" },
  { name: "La Responsabilité du Prince", index: "9" },
  { name: "Son nom est Judal", index: "10" },
  { name: "Une Nouvelle Venue", index: "11" },
  { name: "Résolution et séparation", index: "12" },
  { name: "Le Prince de la rébellion", index: "13" },
  { name: "La réponse d'Ali Baba", index: "14" },
  { name: "La réponse de Qasim", index: "15" },
  { name: "La sagesse de Salomon", index: "16" },
  { name: "Sourire", index: "17" },
  { name: "Le Royaume de Sindoria", index: "18" },
  { name: "Un suspect nommé Sindbad", index: "19" },
  { name: "Prince royal et prince impérial", index: "20" },
  { name: "Le labyrinthe de Zagan", index: "21" },
  { name: "Le lige des flammes", index: "22" },
  { name: "Cri de guerre", index: "23" },
  { name: "Corruption", index: "24" },
  { name: "Ali Baba et Aladin", index: "25" },
  { name: "Prescience d'un voyage", index: "26" },
  { name: "Voyage", index: "27" },
  { name: "Départ", index: "28" },
  { name: "Pirates", index: "29" },
  { name: "Mère", index: "30" },
  { name: "Quelqu'un de gentil", index: "31" },
  { name: "Kôha Ren entre en scène", index: "32" },
  { name: "Journées d'entraînement", index: "33" },
  { name: "L'empire Reim", index: "34" },
  { name: "La Grande Prêtresse", index: "35" },
  { name: "Le Grand Canyon", index: "36" },
  { name: "Le nouvel empereur", index: "37" },
  { name: "Titus Alexius", index: "38" },
  { name: "Les citoyens cachés", index: "39" },
  { name: "Le Pays des Mages", index: "40" },
  { name: "Le temps qu'il me reste à vivre", index: "41" },
  { name: "Déclaration de guerre", index: "42" },
  { name: "La menace de Reim", index: "43" },
  { name: "Un vrai Magi", index: "44" },
  { name: "Retrouvailles", index: "45" },
  { name: "L'étoffe d'un roi", index: "46" },
  { name: "Ce que je veux protéger", index: "47" },
  { name: "Revêtemage", index: "48" },
  { name: "L'Heure de la destruction", index: "49" },
  { name: "Bienvenue chez toi", index: "50" },
];

export default names;
