const names = [
  { index: "1", name: "Séquence Assassinat" },
  { index: "2", name: "Séquence Baseball" },
  { index: "3", name: "Séquence Karma" },
  { index: "4", name: "Séquence Adulte" },
  { index: "5", name: "Séquence Assemblée" },
  { index: "6", name: "Séquence Examen" },
  { index: "7", name: "Séquence Voyage Scolaire (1ère partie)" },
  { index: "8", name: "Séquence Voyage Scolaire (2ème partie)" },
  { index: "9", name: "Séquence nouvelle élève" },
  { index: "10", name: "Séquence L et R" },
  { index: "11", name: "Séquence nouvel élève, 2ème heure" },
  { index: "12", name: "Séquence jeux de balles" },
  { index: "13", name: "Séquence Talent" },
  { index: "14", name: "Séquence Vision" },
  { index: "15", name: "Séquence Examens Trimestriels" },
  { index: "16", name: "Séquence fin de trimestre" },
  { index: "17", name: "Séquence île" },
  { index: "18", name: "Séquence exécution" },
  { index: "19", name: "Séquence antre des démons" },
  { index: "20", name: "Séquence Karma, 2ème heure" },
  { index: "21", name: "Séquence XX/Séquence Takaoka" },
  { index: "22", name: "Séquence Nagisa" },
  { index: "23", name: "Séquence festival d'été" },
  { index: "24", name: "Séquence Kaede" },
  { index: "25", name: "Séquence Itona Horibe" },
  { index: "26", name: "Séquence Filage" },
  { index: "27", name: "Séquence Leader" },
  { index: "28", name: "Séquence Avant et Après" },
  { index: "29", name: "Séquence Dieu de la Mort (1ère partie)" },
  { index: "30", name: "Séquence Dieu de la Mort (2ème partie)" },
  { index: "31", name: "Séquence New Game+" },
  { index: "32", name: "Séquence Fête de l'école" },
  { index: "33", name: "Séquence Fin de trimestre, 2ème heure" },
  { index: "34", name: "Séquence Espace" },
  { index: "35", name: "Séquence laisser vivre" },
  { index: "36", name: "Séquence Véritable identité" },
  { index: "37", name: "Séquence Confession" },
  { index: "38", name: "Séquence Passé" },
  { index: "39", name: "Séquence Scission" },
  { index: "40", name: "Séquence Résultats" },
  { index: "41", name: "Séquence Espace" },
  { index: "42", name: "Séquence Saint-Valentin" },
  { index: "43", name: "Séquence Confiance" },
  { index: "44", name: "Séquence Joyeux anniversaire" },
  { index: "45", name: "Séquence Boss de Fin" },
  { index: "46", name: "Séquence Fin de scolarité" },
  { index: "47", name: "Séquence Avenir" },
];

export default names;
