const names = [
  { name: "Le génie du basket-ball est né", index: "1" },
  { name: "Mort au basket ! Hanamichi VS Rukawa", index: "2" },
  { name: "Gorille VS Hanamichi ! Un choc de puissance !", index: "3" },
  { name: "Hanamichi le basketteur rejoint l'équipe !", index: "4" },
  { name: "Un après-midi inutile !", index: "5" },
  { name: "Rukawa VS Akagi ! La confrontation !", index: "6" },
  { name: "Les débuts d'Hanamichi ! Va y voir du Dunk !", index: "7" },
  { name: "Hanamichi en pleins doutes ! Le piège du judoka", index: "8" },
  { name: "Je vais jouer au basket-ball !", index: "9" },
  { name: 'Le "tir du paysans" est difficile', index: "10" },
  { name: "Notre entraînement spécial secret entre amoureux", index: "11" },
  {
    name: "En garde Ryônan ! Le dernier entraînement avant le match",
    index: "12",
  },
  { name: "Shôhoku VS Ryônan ! Les capitaines sont en feu !", index: "13" },
  { name: "Un super match de basket-ball contre le lycée Ryônan", index: "14" },
  { name: "L'arme secrète Hanamichi sous les feux de la rampe !", index: "15" },
  { name: "C'est qui ce mec ? L'erreur de Taoka", index: "16" },
  {
    name: "Les désillusions du roi du rebond, Hanamichi Sakuragi",
    index: "17",
  },
  { name: "Les 2 dernières minutes ! Sendô, je vais te battre !", index: "18" },
  { name: "Time Up ! La bataille décisive contre Ryōnan", index: "19" },
  { name: "Les chaussures de basket", index: "20" },
  { name: "Les supers fouteurs de merde ! Hanamichi VS Miyagi", index: "21" },
  { name: "La naissance historique de la pire paire d'abrutis", index: "22" },
  { name: "Le dernier jour de l'équipe de basket de Shôhoku", index: "23" },
  {
    name: "La bataille pour le justice. L'arrivée de la bande à Sakuragi",
    index: "24",
  },
  { name: "Celui qui rêvait de remporter le titre national !", index: "25" },
  { name: "Les ennuis de Mitsui à ses 15 ans", index: "26" },
  { name: "Je veux jouer au basket !", index: "27" },
  { name: "Le début des éliminatoires du tournoi inter-lycées", index: "28" },
  { name: "Les débuts officiels d'Hanamichi !", index: "29" },
  { name: "La grande contre-attaque de la bande des repentis", index: "30" },
  { name: "Un ennemi redoutable ! L'arme secrète de Miuradai !", index: "31" },
  { name: "Le dunk ravageur du génie Hanmichi !", index: "32" },
  { name: "Hanamichi Sakuragi, l'expulsé", index: "33" },
  { name: "Le conseil du Gorille le regard qui tue", index: "34" },
  { name: "Les sentiments ardents qui nous lient", index: "35" },
  { name: "Le lycée Shido ! L'entrée en scène de Shoyô !", index: "36" },
  { name: "Hanamichi, le goût d'être titulaire !", index: "37" },
  { name: "Le rush de Rukawa !", index: "38" },
  { name: "L'inarrêtable Ryôta !", index: "39" },
  { name: "Le roi du rebond, Hanamichi Sakuragi !", index: "40" },
  { name: "Le champion de Shôyo ! Fujima entre en scène !", index: "41" },
  {
    name: "Le champion de Shôyo ! Les vraies capacités de Fujima !",
    index: "42",
  },
  { name: "Mitsui atteint ses limites", index: "43" },
  { name: "Mitsui ! L'avalanche des 3 points !", index: "44" },
  {
    name: "Tout proche de l'expulsion ! Hanamichi en difficulté !",
    index: "45",
  },
  { name: "Hanamichi ! Le dunk flamboyant !", index: "46" },
  { name: "Le défi du rival !", index: "47" },
  { name: "L'homme qui jura de battre Kainan !", index: "48" },
  { name: "Le dernier combatant de Takezono", index: "49" },
  { name: "Défier les rois !", index: "50" },
  { name: "Un joueur imprévisible ! Hanamichi en pleine forme !", index: "51" },
  { name: "L'arme secrète pour contenir Sakuragi !", index: "52" },
  { name: "Gorille blessé ! Désespoir absolu !", index: "53" },
  { name: "Le petit-frère de King Kong !", index: "54" },
  { name: "L'homme qui domine le match !", index: "55" },
  { name: "Le champion Maki à plein régime !", index: "56" },
  { name: "Anzai, le pari pour la victoire !", index: "57" },
  { name: "Des types entêtés !", index: "58" },
  { name: "Les 10 dernières secondes, l'issue finale !", index: "59" },
  { name: "Shôhoku au pied du mur !", index: "60" },
  { name: "La contre-attaque de la tête de bonze !", index: "61" },
  { name: "L'entraînement de 3 jours !", index: "62" },
  { name: "Le match au sommet ! Kainan VS Ryônan !", index: "63" },
  { name: "Démonstration de force ! Les rois de Kainan !", index: "64" },
  { name: "La confrontation ultime ! Sendô VS Maki !", index: "65" },
  { name: "Sendô, le pari éclair !", index: "66" },
  { name: "La bataille décisive ! Shôhoku VS Ryônan !", index: "67" },
  { name: "Le sauveur ! Hanamichi Sakuragi", index: "68" },
  { name: "Gorille, le désastre !", index: "69" },
  { name: "Gorilla Dunk !!", index: "70" },
  { name: "Gorille ! Le cri de la résurection !", index: "71" },
  { name: "La plus grande humiliation de sa Vie", index: "72" },
  { name: "Rukawa se déchaîne !", index: "73" },
  { name: "Le plus dangereux des challengers !", index: "74" },
  { name: "Belle action", index: "75" },
  { name: "Le pressentiment de la victoire", index: "76" },
  { name: "Vous êtes fort !", index: "77" },
  { name: "Résurrection ! Uozumi Jun le patron", index: "78" },
  { name: "La vague bleue ! La contre-attaque de Ryoonan !", index: "79" },
  { name: "Les sources d'inquiétude de Shôhoku !", index: "80" },
  { name: "Sendô s'enflamme ! Shôhoku s'écroule !!", index: "81" },
  { name: "Le débutant Hanamichi dévoile son talent", index: "82" },
  { name: "La tenacité du binoclard, le vice-capitaine", index: "83" },
  { name: "Victoire ou défaite", index: "84" },
  { name: "Un nouveau challenge", index: "85" },
  { name: "Le mystère Rukawa", index: "86" },
  { name: "Devenir le N°1 du Japon", index: "87" },
  { name: "Le pays du basket-ball, les Etats-Unis", index: "88" },
  { name: "La détermination de Rukawa !", index: "89" },
  { name: "La vraie star de Shôhoku !", index: "90" },
  { name: "Le tournoi national est en jeu !", index: "91" },
  { name: "Solidarité masculine ! La bande à Sakuragi", index: "92" },
  { name: "L'entraînement des 20 000 shoots", index: "93" },
  { name: "Intense bataille à Shizuoka ! Shôhoku VS Jôsei", index: "94" },
  { name: "Le meilleur jour d'Hanamichi", index: "95" },
  { name: "La paire de basket II", index: "96" },
  { name: "Un goût d'inachevé ! Le retour d'Uozumi", index: "97" },
  { name: "Début du match ! Shôhoku VS Shôyo et Ryônan", index: "98" },
  {
    name: "Shôhoku en danger ! Affrontement contre la plus puissante des équipes",
    index: "99",
  },
  {
    name: "L'homme par qui arrive le miracle - Hanamichi Sakuragi !",
    index: "100",
  },
  { name: "La gloire du Slam Dunk", index: "101" },
];

export default names;
