const names = [
  { name: "Ken, l’héritier de la Grande Ourse", index: "1" },
  { name: "La famine", index: "2" },
  { name: "L’homme aux 7 cicatrices", index: "3" },
  { name: "Le piège de Shin", index: "4" },
  { name: "Le retour de l’enfer", index: "5" },
  { name: "Une armée au service du mal", index: "6" },
  { name: "Ken prisonnier de l’armée divine", index: "7" },
  { name: "La guerre des sens", index: "8" },
  { name: "Seroiamo le maléfique", index: "9" },
  { name: "Ken face au dragon", index: "10" },
  { name: "Le voleur d’eau", index: "11" },
  { name: "La mort est au bout de l’enfer", index: "12" },
  { name: "Le coup du diable", index: "13" },
  { name: "Le temps de la misère", index: "14" },
  { name: "A trois tu meurs", index: "15" },
  { name: "Les loups entre eux", index: "16" },
  { name: "La trahison", index: "17" },
  { name: "Le loup des steppes", index: "18" },
  { name: "L’œil du dragon", index: "19" },
  { name: "Le vaisseau des sables", index: "20" },
  { name: "Ken l’invincible", index: "21" },
  { name: "Le combat final", index: "22" },
  { name: "La tribu sauvage", index: "23" },
  { name: "La rencontre", index: "24" },
  { name: "Vengeance", index: "25" },
  { name: "Les Kibas passent à l’attaque", index: "26" },
  { name: "La quête impossible", index: "27" },
  { name: "Les otages", index: "28" },
  { name: "Ken et son double", index: "29" },
  { name: "Le combat fraternel", index: "30" },
  { name: "L’usurpateur", index: "31" },
  { name: "Retourne en enfer, Jagger", index: "32" },
  { name: "Le village des miracles", index: "33" },
  { name: "Entre l’ange et le démon", index: "34" },
  { name: "Le fier renégat", index: "35" },
  { name: "Le cobaye", index: "36" },
  { name: "A la recherche de Toki", index: "37" },
  { name: "Le destin tragique de Bella", index: "38" },
  { name: "Les portes de l’enfer", index: "39" },
  { name: "L’enfer de Cassandra", index: "40" },
  { name: "La malédiction de Ken", index: "41" },
  { name: "Le traquenard", index: "42" },
  { name: "La chute de Cassandra", index: "43" },
  { name: "L’étoile maléfique", index: "44" },
  { name: "Lynn montre son courage", index: "45" },
  { name: "Le soulèvement", index: "46" },
  { name: "Entre la vie et la mort", index: "47" },
  { name: "Le sacrifice", index: "48" },
  { name: "Face à face", index: "49" },
  { name: "L’homme aux chiens", index: "50" },
  { name: "Le secret de Mamiya", index: "51" },
  { name: "L’étoile de la traitrise", index: "52" },
  { name: "Les esclaves de la beauté", index: "53" },
  { name: "Le bout de la route", index: "54" },
  { name: "Le dernier combat", index: "55" },
  { name: "La fin de Rei", index: "56" },
  { name: "Naissance d’une légende", index: "57" },
  { name: "Le colonel Sauzer", index: "58" },
  { name: "L’oiseau du vent", index: "59" },
  { name: "Les yeux du futur", index: "60" },
  { name: "Le fiancé", index: "61" },
  { name: "La goutte d’eau", index: "62" },
  { name: "L’invincibilité de Sauzer", index: "63" },
  { name: "Le massacre des innocents", index: "64" },
  { name: "L’épreuve de force", index: "65" },
  { name: "Le martyre de Shew", index: "66" },
  { name: "Le secret de Sauzer", index: "67" },
  { name: "La fin d’une étoile", index: "68" },
  { name: "Le destin des 3 frères", index: "69" },
  { name: "La guérison totale", index: "70" },
  { name: "La révélation des origines de Raoul et Toki", index: "71" },
  { name: "Adieu Toki", index: "72" },
  { name: "L’homme de Cirius", index: "73" },
  { name: "Le retour de Raoul, roi d’Hokuto", index: "74" },
  { name: "Ken affronte l’homme de Cirius", index: "75" },
  { name: "La provocation de Ryuga", index: "76" },
  { name: "Explications", index: "77" },
  { name: "A la recherche de Julia", index: "78" },
  { name: "Les sept cicatrices", index: "79" },
  { name: "Un combat pour la vie", index: "80" },
  { name: "Le sacrifice", index: "81" },
  { name: "Un tyran aveuglé par la haine", index: "82" },
  { name: "Vers la rencontre finale", index: "83" },
  { name: "La brigade du vent", index: "84" },
  { name: "Huey le fils du vent", index: "85" },
  { name: "Les flammes de la vengeance", index: "86" },
  { name: "Le géant invincible", index: "87" },
  { name: "Fudo le maître des montagnes", index: "88" },
  { name: "Ken suit son destin", index: "89" },
  { name: "La décision de Juza", index: "90" },
  { name: "Qui se cache sous les traits du général masqué?", index: "91" },
  { name: "Le retour de Juza des nuages", index: "92" },
  { name: "Le combat de Juza contre Raoul !", index: "93" },
  { name: "Un grand danger menace Fudo", index: "94" },
  { name: "Le piège impitoyable des sables mouvants.", index: "95" },
  { name: "La fin de Juza ! Je protégerai la femme", index: "96" },
  { name: "Adieu Julia ! Un héros emporte le secret", index: "97" },
  { name: "La capitale tremble !", index: "98" },
  { name: "Le destin tragique des étoiles filantes !", index: "99" },
  { name: "La technique ultime du Hokuto !", index: "100" },
  { name: "Les ambitions de Raoul s'effondrent,", index: "101" },
  { name: "Le supplice du géant Raoul !", index: "102" },
  { name: "Le défi du démon ! Fudo,", index: "103" },
  { name: "Fudo le héros généreux dont les larmes", index: "104" },
  { name: "Il faut protéger l'étoile de la miséricorde,", index: "105" },
  { name: "Raoul devient sentimental.", index: "106" },
  { name: "L'ultime bataille au temple de formation du Hokuto.", index: "107" },
  { name: "Les adieux des deux frères du Hokuto.", index: "108" },
  { name: "Il est temps de tout vous raconter", index: "109" },
];

export default names;
