const episodes = [
  { index: "1", name: "Renaissance" },
  { index: "2", name: "Confrontation" },
  { index: "3", name: "Pacte" },
  { index: "4", name: "Poursuite" },
  { index: "5", name: "Tactique" },
  { index: "6", name: "Déchirure" },
  { index: "7", name: "Temps couvert" },
  { index: "8", name: "Regard" },
  { index: "9", name: "Contact" },
  { index: "10", name: "Doute" },
  { index: "11", name: "Assaut" },
  { index: "12", name: "Amour" },
  { index: "13", name: "Confession" },
  { index: "14", name: "Ami" },
  { index: "15", name: "Pari" },
  { index: "16", name: "Décision" },
  { index: "17", name: "Exécution" },
  { index: "18", name: "Allié" },
  { index: "19", name: "Matsuda" },
  { index: "20", name: "Expédient" },
  { index: "21", name: "Performance" },
  { index: "22", name: "Conduite" },
  { index: "23", name: "Frénésie" },
  { index: "24", name: "Résurrection" },
  { index: "25", name: "Silence" },
  { index: "26", name: "Reprise" },
  { index: "27", name: "Enlèvement" },
  { index: "28", name: "Impatience" },
  { index: "29", name: "Père" },
  { index: "30", name: "Justice" },
  { index: "31", name: "Transfert" },
  { index: "32", name: "Choix" },
  { index: "33", name: "Arrogance" },
  { index: "34", name: "Vigilance" },
  { index: "35", name: "Tentative de meurtre" },
  { index: "36", name: "28 janvier" },
  { index: "37", name: "Le nouveau monde" },
];

export default episodes;
