export const citation: string[] = [
  'L’avenir ne peut exister que si on met sa vie en jeu ! - <span>Monkey D. Luffy</span>',
  'À quoi te sert ton ambition si tu ne peux pas protéger ton capitaine ? - <span>Roronoa Zoro</span>',
  'Les gens ne cesseront jamais d’avoir des rêves ! - <span>Barbe Noire</span>',
  'Il y a des batailles qu’on ne gagne pas avec les poings ! - <span>Barbe Noire</span>',
  'Un pirate doit être fier de son nom. Tâchez de vous souvenir du mien - <span>Monkey D. Luffy</span>',
  'Haïssez votre propre destinée, qui m’a conduit sur votre bateau tel un fléau de la mort. - <span>Roronoa Zoro</span>',
  'Si je meurs ici, c’est que je n’aurais pas pu aller au-delà - <span>Roronoa Zoro</span>',
  'La force en elle-même ne m’intéresse pas. Sauf si c’est pour défendre ceux qui me sont chers ! - <span>Monkey D. Luffy</span>',
  'Continue ta route, observe le monde de tes propres yeux et alors, peut être qu’à la fin de ton voyage tu parviendras à une conclusion différente de la nôtre - <span>Silvers Rayleigh</span>',
  'Quoi qu’il arrive, ne perdez jamais espoir face aux adversités du monde qui vous entoure ! Soyez assez forts pour pouvoir rire de tout, ne vous préoccupez pas du regard des autres. - <span>Belmer</span>',
  'Ne pas voir la pourriture de ce monde, est un plaisir uniquement connu des aveugles. - <span>Fujitora</span>',
  'La passion et les rêves sont comme le temps, rien ne peut les arrêter, et il en sera ainsi tant qu’il y aura des hommes prêts à donner un sens au mot « LIBERTE » - <span>Gol D. Roger</span>',
  'La justice crée par l’humanité ne périra jamais - <span>Sengoku</span>',
  'Justice vaincra ? Je ne vois pas comment il pourrait en être autrement ! La justice est toujours du côté des vainqueurs ! - <span>Doflamingo</span>',
  'Je ne suis pas né homme pour céder devant la force. - <span>Portgas D. Ace</span>',
  "Un homme meurt quand il tombe dans l'oubli. - <span>Hiluluk</span>",
  'Je ne ferai rien que je puisse regretter un jour. - <span>Portgas D. Ace</span>',
  'Quand on a faim, on mange ! - <span>Monkey D. Luffy</span>',
  "J'ai fait équipe avec vous uniquement parce que nous avions des intérêts communs. - <span>Nami</span>",
  'A-t-on déjà vu un cuisinier qui ait peur du feu. - <span>Sanji</span>',
  "Les gradés ne commentent jamais d'erreur. - <span>Morgan</span>",
  "Sous aucun prétexte je ne pardonnerai à ceux qui s'en prennent à mes amis. - <span>Shanks</span>",
  'Si vous les avez au bout du fil, dites leur que je ne reçois aucun ordre de personne. - <span>Smoker</span>',
  "Je vous pardonne, savez-vous pourquoi? Tout simplement parce que je n'ai jamais fait confiance à personne. - <span>Crocodile</span>",
];
