const episodes = [
  { index: "1", name: "Un Camarade détestable" },
  { index: "2", name: "La Création de Shadow Garden" },
  { index: "3", name: "L'Escrime des laborieux" },
  { index: "4", name: "La Récompense des tortionnaires" },
  { index: "5", name: "I am..." },
  { index: "6", name: "Les Imposteurs" },
  { index: "7", name: "Le Complot et le Tournoi sanglant" },
  { index: "8", name: "Assaut sur l'académie des magelames" },
  { index: "9", name: "Au bout du mensonge" },
  { index: "10", name: "Lindblum, Terre Sainte et capitale de la duperie" },
  { index: "11", name: "Les Épreuves de la déesse" },
  { index: "12", name: "La Vérité dans les souvenirs" },
  { index: "13", name: "Combat sanglant pour l'anéantissement" },
  { index: "14", name: "Tes mensonges, tes souhaits" },
  { index: "15", name: "La Force du plus faible" },
  { index: "16", name: "Intentions invisibles" },
  { index: "17", name: "Le Clair de lune qui perçait les ténèbres" },
  { index: "18", name: "Tout jouer sur un instant" },
  { index: "19", name: "Le Pantin dansant" },
  { index: "20", name: "La Venue du démon" },
  { index: "21", name: "La Cité sans loi" },
  { index: "22", name: "La Terre du repos" },
  { index: "23", name: "L'Heure du réveil" },
  { index: "24", name: "Le Masque du mensonge" },
  { index: "25", name: "Celui qui tire les ficelles" },
  { index: "26", name: "John Smith" },
  { index: "27", name: "Ce qui m'est cher" },
  { index: "28", name: "Les Larmes du dragon" },
  { index: "29", name: "La Clé" },
  { index: "30", name: "L'Oiseau en cage" },
  { index: "31", name: "La Décision" },
  { index: "32", name: "Tout en haut" },
];

export default episodes;
