const episodes = [
  { name: "Le « Black Lagoon »", index: 1 },
  { name: "Le Paradis de Mangroves", index: 2 },
  { name: "Poursuite infernale", index: 3 },
  { name: "Le retour de l'Aigle", index: 4 },
  { name: "Chasse à l'aigle et Aigles en chasse", index: 5 },
  { name: "Chasse au clair de lune", index: 6 },
  { name: "Du calme, vous deux", index: 7 },
  { name: "Rasta Blasta", index: 8 },
  { name: "Bonne à tuer", index: 9 },
  { name: "La bonne invincible", index: 10 },
  { name: "Révolution ciblée", index: 11 },
  { name: "Guérillas dans la jungle", index: 12 },
  { name: "L'avènement des jumeaux vampires", index: 13 },
  { name: "Un conte de fées sanglant", index: 14 },
  { name: "Le chant du cygne à l'aube", index: 15 },
  { name: "Jane aux billets verts", index: 16 },
  { name: "Le cirque des curiosités de Roanapur", index: 17 },
  { name: "La chance de M. Benny", index: 18 },
  { name: "Le mont Fuji : le paradis des gangsters", index: 19 },
  { name: "La succession", index: 20 },
  { name: "Les fillettes soldats des deux pères", index: 21 },
  { name: "La Tour Sombre", index: 22 },
  { name: "La revanche de Blanche Neige", index: 23 },
  { name: "Les flingueurs", index: 24 },
  { name: "Massacre collatéral", index: 25 },
  { name: "Tactiques d'un employé de bureau", index: 26 },
  { name: "Les anges dans le viseur", index: 27 },
  { name: "Tuerie en surchauffe", index: 28 },
  { name: "Codename Paradise, Status MIA", index: 29 },
];

export default episodes;
