const names = [
  { name: "Le Garçon Bloqué dans l'Iceberg", index: "1" },
  { name: "Avatar, le Retour", index: "2" },
  { name: "Le Temple de l'Air Austral", index: "3" },
  { name: "Les Guerriers de Kyoshi", index: "4" },
  { name: "Le Roi d'Omashu", index: "5" },
  { name: "Emprisonnée", index: "6" },
  { name: "Solstice d'Hiver, Partie 1 : Le Monde Spirituel", index: "7" },
  { name: "Solstice d'Hiver, Partie 2 : L'Avatar Roku", index: "8" },
  { name: "Le Manuscrit de la Maîtrise de l'Eau", index: "9" },
  { name: "Jet", index: "10" },
  { name: "Le Grand Canyon", index: "11" },
  { name: "La Tempête", index: "12" },
  { name: "L'Esprit Bleu", index: "13" },
  { name: "La Diseuse de Bonne Aventure", index: "14" },
  { name: "Bato de la Tribu de l'Eau", index: "15" },
  { name: "Le Déserteur", index: "16" },
  { name: "Le Temple de l'Air Boréal", index: "17" },
  { name: "Le Grand Maître de l'Eau", index: "18" },
  { name: "Le Siège du Nord, Partie 1", index: "19" },
  { name: "Le Siège du Nord, Partie 2", index: "20" },
  { name: "L'État d'Avatar", index: "21" },
  { name: "La Grotte des Amoureux", index: "22" },
  { name: "Retour à Omashu", index: "23" },
  { name: "Le Marais", index: "24" },
  { name: "La Fête de l'Avatar", index: "25" },
  { name: "La Fripouille Aveugle", index: "26" },
  { name: "Zuko, Seul", index: "27" },
  { name: "Pris en Chasse", index: "28" },
  { name: "Un Apprentissage Difficile", index: "29" },
  { name: "La Bibliothèque", index: "30" },
  { name: "Le Désert", index: "31" },
  { name: "Le Passage du Serpent", index: "32" },
  { name: "La Foreuse", index: "33" },
  { name: "Une Cité de Murailles et de Secrets", index: "34" },
  { name: "Les Contes de Ba Sing Se", index: "35" },
  { name: "Les Jours Perdus d'Appa", index: "36" },
  { name: "Le Lac Laogai", index: "37" },
  { name: "Le Roi de la Terre", index: "38" },
  { name: "Le Gourou", index: "39" },
  { name: "Les Carrefours du Destin", index: "40" },
  { name: "Le Réveil", index: "41" },
  { name: "Le Bandeau", index: "42" },
  { name: "La Dame Peinte", index: "43" },
  { name: "Le Maître de Sokka", index: "44" },
  { name: "La Plage", index: "45" },
  { name: "L'Avatar et le Seigneur du Feu", index: "46" },
  { name: "La Fugitive", index: "47" },
  { name: "La Marionnettiste", index: "48" },
  { name: "Cauchemars et Hallucinations", index: "49" },
  { name: "Le Jour du Soleil Noir, Partie 1 : L'Invasion", index: "50" },
  { name: "Le Jour du Soleil Noir, Partie 2 : L'Éclipse", index: "51" },
  { name: "Le Temple de l'Air de l'Ouest", index: "52" },
  { name: "Les Maîtres du Feu", index: "53" },
  { name: "Le Rocher Bouillant, Partie 1", index: "54" },
  { name: "Le Rocher Bouillant, Partie 2", index: "55" },
  { name: "Les Cuirassés du Sud", index: "56" },
  { name: "Les Acteurs de l'Île de Braise", index: "57" },
  { name: "La Comète de Sozin, Partie 1 : Le Roi Phénix", index: "58" },
  { name: "La Comète de Sozin, Partie 2 : Les Vieux Maîtres", index: "59" },
  { name: "La Comète de Sozin, Partie 3 : Dans le Brasier", index: "60" },
  { name: "La Comète de Sozin, Partie 4 : L'Avatar Aang", index: "61" },
];

export default names;
