const names = [
  { name: "Le héros au bouclier", index: "1" },
  { name: "La jeune esclave", index: "2" },
  { name: "La vague de calamités", index: "3" },
  { name: "La berceuse de l'aube", index: "4" },
  { name: "Filo", index: "5" },
  { name: "Nouvelle coéquipière", index: "6" },
  { name: "Le saint de l'oiseau divin", index: "7" },
  { name: "Le bouclier du courroux", index: "8" },
  { name: "Melty", index: "9" },
  { name: "Dans la tourmente", index: "10" },
  { name: "Calamités, le retour", index: "11" },
  { name: "La ténébreuse inconnue", index: "12" },
  { name: "Le démon au bouclier", index: "13" },
  { name: "Des souvenirs indélébiles", index: "14" },
  { name: "Raphtalia", index: "15" },
  { name: "La reine des filoriaux", index: "16" },
  { name: "L'héritage de la promesse", index: "17" },
  { name: "Complots à la chaîne", index: "18" },
  { name: "Les quatre saints ancestraux", index: "19" },
  { name: "Combat entre le bien et le mal", index: "20" },
  { name: "Le retour triomphal de Naofumi", index: "21" },
  { name: "La réunion des héros", index: "22" },
  { name: "Les îles Carmila", index: "23" },
  { name: "Les gardiens d'un autre monde", index: "24" },
  { name: "L'avènement du héros au bouclier", index: "25" },
  { name: "Un nouveau cri", index: "26" },
  { name: "Les traces de la Tortue Spirituelle", index: "27" },
  { name: "La terre tremble", index: "28" },
  { name: "Vestiges dans le brouillard", index: "29" },
  { name: "Aust Penglai", index: "30" },
  { name: "Poursuite", index: "31" },
  { name: "Labyrinthe infini", index: "32" },
  { name: "Départ enneigé", index: "33" },
  { name: "La nymphe qui fredonne", index: "34" },
  { name: "Le héros à l'épée", index: "35" },
  { name: "Kizuna", index: "36" },
  { name: "Raison de combattre", index: "37" },
  { name: "Fleurs de souvenirs", index: "38" },
  { name: "Le colisée de l'ombre", index: "39" },
  { name: "Nadia", index: "40" },
  { name: "La fatrie des tigres blancs", index: "41" },
  { name: "Plan de capture du héros à la lance", index: "42" },
  { name: "Chacun son chemin", index: "43" },
  { name: "La pointe de lance de la force", index: "44" },
  { name: "La fille et le dragon", index: "45" },
  { name: "Le nid du dragon", index: "46" },
  { name: "Dragon démoniaque", index: "47" },
  { name: "Perfect = Hide = Justice", index: "48" },
  { name: "Justice contre justice", index: "49" },
  { name: "Ceux qu'il faut protéger", index: "50" },
];

export default names;
