const names = [
  { name: "Trick: 1", index: "1" },
  { name: "Trick: 2", index: "2" },
  { name: "Trick: 3", index: "3" },
  { name: "Trick: 4", index: "4" },
  { name: "Trick: 5", index: "5" },
  { name: "Trick: 6", index: "6" },
  { name: "Trick: 7", index: "7" },
  { name: "Trick: 8", index: "8" },
  { name: "Trick: 9", index: "9" },
  { name: "Trick: 10", index: "10" },
  { name: "Trick: 11", index: "11" },
  { name: "Trick: 12", index: "12" },
  { name: "Trick: 13", index: "13" },
  { name: "Trick: 14", index: "14" },
  { name: "Trick: 15", index: "15" },
  { name: "Trick: 16", index: "16" },
  { name: "Trick: 17", index: "17" },
  { name: "Trick: 18", index: "18" },
  { name: "Trick: 19", index: "19" },
  { name: "Trick: 20", index: "20" },
  { name: "Trick: 21", index: "21" },
  { name: "Trick: 22", index: "22" },
  { name: "Trick: 23", index: "23" },
  { name: "Trick: 24", index: "24" },
  { name: "Trick: 25", index: "25" },
];

export default names;
