const episodes = [
  { name: "Le jour où le démon vient au monde", index: "1" },
  { name: "L'éveil du chevalier blanc", index: "2" },
  { name: "Le faux camarade de classe", index: "3" },
  { name: "Son nom est Zero", index: "4" },
  { name: "La princesse et la sorcière", index: "5" },
  { name: "Le masque volé", index: "6" },
  { name: "Tir sur Cornelia !", index: "7" },
  { name: "L'Ordre des Chevaliers Noirs", index: "8" },
  { name: "Refrain", index: "9" },
  { name: "Le Guren danse", index: "10" },
  { name: "La bataille de Narita", index: "11" },
  { name: "Le Messager de Kyôto", index: "12" },
  { name: "Shirley et l'arme", index: "13" },
  { name: "Geass contre Geass", index: "14" },
  { name: "Mao applaudit", index: "15" },
  { name: "Nunnally enlevée", index: "16" },
  { name: "Chevalier", index: "17" },
  { name: "Je t'ordonne, Suzaku Kururugi...", index: "18" },
  { name: "L'île des dieux", index: "19" },
  { name: "La Bataille de Kyûshû", index: "20" },
  { name: "Annonce à la fête de l'académie", index: "21" },
  { name: "Euphie baignée de sang", index: "22" },
  { name: "Avec au moins du chagrin", index: "23" },
  { name: "Où tout s'effondre", index: "24" },
  { name: "Zero", index: "25" },
  { name: "Le Jour de l'Eveil du Démon", index: "26" },
  { name: "Plan pour un Japon indépendant", index: "27" },
  { name: "En prison à l'Académie", index: "28" },
  { name: "Contre-attaque sur l'échafaud", index: "29" },
  { name: "Les Chevaliers de la Table Ronde", index: "30" },
  { name: "Guet-Apens au-dessus du Pacifique", index: "31" },
  { name: "Le masque abandonné", index: "32" },
  { name: "Un million de miracles", index: "33" },
  { name: "Une fiancée dans la Cité Interdite", index: "34" },
  { name: "Quand brille le Shen Hu", index: "35" },
  { name: "La force des sentiments", index: "36" },
  { name: "Love attack !", index: "37" },
  { name: "L'assassin venu du passé", index: "38" },
  { name: "Chasse au Geass", index: "39" },
  { name: "Le monde de C", index: "40" },
  {
    name: "Première résolution de la Fédération des Nations Unies",
    index: "41",
  },
  { name: "De la terre dans la bouche", index: "42" },
  { name: "La deuxième bataille de Tokyo", index: "43" },
  { name: "Trahison", index: "44" },
  { name: "L'empereur démis", index: "45" },
  { name: "La jonction Ragnarök", index: "46" },
  { name: "Lelouch Empereur", index: "47" },
  { name: "Le masque de Schneizel", index: "48" },
  { name: "Les cieux sous le Damoclès", index: "49" },
  { name: "Zero Requiem", index: "50" },
];

export default episodes;
