const episodes = [
  { name: "Le prince nu", index: "1" },
  { name: "Le prince et son ombre", index: "2" },
  { name: "Le nouveau roi", index: "3" },
  { name: "Le premier voyage", index: "4" },
  { name: "Des complots entremêlés", index: "5" },
  { name: "Le roi des enfers", index: "6" },
  { name: "Le prince apprenti", index: "7" },
  { name: "Les sacrifices d'un souhait", index: "8" },
  { name: "La reine et son bouclier", index: "9" },
  { name: "L'épée du prince", index: "10" },
  { name: "Les deux frères", index: "11" },
  { name: "Un conflit en approche", index: "12" },
  { name: "Un royaume ébranlé", index: "13" },
  { name: "Le retour du prince", index: "14" },
  { name: "Les chevaliers des enfers", index: "15" },
  { name: "La dignité d'un roi", index: "16" },
  { name: "Le fléau de l'immortalité", index: "17" },
  { name: "La guerre contre les dieux", index: "18" },
  { name: "L'ultime rempart", index: "19" },
  { name: "L'immortel contre l'invincible", index: "20" },
  { name: "L'épée du roi", index: "21" },
  { name: "La promesse faite au génie", index: "22" },
  { name: "Le roi et son soleil", index: "23" },
  { name: "Les douze travaux d'Ombre - Le prince et l'or", index: "24" },
  { name: "Les animaux de la lande - Le désert mystérieux", index: "25" },
  { name: "La vielle amie de Hiling - Daida et la magie", index: "26" },
  { name: "Les trois frères et l'immortalité", index: "27" },
  {
    name: "La loi des enfers - Le cheval blanc se rue - Hokuro, le soldat au cœur tendre",
    index: "28",
  },
  { name: "Bojji devenu roi - La mélancolie du roi Daida", index: "29" },
  {
    name: "Le sourire du charmeur de serpents - Le festin des gardes royaux élites",
    index: "30",
  },
  { name: "Le rêve d'Ombre - Une maman en or", index: "31" },
  { name: "Miranjo et le génie - Les trésors du prince", index: "32" },
  { name: "La fine lame renaît", index: "33" },
];

export default episodes;
