const episodes = [
  { name: "L'Alchimiste Fullmetal", index: "1" },
  { name: "Le Premier Jour", index: "2" },
  { name: "La Ville hérétique", index: "3" },
  { name: "L'Angoisse de l'Alchimiste", index: "4" },
  { name: "Pluie de chagrin", index: "5" },
  { name: "Un foyer et Une famille", index: "6" },
  { name: "La Vérité cachée", index: "7" },
  { name: "Le Cinquième Laboratoire", index: "8" },
  { name: "Sentiments composés", index: "9" },
  { name: "Chacun sa route", index: "10" },
  { name: "Miracle à Rush Valley", index: "11" },
  { name: "Un est tout, tout n'est qu'un", index: "12" },
  { name: "Les Bêtes de Dublith", index: "13" },
  { name: "Ce qui se tapit au sous-sol", index: "14" },
  { name: "Le Messager de l'Est", index: "15" },
  { name: "Les Traces d'un compagnon d'armes", index: "16" },
  { name: "La Flamme froide", index: "17" },
  { name: "L'Arrogance au creux de sa jeune main", index: "18" },
  { name: "La mort de ce qui ne peut pas mourir", index: "19" },
  { name: "Le Père devant la tombe", index: "20" },
  { name: "L'Avancée de l'imbécile", index: "21" },
  { name: "La silhouette que l'on voit au loin", index: "22" },
  { name: "Une Jeune Fille sur le champ de bataille", index: "23" },
  { name: "Dans le ventre", index: "24" },
  { name: "La Porte des ténèbres", index: "25" },
  { name: "Retrouvailles", index: "26" },
  { name: "Le Banquet d'interlude", index: "27" },
  { name: "Père", index: "28" },
  { name: "Les Divagations d'un imbécile", index: "29" },
  { name: "L'Extermination d'Ishbal", index: "30" },
  { name: "Une promesse à 520 cenz", index: "31" },
  { name: "Le Fils du Führer", index: "32" },
  { name: "La Muraille nord de Briggs", index: "33" },
  { name: "La Reine des glaces", index: "34" },
  { name: "Les Contours de ce pays", index: "35" },
  { name: "Portrait de famille", index: "36" },
  { name: "Le Premier Homonculus", index: "37" },
  { name: "La Bataille de Baschool", index: "38" },
  { name: "Un rêve éveillé", index: "39" },
  { name: "Homonculus, le petit être dans une fiole", index: "40" },
  { name: "Abysses", index: "41" },
  { name: "Le Début de la contre-attaque", index: "42" },
  { name: "La Morsure d'une fourmi", index: "43" },
  { name: "En avant toute !", index: "44" },
  { name: "Le Jour promis", index: "45" },
  { name: "L'ombre qui approche", index: "46" },
  { name: "Le Messager des ténèbres", index: "47" },
  { name: "La Promesse du passage souterrain", index: "48" },
  { name: "Amour familial", index: "49" },
  { name: "Panique à Central", index: "50" },
  { name: "L'Armée immortelle", index: "51" },
  { name: "L'union fait la force", index: "52" },
  { name: "Les Flammes de la vengeance", index: "53" },
  { name: "La Terre Brûlée", index: "54" },
  { name: "L'Éthique de vie de ces adultes", index: "55" },
  { name: "Le Retour du Führer", index: "56" },
  { name: "Repos éternel", index: "57" },
  { name: "Sacrifices humains", index: "58" },
  { name: "Lumière perdue", index: "59" },
  { name: "L'Œil du ciel, la porte de la terre", index: "60" },
  { name: "Celui qui avale Dieu", index: "61" },
  { name: "Contre-attaque déchaînée", index: "62" },
  { name: "De l'autre côté de la porte", index: "63" },
  { name: "Au bout du voyage", index: "64" },
];

export default episodes;
