const names = [
  { name: "Engagement", index: "1" },
  { name: "Terme du contrat", index: "2" },
  { name: "Début de situation difficile", index: "3" },
  { name: "Saisie manuscrite", index: "4" },
  { name: "Mémo vocal", index: "5" },
  { name: "Mode vibreur", index: "6" },
  { name: "Tonalité", index: "7" },
  { name: "Nouveau modèle", index: "8" },
  { name: "Numéro bloqué", index: "9" },
  { name: "Régime familial", index: "10" },
  { name: "Cessation de service", index: "11" },
  { name: "Pas de réception", index: "12" },
  { name: "Appel limité", index: "13" },
  { name: "Réinitialisation de la mémoire", index: "14" },
  { name: "Forfait couple", index: "15" },
  { name: "Réparation", index: "16" },
  { name: "Réduction famille", index: "17" },
  { name: "Fils croisés", index: "18" },
  { name: "Supprimer tous les messages", index: "19" },
  { name: "Transfert de données", index: "20" },
  { name: "MOT DE PASSE", index: "21" },
  { name: "Déconnexion", index: "22" },
  { name: "Rupture de contrat", index: "23" },
  { name: "Récupération des données", index: "24" },
  { name: "Réinitialisation", index: "25" },
  { name: "formatage", index: "26" },
  { name: "Recomposé (redial)", index: "27" },
];

export default names;
