export default [
  {
    index: '1',
    name: 'À toi qui vis 2000 ans plus tard  – La chute de Shiganshina',
  },
  { index: '2', name: 'Ce jour-là' },
  {
    index: '3',
    name: 'Une faible étincelle dans le désespoir  – Le réveil de l’humanité',
  },
  {
    index: '4',
    name: 'Le soir de la cérémonie de fin d’entraînement',
  },
  {
    index: '5',
    name: 'Première bataille  – La lutte pour le district Trost',
  },
  { index: '6', name: 'Une petite lame' },
  { index: '7', name: 'Courte lame' },
  { index: '8', name: 'J’entends les battements de ton cœur' },
  { index: '9', name: 'Qu’est-il advenu du bras gauche ?' },
  { index: '10', name: 'Répondre' },
  { index: '11', name: 'Idole' },
  { index: '12', name: 'Blessure' },
  { index: '13', name: 'Désir primitif' },
  {
    index: '14',
    name: 'On ne peut pas le regarder dans les yeux  – La veille de la contre-attaque',
  },
  { index: '15', name: 'Unité d’intervention' },
  { index: '16', name: 'Ce qu’il faut faire maintenant' },
  {
    index: '17',
    name: 'Le Titan féminin  – La 57e expédition extra-muros',
  },
  { index: '18', name: 'La forêt des arbres géants' },
  { index: '19', name: 'Morsure' },
  { index: '20', name: 'Erwin Smith' },
  { index: '21', name: 'Coup dur' },
  { index: '22', name: 'Les vaincus' },
  {
    index: '23',
    name: 'Sourire  – Attaque surprise au district de Stohess',
  },
  { index: '24', name: 'Pitié' },
  { index: '25', name: 'Mur' },
  { index: '26', name: 'Le Titan bestial' },
  { index: '27', name: 'De retour au village' },
  { index: '28', name: 'Direction le sud-ouest' },
  { index: '29', name: 'Soldats' },
  { index: '30', name: 'Historia' },
  { index: '31', name: 'Guerriers' },
  { index: '32', name: 'Percussion, projection, préhension' },
  { index: '33', name: 'Poursuite' },
  { index: '34', name: 'Paroles' },
  { index: '35', name: 'Enfants' },
  { index: '36', name: 'Assaut' },
  { index: '37', name: 'Le cri' },
  { index: '38', name: 'Colonne de fumée' },
  { index: '39', name: 'Douleur' },
  { index: '40', name: 'Souvenirs' },
  { index: '41', name: 'Confiance' },
  { index: '42', name: 'Réponse' },
  { index: '43', name: 'Crime' },
  { index: '44', name: 'Souhait' },
  { index: '45', name: 'Le rempart d’Orvud' },
  { index: '46', name: 'La reine de ces murs' },
  { index: '47', name: 'L’amitié' },
  { index: '48', name: 'Un simple spectateur' },
  { index: '49', name: 'À la veille de la reconquête' },
  { index: '50', name: 'La cité où tout a commencé' },
  { index: '51', name: 'La lance foudroyante' },
  { index: '52', name: 'Irruption' },
  { index: '53', name: 'Match parfait' },
  { index: '54', name: 'Héroïque' },
  { index: '55', name: 'Soleil de minuit' },
  { index: '56', name: 'Le sous-sol ' },
  { index: '57', name: 'Ce jour de mon enfance' },
  { index: '58', name: 'Le titan assaillant' },
  { index: '59', name: 'De l’autre côté' },
  { index: '60', name: 'De l’autre côté de la mer' },
  { index: '61', name: 'Train de nuit' },
  { index: '62', name: 'La porte de l’espoir' },
  { index: '63', name: 'De main en main' },
  { index: '64', name: 'Déclaration de guerre' },
  { index: '65', name: 'Le titan marteau' },
  { index: '66', name: 'L’assaut' },
  { index: '67', name: 'Balle mortelle' },
  { index: '68', name: 'Les mercenaires' },
  { index: '69', name: 'De beaux principes' },
  { index: '70', name: 'Imposture' },
  { index: '71', name: 'Le guide' },
  { index: '72', name: 'Les enfants de la forêt' },
  { index: '73', name: 'Sauvagerie' },
  { index: '74', name: 'La seule solution' },
  { index: '75', name: 'Ciel et terre' },
  { index: '76', name: 'Jugement' },
  { index: '77', name: 'Ruse' },
  { index: '78', name: 'L’aîné et le cadet' },
  { index: '79', name: 'Un instant' },
  { index: '80', name: 'De toi, il y a deux mille ans' },
  { index: '81', name: 'Le dégel' },
  { index: '82', name: 'Le coucher du soleil' },
  { index: '83', name: 'Amour-propre' },
  { index: '84', name: 'La nuit du final' },
  { index: '85', name: 'Traître' },
  { index: '86', name: 'Rétrospection' },
  { index: '87', name: 'L’aube de l’Humanité' },
  { index: '88', name: 'The Final Chapters Part 1' },
  { index: '89', name: 'The Final Chapters Part 2' },
];
