const names = [
  { name: "Tragédie", index: "1" },
  { name: "Solitude", index: "2" },
  { name: "Colombes", index: "3" },
  { name: "Dîner", index: "4" },
  { name: "Cicatrice", index: "5" },
  { name: "Ondée", index: "6" },
  { name: "Emprisonnement", index: "7" },
  { name: "Cercle", index: "8" },
  { name: "Cage", index: "9" },
  { name: "L'Arbre Aogiri", index: "10" },
  { name: "Frénésie", index: "11" },
  { name: "Goule", index: "12" },
  { name: "Foi", index: "13" },
  { name: "Fleurs Dansantes", index: "14" },
  { name: "Pendu", index: "15" },
  { name: "Profondeur", index: "16" },
  { name: "Fissures", index: "17" },
  { name: "Mille chemins", index: "18" },
  { name: "Imprégnation", index: "19" },
  { name: "Les 9", index: "20" },
  { name: "Panoramique", index: "21" },
  { name: "Dernière pluie", index: "22" },
  { name: "Des fleurs à foison", index: "23" },
  { name: "Aiguiser", index: "24" },
  { name: "Les Chasseurs", index: "25" },
  { name: "Fragments", index: "26" },
  { name: "La Veille", index: "27" },
  { name: "Les Enchères", index: "28" },
  { name: "La nuit se disperse", index: "29" },
  { name: "Au point culminant", index: "30" },
  { name: "Quotidien remémoré", index: "31" },
  { name: "Les Rampants", index: "32" },
  { name: "Revenant", index: "33" },
  { name: "Tremblements", index: "34" },
  { name: "Ange déchu", index: "35" },
  { name: "Aube", index: "36" },
  { name: "Et encore une fois", index: "37" },
  { name: "Ténèbres blanches", index: "38" },
  { name: "Cross Game", index: "39" },
  { name: "Ce qu'on laisse derrière soi", index: "40" },
  { name: "Rencontre et confusion", index: "41" },
  { name: "Magistral", index: "42" },
  { name: "Liens", index: "43" },
  { name: "Le Réveil", index: "44" },
  { name: "Rappel", index: "45" },
  { name: "La Tragédie à son comble", index: "46" },
  { name: "Rencontres inattendues", index: "47" },
  { name: "Dénouement", index: "48" },
];

export default names;
