const episodes = [
  { index: "1", name: "Transperce les cieux avec ta vrille !" },
  { index: "2", name: "Celui-là, c'est moi qui vais le piloter, je te dis !" },
  { index: "3", name: "Arrête de te la péter avec tes deux têtes !" },
  { index: "4", name: "C'est pas le nombre de têtes qui compte !" },
  { index: "5", name: "Sérieux, je pige que dalle à tout ça !" },
  {
    index: "6",
    name: "Dans la vie, y a des occases qu'un mec peut pas rater !",
  },
  { index: "7", name: "C'est toi qui vas te charger du boulot !" },
  { index: "8", name: "Adieu, mon Frère..." },
  { index: "9", name: "Un humain ? Qu'est-ce que c'est exactement ?" },
  { index: "10", name: "Ton Frangin, quel genre de personne c'était ?" },
  { index: "11", name: "Simon, est-ce que je peux ?" },
  { index: "12", name: "Mademoiselle Yoko, j'ai une faveur à vous demander" },
  { index: "13", name: "Bon appétit à tous !" },
  { index: "14", name: "Salutations à tous !" },
  { index: "15", name: "Désormais, je regarderai vers le lendemain" },
  { index: "16", name: "Rétrospection" },
  { index: "17", name: "Tu ne comprends vraiment rien à rien" },
  { index: "18", name: "Je veux tout savoir sur ce monde" },
  { index: "19", name: "Nous survivrons, quel que soit le moyen" },
  { index: "20", name: "Jusqu'où les Dieux nous mettront-ils à l'épreuve ?" },
  { index: "21", name: "Vous êtes de ceux qui doivent survivre" },
  { index: "22", name: "Ceci est mon ultime devoir !" },
  { index: "23", name: "En route pour le combat final !" },
  { index: "24", name: "Je n'oublierai jamais cette minute, cette seconde !" },
  { index: "25", name: "Que ta dernière volonté soit respectée!" },
  { index: "26", name: "En avant camarades !" },
  { index: "27", name: "La piste des étoiles" },
];

export default episodes;
