export default [
  { index: '1', name: 'Uzumaki Boruto !!' },
  { index: '2', name: 'Le fils du Hokage…!!' },
  { index: '3', name: 'Metal Lee le fougueux !!' },
  { index: '4', name: 'Bataille Ninjutsu entre garçons et filles !!' },
  { index: '5', name: 'Le mystérieux étudiant transféré…!!' },
  { index: '6', name: 'La dernière leçon…!!' },
  { index: '7', name: 'L’amour et les chips pomme de terre…!!' },
  { index: '8', name: 'La révélation du rêve' },
  { index: '9', name: 'La preuve de soi-même' },
  { index: '10', name: 'L’incident fantôme, l’enquête commence !!' },
  { index: '11', name: 'L’ombre du cerveau' },
  { index: '12', name: 'Boruto et Mitsuki' },
  { index: '13', name: 'La bête démon, apparaît…!!' },
  { index: '14', name: 'Le chemin que Boruto peut voir' },
  { index: '15', name: 'Un nouveau chemin' },
  { index: '16', name: 'La crise du redoublement' },
  { index: '17', name: 'Cours, Salada !!' },
  { index: '18', name: 'Une journée dans la vie de la famille Uzumaki' },
  { index: '19', name: 'Uchiha Salada' },
  { index: '20', name: 'Le garçon au Sharingan' },
  { index: '21', name: 'Sasuke et Sarada' },
  { index: '22', name: 'Pensées communicantes' },
  { index: '23', name: 'La forme de leurs connexions' },
  { index: '24', name: 'Boruto et Sarada' },
  { index: '25', name: 'Une excursion scolaire turbulente !!' },
  { index: '26', name: 'Le successeur du Mizukage' },
  { index: '27', name: 'Le combat shinobi de l’amitié' },
  { index: '28', name: 'Déclaration de guerre' },
  { index: '29', name: 'Les sept nouveaux ninja épéistes' },
  { index: '30', name: 'Sharingan contre Kiba l’épée de la foudre' },
  { index: '31', name: 'Boruto et Kagura' },
  { index: '32', name: 'La quête de souvenirs' },
  { index: '33', name: 'Slump !! La fausse grosse caricature' },
  { index: '34', name: 'Nuit étoilée' },
  { index: '35', name: 'Réunion parents-professeurs-élèves…!' },
  { index: '36', name: 'L’examen de fin d’études démarre !!' },
  { index: '37', name: 'La résolution d’un Shinobi' },
  { index: '38', name: 'Formation, les cellules de trois hommes…?' },
  { index: '39', name: 'Le chemin illuminé par la pleine lune' },
  { index: '40', name: 'Team 7 : la première mission' },
  { index: '41', name: 'La force dans l’unité' },
  { index: '42', name: 'Le travail d’un ninja' },
  { index: '43', name: 'Le gang Byakuya fait surface !!' },
  { index: '44', name: 'Les doutes de Shikadai' },
  { index: '45', name: 'Mémoires du jour de neige' },
  { index: '46', name: 'Décision !! Stratégie de la nuit' },
  { index: '47', name: 'Le personnage que je veux être' },
  { index: '48', name: 'Le documentaire Genin !!' },
  { index: '49', name: 'Wasabi et Namida' },
  { index: '50', name: 'Examen Chunin – Réunion de recommandation' },
  { index: '51', name: 'L’anniversaire de Boruto' },
  { index: '52', name: 'L’ombre de Sasuke' },
  { index: '53', name: 'L’anniversaire d’Himawari' },
  { index: '54', name: 'Sasuke et Boruto' },
  { index: '55', name: 'Le ninja scientifique' },
  { index: '56', name: 'Rivaux, rassemblement !!' },
  { index: '57', name: 'La raison pour laquelle je ne peux pas perdre' },
  { index: '58', name: 'Le début du tournoi !!' },
  { index: '59', name: 'Boruto contre Shikadai' },
  { index: '60', name: 'La feuille cachée contre le sable caché' },
  { index: '61', name: 'L’utilisateur du sable de fer : Shinki' },
  { index: '62', name: 'Otsutsuki, invasion !!' },
  { index: '63', name: 'L’atout maître de Sasuke' },
  { index: '64', name: 'Naruto, sauvetage !!' },
  { index: '65', name: 'Père et fils' },
  { index: '66', name: 'Mon histoire…!!' },
  { index: '67', name: 'Super Chocho mode papillon !!' },
  { index: '68', name: 'Super Chocho mode bisou !!' },
  { index: '69', name: 'Super Chocho perturbation d’amour !!' },
  { index: '70', name: 'L’autre côté de la tension' },
  { index: '71', name: 'La pierre la plus dure du monde' },
  { index: '72', name: 'La volonté de Mitsuki' },
  { index: '73', name: 'L’autre côté de la Lune' },
  { index: '74', name: 'L’ennemi est Ino-Shika-Cho…!!' },
  { index: '75', name: 'Les épreuves de la cave Ryuchi' },
  { index: '76', name: 'Subir la colère' },
  { index: '77', name: 'Ennemi puissant, la bataille de Garaga !!' },
  { index: '78', name: 'Les spéculations de chacun' },
  { index: '79', name: 'On se retrouve, Mitsuki…!!' },
  { index: '80', name: 'L’ami de Mitsuki' },
  { index: '81', name: 'Le vœu de Boruto' },
  { index: '82', name: 'Infiltration !! Iwagakure' },
  { index: '83', name: 'La justice d’Onoki' },
  { index: '84', name: 'Les sentiments d’Onoki, les sentiments de Ku' },
  { index: '85', name: 'Cœur de pierre' },
  { index: '86', name: 'La volonté de Kozuchi' },
  { index: '87', name: 'La sensation d’être vivant' },
  { index: '88', name: 'Clash, Kokuyo !!' },
  { index: '89', name: 'Cœur pénétré' },
  { index: '90', name: 'Mitsuki et Sekiei' },
  { index: '91', name: 'La volonté d’Ohnoki' },
  { index: '92', name: 'Une nouvelle routine' },
  { index: '93', name: 'Journée parents-enfants' },
  { index: '94', name: 'Une aide précieuse !! Le concours des gros mangeurs' },
  { index: '95', name: 'Une grande stratégie avec sa fille' },
  { index: '96', name: 'Sang, sueur et larmes / Namida' },
  { index: '97', name: 'La décision de Shikadai' },
  { index: '98', name: 'La forêt maudite' },
  { index: '99', name: 'Jugo et le sortilège' },
  { index: '100', name: 'Le chemin décidé' },
  { index: '101', name: 'Le renfort de Jugo' },
  { index: '102', name: 'Mêlée !!' },
  { index: '103', name: 'Saison de migration' },
  { index: '104', name: 'Un petit colocataire' },
  { index: '105', name: 'Les cicatrices du cœur' },
  { index: '106', name: 'Rouleau ninja de fumée – Mission rang S !!' },
  {
    index: '107',
    name: 'Rouleau ninja de fumée – Bataille entre chien et chat !!',
  },
  { index: '108', name: 'Rouleau ninja de fumée – L’auberge fantôme !!' },
  { index: '109', name: 'Rouleau ninja de fumée – Chips et grand rocher !!' },
  {
    index: '110',
    name: 'Rouleau ninja de fumée – Bains thermaux revigorants !!',
  },
  { index: '111', name: 'Rouleau ninja de fumée – Le roi de Mirai !!' },
  { index: '112', name: 'La conférence des chefs de promotion Chunin' },
  { index: '113', name: 'Les caractéristiques d’un commandant' },
  { index: '114', name: 'La guerre par procuration de Gemaki !!' },
  { index: '115', name: 'Team 25' },
  { index: '116', name: 'Konohamaru et Lemon' },
  { index: '117', name: 'Le secret de Lemon' },
  { index: '118', name: 'Celui qui acquiert des souvenirs' },
  { index: '119', name: 'La voie du ninja de Konohamaru' },
  { index: '120', name: 'Avec Sasuke comme but' },
  { index: '121', name: 'Protéger le une-queue ! La mission confiée' },
  { index: '122', name: 'Bataille de poupées !!' },
  { index: '123', name: 'Urashiki, résurrection' },
  { index: '124', name: 'L’heure de la décision' },
  { index: '125', name: 'Boruto et Shinki' },
  { index: '126', name: 'Le plan de Shukaku' },
  { index: '127', name: 'Tactiques pour flirter' },
  { index: '128', name: 'La cible d’Urashiki' },
  { index: '129', name: 'Le village caché de la feuille' },
  { index: '130', name: 'Rassemblez-vous, Genin !!' },
  { index: '131', name: 'La force des neuf queues' },
  { index: '132', name: 'Le défi de Jiraiya' },
  { index: '133', name: 'Un village sans Sasuke' },
  { index: '134', name: 'Le pouvoir de lire le futur' },
  { index: '135', name: 'Bataille finale décisive, Urashiki' },
  { index: '136', name: 'Au-delà du temps !!' },
  { index: '137', name: 'L’étudiant étranger samouraï' },
  { index: '138', name: 'L’anniversaire de Hiashi' },
  { index: '139', name: 'Terreur ! Onikuma Enko' },
  {
    index: '140',
    name: 'Le jutsu de transfert d’âme qui a succombé aux chips',
  },
  { index: '141', name: 'La prison ninja : le château Hozuki' },
  { index: '142', name: 'Test de tripes' },
  { index: '143', name: 'Le criminel qui visait Kokuri' },
  { index: '144', name: 'Le secret de Kokuri' },
  { index: '145', name: 'Échapper à la prison du château Hozuki' },
  { index: '146', name: 'S’échapper, c’est parti !!' },
  { index: '147', name: 'Bataille sous la lune' },
  { index: '148', name: 'Une nouvelle mission !!' },
  { index: '149', name: 'Amis…!!' },
  { index: '150', name: 'La valeur d’une carte maîtresse cachée !!' },
  { index: '151', name: 'Boruto et Tento' },
  { index: '152', name: 'Éveil au Ninjutsu médical' },
  { index: '153', name: 'Une Harmonie en or' },
  { index: '154', name: 'Himawari, ninja en herbe !' },
  { index: '155', name: 'Mitsuki, un jour de pluie' },
  { index: '156', name: 'Je ne peux pas rester mince' },
  { index: '157', name: 'Les Traces de Kara' },
  { index: '158', name: 'Le Disparu' },
  { index: '159', name: 'Les Cellules de Hashirama' },
  { index: '160', name: 'Le Pays du Silence' },
  { index: '161', name: 'Le Château des cauchemars' },
  { index: '162', name: 'Sortir de la nasse' },
  { index: '163', name: 'Les Poursuivants' },
  { index: '164', name: 'La Technique interdite mortelle' },
  { index: '165', name: 'Le Devoir des quadruplés' },
  { index: '166', name: 'Combat à mort' },
  { index: '167', name: 'Leur Détermination à tous les deux' },
  { index: '168', name: 'L’Entraînement commence' },
  { index: '169', name: 'Mission conjointe avec Suna' },
  { index: '170', name: 'Un nouvel Orbe tourbillonan' },
  { index: '171', name: 'Les Résultats de l’entraînement' },
  { index: '172', name: 'L’Autographe de la peur' },
  { index: '173', name: 'Le Secret du sous-sol' },
  { index: '174', name: 'Renaissance de l’Arbre divin' },
  { index: '175', name: 'Au-delà des limites' },
  { index: '176', name: 'Fermez les portes A-N' },
  { index: '177', name: 'L’Infaillible Système de détection' },
  { index: '178', name: 'Le Dos du père' },
  { index: '179', name: 'La Machination de Victor' },
  { index: '180', name: 'Mugino l’assassin' },
  { index: '181', name: 'Le Réceptacle' },
  { index: '182', name: 'Ao' },
  { index: '183', name: 'Le Bras' },
  { index: '184', name: 'Les Marionnettes' },
  { index: '185', name: 'L’Outil' },
  { index: '186', name: 'L’Usage' },
  { index: '187', name: 'Kâma' },
  { index: '188', name: 'Le Réveil' },
  { index: '189', name: 'Résonnance' },
  { index: '190', name: 'Désertion' },
  { index: '191', name: 'Chien errant' },
  { index: '192', name: 'Le passé' },
  { index: '193', name: 'Sous le même toit' },
  { index: '194', name: 'La Famille Uzumaki' },
  { index: '195', name: 'Le Vase' },
  { index: '196', name: 'Un pouvoir qui relie' },
  { index: '197', name: 'Delta' },
  { index: '198', name: 'Monstres' },
  { index: '199', name: 'Surchargé' },
  { index: '200', name: 'Devenir un étudiant' },
  { index: '201', name: 'Larmes vides' },
  { index: '202', name: 'Une organisation religieuse' },
  { index: '203', name: 'Attaque surprise… !' },
  { index: '204', name: 'C’est une mauvaise nouvelle' },
  { index: '205', name: 'Preuve' },
  { index: '206', name: 'La nouvelle équipe sept' },
  { index: '207', name: 'Régénération' },
  { index: '208', name: 'Manifestation de Moshiki' },
  { index: '209', name: 'Le Paria' },
  { index: '210', name: 'Les indices de Kara' },
  { index: '211', name: 'La traque' },
  { index: '212', name: 'La défection d’Amado' },
  { index: '213', name: 'La véritable identité' },
  { index: '214', name: 'Un destin prédestiné' },
  { index: '215', name: 'Préparé' },
  { index: '216', name: 'Sacrifice' },
  { index: '217', name: 'Décision' },
  { index: '218', name: 'Partenaire' },
  { index: '219', name: 'Retour' },
  { index: '220', name: 'Temps restant' },
  { index: '221', name: 'Examen Chunin, encore une fois' },
  { index: '222', name: 'La veille de la bataille décisive' },
  { index: '223', name: 'Inojin vs : Houki' },
  { index: '224', name: 'La légende de Bakeneko' },
  { index: '225', name: 'L’épreuve de force des meilleurs amis' },
  { index: '226', name: 'Samouraï contre Kagaku' },
  { index: '227', name: 'La dernière mission de l’équipe 7 ? !' },
  { index: '228', name: 'Kawaki, la voie du Shinobi' },
  { index: '229', name: 'Violation de l’ordre' },
  { index: '230', name: 'Souhait' },
  { index: '231', name: 'Épée rouillée' },
  { index: '232', name: 'La première mission du capitaine Denki' },
  { index: '233', name: 'La nouvelle équipe 7, starting !' },
  { index: '234', name: 'Le méchant déchaîné' },
  { index: '235', name: 'Infiltrer l’île de Dotou' },
  { index: '236', name: 'Évasion' },
  { index: '237', name: 'Forteresse mobile' },
  { index: '238', name: 'Le bateau du tueur sanguinaire' },
  { index: '239', name: 'Le Garçon de l’île de la construction navale' },
  { index: '240', name: 'Le Rêve d’Ikada' },
  { index: '241', name: 'Le Secret d’Ikada' },
  { index: '242', name: 'Seiren' },
  { index: '243', name: 'Localisation' },
  { index: '244', name: 'Fissures' },
  { index: '245', name: 'La Hargnes de Funamushi' },
  { index: '246', name: 'Coup dur' },
  { index: '247', name: 'Pour Kagura' },
  { index: '248', name: 'Une bataille à mort, encore une fois' },
  { index: '249', name: 'Bourgeoins de haine' },
  { index: '250', name: 'Le sang de Funato' },
  { index: '251', name: 'Leurs deux résolutions' },
  { index: '252', name: 'Sentiments de croyance' },
  { index: '253', name: 'Des sentiments inconciliables' },
  { index: '254', name: 'Vortex de la vengeance' },
  { index: '255', name: 'Devoirs difficiles' },
  { index: '256', name: 'La meilleure recette' },
  { index: '257', name: 'Konohamaru devient l’Hokage ! ?' },
  { index: '258', name: 'Voyage aux sources chaudes de la famille Uzumaki' },
  { index: '259', name: 'Plaies non cicatrisées' },
  { index: '260', name: 'Feux d’artifice de l’amour' },
  { index: '261', name: 'Kawaki, entrée dans l’Académie !' },
  { index: '262', name: 'La fête du thé des princesses' },
  { index: '263', name: 'Ouverture de la fleur ! Le talent de l’enseignant' },
  { index: '264', name: 'L’expédition des Sept Merveilles s’est formée !' },
  {
    index: '265',
    name: 'Compétition par équipe, formation aux compétences pratiques !',
  },
  { index: '266', name: 'L’enlèvement d’Himawari' },
  { index: '267', name: 'Kawaki, identité révélée ?!' },
  { index: '268', name: 'Le festival des écoles ciblées' },
  { index: '269', name: 'Une ombre rampante' },
  { index: '270', name: 'Les deux faces d’une même pièce' },
  { index: '271', name: 'L’île de la trahison' },
  { index: '272', name: 'Les élèves font bloc !' },
  { index: '273', name: 'Adieu, l’Académie !' },
  { index: '274', name: 'Le faucon incapable de voler' },
  { index: '275', name: 'Vers le ciel à nouveau' },
  { index: '276', name: 'Bienvenue au Labyrinthe' },
  { index: '277', name: 'La vie qui disparaît' },
  { index: '278', name: 'Les Chaises musicales' },
  { index: '279', name: 'Les sept murs' },
  { index: '280', name: 'Percée' },
  { index: '281', name: 'La huitième vérité' },
  { index: '282', name: 'Le Roman de Sasuke – Infiltration' },
  { index: '283', name: 'Le Roman de Sasuke – Alignement d’étoiles' },
  { index: '284', name: 'Le Roman de Sasuke – Le Secret du sous-sol' },
  { index: '285', name: 'Le Roman de Sasuke – Le Ciel tombé sur terre' },
  { index: '286', name: 'Le Roman de Sasuke – L’anneau' },
  { index: '287', name: 'Les Marques de griffes' },
  { index: '288', name: 'Captif' },
  { index: '289', name: 'Le Statut' },
  { index: '290', name: 'La Présence' },
  { index: '291', name: 'Contrôle' },
  { index: '292', name: 'Envie' },
  { index: '293', name: 'Adieu' },
];
