export default [
  { index: '1', name: 'Et voici Naruto Uzumaki' },
  { index: '2', name: 'Je m’appelle Konohamaru' },
  { index: '3', name: 'Sasuke et Sakura : Amis ou Ennemis ?' },
  { index: '4', name: 'L’Épreuve de survie' },
  { index: '5', name: 'Recalés ?' },
  { index: '6', name: 'Au pays des vagues' },
  { index: '7', name: 'L’Assassin dans la brume' },
  { index: '8', name: 'La Promesse du sang' },
  { index: '9', name: 'Kakashi, le ninja copieur' },
  { index: '10', name: 'Le Chakra' },
  { index: '11', name: 'Il était une fois un héros' },
  { index: '12', name: 'Bataille sur le pont ! Le Retour de Zabuza' },
  { index: '13', name: 'Les Miroirs de glace de Haku' },
  { index: '14', name: 'Imprévisible Naruto !' },
  { index: '15', name: 'Bataille dans la brume' },
  { index: '16', name: 'Le Sceau brisé' },
  { index: '17', name: 'Le Passé oublié' },
  { index: '18', name: 'Un ninja, une arme' },
  { index: '19', name: 'La neige recouvre Zabuza' },
  { index: '20', name: 'L’Examen des chûnin' },
  { index: '21', name: 'De mystérieux et puissants adversaires !' },
  { index: '22', name: 'Sasuke contre Lee' },
  { index: '23', name: 'Les Rivaux !' },
  { index: '24', name: 'La Première Épreuve' },
  { index: '25', name: 'La Dixième Question' },
  { index: '26', name: 'Le Journal de l’école de Konoha' },
  { index: '27', name: 'La Seconde Épreuve ! Tout le monde est un ennemi' },
  { index: '28', name: 'Manger ou être mangé… Naruto joue les appâts !' },
  { index: '29', name: 'Naruto contre-attaque !' },
  { index: '30', name: 'Le Feu du dragon' },
  { index: '31', name: 'Le Combat pour l’amour' },
  { index: '32', name: 'Le Talent exceptionnel de Gaara' },
  { index: '33', name: 'Une formation imbattable ! Sanglier-Cerf-Papillon' },
  { index: '34', name: 'Le Pouvoir du Byakugan' },
  { index: '35', name: 'Interdit de regarder !' },
  { index: '36', name: 'Combat de clones' },
  { index: '37', name: 'Le Succès des neuf genins' },
  { index: '38', name: 'Les éliminatoires commencent' },
  { index: '39', name: 'Shishirendan ! La Fureur du lion' },
  { index: '40', name: 'Une confrontation explosive' },
  { index: '41', name: 'Le Combat des rivales' },
  { index: '42', name: 'Que le meilleur combat soit !' },
  { index: '43', name: 'Shikamaru le stratège' },
  { index: '44', name: 'Akamaru participe au combat' },
  { index: '45', name: 'L’Incroyable Atout de Naruto !' },
  { index: '46', name: 'Le Pouvoir de Lee' },
  { index: '47', name: 'Sous les yeux de celui que j’admire' },
  { index: '48', name: 'Le Pouvoir du Byakugan' },
  { index: '49', name: 'La Technique interdite' },
  { index: '50', name: 'Le Jeu de la mort' },
  { index: '51', name: 'Sasuke en danger !' },
  { index: '52', name: 'Le Retour d’Ebisu' },
  { index: '53', name: 'L’ermite est de retour' },
  { index: '54', name: 'La Technique d’invocation' },
  { index: '55', name: 'Un vœu fait à une fleur' },
  { index: '56', name: 'Une question de vie ou de mort' },
  { index: '57', name: 'Maître Crapaud entre en scène' },
  { index: '58', name: 'L’Histoire de Gaara' },
  { index: '59', name: 'L’épreuve finale commence' },
  { index: '60', name: 'Byakugan contre Multiclonage !' },
  { index: '61', name: 'La Défense absolue' },
  { index: '62', name: 'Le Pouvoir caché du raté' },
  {
    index: '63',
    name: 'Disqualifié ? Attention le grand tournoi est perturbé',
  },
  { index: '64', name: 'Un peu de nerf, Shikamaru !' },
  { index: '65', name: 'Mais où est-il ? Sasuke se fait attendre' },
  { index: '66', name: 'Celui qui déclenche une tempête' },
  { index: '67', name: 'Les Leçons du maître' },
  { index: '68', name: 'Offensive sur Konoha !' },
  { index: '69', name: 'Enfin ! Une mission de rang A' },
  { index: '70', name: 'L’Embuscade de Shikamaru' },
  { index: '71', name: 'Le Combat des Hokage' },
  { index: '72', name: 'L’Erreur du Hokage' },
  { index: '73', name: 'Le Sceau du démon' },
  { index: '74', name: 'La Vraie Nature de Gaara' },
  { index: '75', name: 'La Détermination de Sasuke' },
  { index: '76', name: 'L’Assassin du clair de lune' },
  { index: '77', name: 'Son nom est Gaara' },
  { index: '78', name: 'Naruto sort le grand jeu' },
  { index: '79', name: 'Le Coup final' },
  { index: '80', name: 'Konoha pleure le 3e Hokage' },
  { index: '81', name: 'Retour au pays' },
  { index: '82', name: 'Sharingan contre Sharingan' },
  { index: '83', name: 'Naruto et Jiraya… Sources de problèmes' },
  { index: '84', name: 'Le Cri des Mille Oiseaux' },
  { index: '85', name: 'La Malédiction du clan Uchiwa' },
  { index: '86', name: 'L’entraînement commence' },
  { index: '87', name: 'Naruto et le ballon d’eau' },
  { index: '88', name: 'Vers la concentration ultime' },
  { index: '89', name: 'Ondulation' },
  { index: '90', name: 'Explosion de colère !' },
  { index: '91', name: 'Le Pendentif maudit' },
  { index: '92', name: 'La Réponse de Tsunade' },
  { index: '93', name: 'Les négociations sont interrompues' },
  { index: '94', name: 'Rasengan !' },
  { index: '95', name: 'Le 5e Hokage' },
  { index: '96', name: 'Bataille sur 3 fronts' },
  { index: '97', name: 'Naruto aux sources thermales' },
  { index: '98', name: 'Le Diagnostic de Tsunade' },
  { index: '99', name: 'L’Héritier' },
  { index: '100', name: 'La Détermination de Lee' },
  { index: '101', name: 'Bas le masque, Kakashi sensei !' },
  { index: '102', name: 'Mission au pays du Thé' },
  { index: '103', name: 'La Grande Course de Todoroki' },
  { index: '104', name: 'Orages sur Nagi' },
  { index: '105', name: 'Juste avant l’arrivée ! La bataille fait rage…' },
  { index: '106', name: 'La Dernière Ligne droite pour Idate' },
  { index: '107', name: 'Sasuke contre Naruto' },
  { index: '108', name: 'Une cassure invisible' },
  { index: '109', name: 'L’Invitation du Son' },
  { index: '110', name: 'Les Cinq de Konoha + Un' },
  { index: '111', name: 'Le Pouvoir des quatre ninjas d’Oto' },
  { index: '112', name: 'La tension monte dans l’équipe de Shikamaru' },
  { index: '113', name: 'Chôji se déchaîne !' },
  { index: '114', name: 'Adieu l’ami, je ne t’oublierai jamais' },
  { index: '115', name: 'C’est moi ton adversaire' },
  { index: '116', name: 'L’Angle mort du Byakugan' },
  { index: '117', name: 'Neji, sa raison de ne pas perdre' },
  { index: '118', name: 'Récupérer le tonneau !' },
  { index: '119', name: 'Un nouvel ennemi !' },
  { index: '120', name: 'Hurlez ! Aboyez ! L’Équipe ultime' },
  { index: '121', name: 'Chacun son combat' },
  { index: '122', name: 'Shikamaru joue le tout pour le tout' },
  { index: '123', name: 'Arrivée du fauve de jade de Konoha' },
  { index: '124', name: 'L’Explosion du fauve de jade !' },
  { index: '125', name: 'Les Ninjas de Suna' },
  { index: '126', name: 'Gaara contre Kimimaro' },
  { index: '127', name: 'Une attaque implacable !' },
  { index: '128', name: 'Un cri égaré !' },
  { index: '129', name: 'Itachi et Sasuke, le destin des deux frères' },
  { index: '130', name: 'Père et fils, le blason brisé' },
  { index: '131', name: 'Le Secret du kaléidoscope hypnotique du Sharingan' },
  { index: '132', name: 'Mon ami' },
  { index: '133', name: 'Le Cri des larmes, tu es mon ami' },
  { index: '134', name: 'Conclusion sous une pluie de larmes' },
  { index: '135', name: 'Une promesse non tenue' },
  { index: '136', name: 'Enfin une mission de rang S !' },
  { index: '137', name: 'L’Ombre du clan Fûma' },
  { index: '138', name: 'Pureté et trahison, un rêve éphémère' },
  { index: '139', name: 'Horreur ! Le Palais d’Orochimaru' },
  { index: '140', name: 'Le Piège de Kabuto' },
  { index: '141', name: 'La Décision de Sakura' },
  { index: '142', name: 'Un trio diabolique' },
  { index: '143', name: 'Je compte sur ton groin' },
  { index: '144', name: 'Le Nouveau Trio' },
  { index: '145', name: 'Ino, Shika, Chô… La Nouvelle Formation !' },
  { index: '146', name: 'Des ambitions brisées !' },
  { index: '147', name: 'Duel fatidique !' },
  { index: '148', name: 'À la recherche des insectes flaireurs' },
  { index: '149', name: 'Tous les insectes se ressemblent' },
  { index: '150', name: 'La Grande Bataille des insectes' },
  { index: '151', name: 'Enflamme-toi Byakugan !' },
  { index: '152', name: 'Requiem pour les vivants' },
  { index: '153', name: 'Que les poings de l’amour atteignent ton cœur' },
  { index: '154', name: 'L’Ennemi naturel du Byakugan' },
  { index: '155', name: 'Des nuages noirs en approche' },
  { index: '156', name: 'La Vengeance de Raïga' },
  { index: '157', name: 'Cours !! C’est le curry de la vie !' },
  { index: '158', name: 'L’Esprit d’équipe' },
  { index: '159', name: 'Ami ou Ennemi ? Le Chasseur de primes du désert' },
  { index: '160', name: 'La Bataille du temple d’Okay' },
  { index: '161', name: 'D’étranges visiteurs' },
  { index: '162', name: 'Le Guerrier maudit blanc' },
  { index: '163', name: 'Les Arrangements de Kômei, le stratège' },
  { index: '164', name: 'Les renforts arrivent trop tard' },
  { index: '165', name: 'La Mort de Naruto' },
  { index: '166', name: 'La Page perdue' },
  { index: '167', name: 'Le Temps du vol des oiseaux blancs' },
  {
    index: '168',
    name: 'Brûlons les graisses ! Mélangeons, étirons, et à la cuisson !',
  },
  { index: '169', name: 'La Page perdue' },
  { index: '170', name: 'Le Mystère du Kaima' },
  { index: '171', name: 'Intrusion ! Le piège se referme !' },
  { index: '172', name: 'Désespoir… Le Cœur lacéré' },
  { index: '173', name: 'Bataille en mer, le pouvoir libéré' },
  { index: '174', name: 'Naruto ! Moi aussi, je suis un ninja !' },
  { index: '175', name: 'Creuse, baisse-toi et trouve le trésor !' },
  { index: '176', name: 'Une grande partie de chasse à l’homme !' },
  { index: '177', name: 'Oh ?! S’il vous plaît, monsieur le facteur !' },
  { index: '178', name: 'Le Garçon au nom d’étoile' },
  { index: '179', name: 'Étoile d’été, souvenir d’une berceuse' },
  { index: '180', name: 'L’Adresse du paon dédommagé' },
  { index: '181', name: 'Hoshikage, la vérité cachée' },
  { index: '182', name: 'Les Retrouvailles' },
  { index: '183', name: 'L’Éclat de l’étoile' },
  { index: '184', name: 'Une longue journée pour Kiba Inuzuka' },
  { index: '185', name: 'Onboo, le nouveau compagnon de Naruto !' },
  { index: '186', name: 'Shino délire' },
  { index: '187', name: 'Les Déménageurs de Konoha' },
  { index: '188', name: 'Les Marchands ambulants poursuivis !' },
  { index: '189', name: 'Combats impitoyables' },
  { index: '190', name: 'Le Point faible de l’homme magnétique !' },
  { index: '191', name: 'La Grande Fuite de Naruto !' },
  { index: '192', name: 'Le Paradis des joufflus' },
  { index: '193', name: 'Le Château fantôme…' },
  { index: '194', name: 'Le Château fantôme…' },
  { index: '195', name: 'La Troisième Grande Bête, l’ultime rival' },
  { index: '196', name: 'Les Larmes du combat !' },
  { index: '197', name: 'Rassemblement des onze de Konoha !' },
  { index: '198', name: 'La Mémoire de Naruto' },
  { index: '199', name: 'Loupé ! La cible apparaît dans la ligne de mire' },
  { index: '200', name: 'En service actif !' },
  {
    index: '201',
    name: 'Pièges en série ! Compte à rebours vers l’anéantissement.',
  },
  { index: '202', name: 'Le Top 5 des duels les plus populaires !' },
  { index: '203', name: 'La Décision de Kurenaï' },
  { index: '204', name: 'Yakumo poursuivie' },
  { index: '205', name: 'La Mission secrète de Kurenaï' },
  { index: '206', name: 'Une illusion ou la réalité ?' },
  { index: '207', name: 'Le Pouvoir supposé renfermé' },
  { index: '208', name: 'L’Objet d’art rare' },
  { index: '209', name: 'Les ennemis sont les Shinobazu !' },
  { index: '210', name: 'La Forêt de l’illusion' },
  { index: '211', name: 'Souvenirs dans le feu' },
  { index: '212', name: 'Chacun son chemin !' },
  { index: '213', name: 'La Mémoire perdue' },
  { index: '214', name: 'La Vérité retrouvée' },
  { index: '215', name: 'Une mémoire rejetée' },
  { index: '216', name: 'Le Maître disparu' },
  { index: '217', name: 'L’Alliance avec Suna' },
  { index: '218', name: 'La Contre-attaque de Suiko' },
  { index: '219', name: 'L’Arme ultime ressuscitée' },
  { index: '220', name: 'Départ en voyage' },
];
