const names = [
  { name: "Tigre et Dragon", index: "1" },
  { name: "Ryuuji et Taiga", index: "2" },
  { name: "Ta chanson", index: "3" },
  { name: "L'expression de cet instant", index: "4" },
  { name: "Kawashima Ami", index: "5" },
  { name: "Vraie personnalité", index: "6" },
  { name: "Ouverture de la piscine", index: "7" },
  { name: "Pour le bien de qui ?", index: "8" },
  { name: "Tu dois aller à la mer", index: "9" },
  { name: "Feu d'artifice", index: "10" },
  { name: "Festival culturel du lycée Oohashi (1)", index: "11" },
  { name: "Festival culturel du lycée Oohashi (2)", index: "12" },
  { name: "Festival culturel du lycée Oohashi (3)", index: "13" },
  { name: "Taiga, le Tigre de poche du Bonheur", index: "14" },
  { name: "Les Etoiles Lointaines", index: "15" },
  { name: "Un pas en Avant", index: "16" },
  { name: "Mercure rétrograde à Noël", index: "17" },
  { name: "Sous le Sapin", index: "18" },
  { name: "Fête de Noël", index: "19" },
  { name: "Comme ça pour toujours", index: "20" },
  { name: "Quoi qu'il arrive", index: "21" },
  { name: "La Scène avec toi", index: "22" },
  { name: "Le Chemin que nous devons emprunter", index: "23" },
  { name: "Confession", index: "24" },
  { name: "Toradora!", index: "25" },
  { name: "Le secret du bento", index: "26" },
];

export default names;
