const names = [
  { name: "L'Adieu aux beaux jours", index: "1" },
  { name: "Les Ombres", index: "2" },
  { name: "Échoué sur le rivage", index: "3" },
  { name: "Du jamais vu", index: "4" },
  { name: "Le Maelstrom", index: "5" },
  { name: "Résonance orbitale", index: "6" },
  { name: "Ennemi mortel", index: "7" },
  { name: "Souvenirs", index: "8" },
  { name: "Coulent mes larmes", index: "9" },
  { name: "Dans les ténèbres", index: "10" },
  { name: "L'heure du dîner", index: "11" },
  { name: "Nuit sanglante", index: "12" },
  { name: "Amis", index: "13" },
  { name: "Être ; Ne pas être", index: "14" },
  { name: "Lumières caméra action", index: "15" },
  { name: "Original", index: "16" },
  { name: "Détermination", index: "17" },
  { name: "Face à face", index: "18" },
  { name: "La noirceur de la Boue", index: "19" },
  { name: "Tout est perdu (ou pas)", index: "20" },
  { name: "Le jour le plus long de Shinpei Ajiro", index: "21" },
  { name: "Le Retour", index: "22" },
  { name: "La Nuit sans fin", index: "23" },
  { name: "L'appel d'Hiruko", index: "24" },
  { name: "Je suis rentré", index: "25" },
];

export default names;
