const names = [
  { name: "La Nuit des vampires", index: "1" },
  { name: "La Mémoire du sang", index: "2" },
  { name: "Les Crocs de la confession", index: "3" },
  { name: "Condamnation", index: "4" },
  { name: "Banquet au clair de lune", index: "5" },
  { name: "Leur choix", index: "6" },
  { name: "Le Labyrinthe rouge écarlate", index: "7" },
  { name: "Lamentations", index: "8" },
  { name: "Les Yeux rouges vifs", index: "9" },
  { name: "La Princesse des ténèbres", index: "10" },
  { name: "Le Marché de l'espoir", index: "11" },
  { name: "Le Serment des sang-pur", index: "12" },
  { name: "La Chaine rouge profond", index: "13" },
  { name: "Pécheurs du destin ~Guilty~", index: "14" },
  { name: "Promesse éternelle ~Paradoxe~", index: "15" },
  { name: "Le Portrait du Lapis-Lazuli ~Mirage~", index: "16" },
  { name: "L'Éveil du démon ~Libido~", index: "17" },
  { name: "Le Piège du subalterne ~Stratagème~", index: "18" },
  { name: "Faux Amants ~Lovers~", index: "19" },
  { name: "Le Baiser embarrassant ~Kiss~", index: "20" },
  { name: "La Spirale des souvenirs ~Mémoire~", index: "21" },
  { name: "La Résurrection du souverain dément ~Emperor~", index: "22" },
  { name: "Prélude à la bataille ~Prélude~", index: "23" },
  { name: "Nos deux vies ~Soul~", index: "24" },
  { name: "La Fin du monde ~Period~", index: "25" },
  { name: "Le Chevalier vampire ~Knight~", index: "26" },
];

export default names;
