const names = [
  { name: "J'ai recueilli le diable", index: "1" },
  { name: "Le bébé démon aux commandes", index: "2" },
  { name: "N'y a-t-il personne de fort et de violent ?", index: "3" },
  {
    name: "L'incontinence du diable une seconde avant le désastre",
    index: "4",
  },
  { name: "Il n'y a rien que l'argent ne puisse acheter", index: "5" },
  { name: "Le jouet venu des enfers", index: "6" },
  { name: "Première expérience au parc", index: "7" },
  { name: "Nouvelle rencontre", index: "8" },
  { name: "L'amour est un ouragan", index: "9" },
  { name: "Le disciple", index: "10" },
  {
    name: "Il y a bien quelque chose que l'argent ne pouvait acheter",
    index: "11",
  },
  { name: "Je t'empêcherai de dormir !", index: "12" },
  { name: "Examen d'évaluation", index: "13" },
  { name: "Quelqu'un connaît-il des coups spéciaux ?", index: "14" },
  { name: "Les racailles en maillot", index: "15" },
  { name: "Tu n'es pas mal pour un homme !", index: "16" },
  { name: "Les devoirs de vacances des enfers", index: "17" },
  { name: "Je ne combats plus avec un bébé à bord", index: "18" },
  { name: "Voilà le docteur", index: "19" },
  { name: "Rassemblement", index: "20" },
  { name: "Qui est le plus fort d'Ishiyama ?", index: "21" },
  { name: "Retraite à la montagne", index: "22" },
  { name: "Irrémédiable ?", index: "23" },
  { name: "Me voici, monde formidable", index: "24" },
  { name: "Un nouveau trimestre commence", index: "25" },
  { name: "Appelle-moi frangin", index: "26" },
  { name: "On l'appelle Magicienne", index: "27" },
  { name: "Prenons nos mesures", index: "28" },
  { name: "C'est quoi, les six Chevaliers Saints ?", index: "29" },
  { name: "Qui sont les six Chevaliers ?", index: "30" },
  { name: "Aucune conclusion n'a été atteinte !", index: "31" },
  { name: "Qu'est-il arrivé à la nouvelle élève ?", index: "32" },
  { name: "La blessure du passé", index: "33" },
  { name: "Désolé pour le dérangement", index: "34" },
  { name: "C'est l'heure du match", index: "35" },
  { name: "Comptes enfin réglés", index: "36" },
  { name: "Il était professeur", index: "37" },
  { name: "Dispute entre frères", index: "38" },
  { name: "Le grand frère était un pleurnichard", index: "39" },
  { name: "De nouveaux venus guère bienvenus", index: "40" },
  { name: "Situation désespérée. Que fait-on ?", index: "41" },
  { name: "C'est l'heure de l'entraînement", index: "42" },
  { name: "Où est passé son frère ?", index: "43" },
  { name: "Il faut devenir plus fort", index: "44" },
  { name: "Les jeux vidéo, c'est une heure par jour maximum", index: "45" },
  { name: "Enflamme-toi ! Super transformation !", index: "46" },
  { name: "Désolée d'avoir été si longue", index: "47" },
  { name: "Je suis son père", index: "48" },
  {
    name: "Spécial nouvel an ! Beel Beel ou le voyage en Occident",
    index: "49",
  },
  { name: "Aujourd'hui le contenu est un peu différent", index: "50" },
  { name: "Le chien de garde regarde", index: "51" },
  { name: "Et les racailles disparurent", index: "52" },
  {
    name: "La première conquête de Baby Beel / Furuichi tombe amoureux",
    index: "53",
  },
  { name: "Black Beel a grandi", index: "54" },
  { name: "J'ai perdu ma banane / Le démon suprême en visite", index: "55" },
  {
    name: "Es-tu un traître ? / Est-ce un moment pour un homme...",
    index: "56",
  },
  {
    name: "Tu veux un manjû ? / Tu ne veux pas aller dans un bain mixte ?",
    index: "57",
  },
  { name: "L'institut D.Daimont ouvre ses portes", index: "58" },
  { name: "Nous sommes les plus forts", index: "59" },
  { name: "Ce n'est pas un adieu", index: "60" },
];

export default names;
