const names = [
  { name: "LE DÉPART DU GARÇON", index: "1" },
  { name: "UNE FORCE INCONNUE", index: "2" },
  { name: "LES QUATRE CAVALIERS DE L'APOCALYPSE", index: "3" },
  { name: "LE DÉMON DU RAVIN DE L'ÉCHO", index: "4" },
  { name: "UNE DÉTERMINATION QUI SE RENFORCE", index: "5" },
  { name: "SISTANA ÉBRANLÉE", index: "6" },
  { name: "LE NOM DE LA MAGIE", index: "7" },
  { name: "DE JEUNES HÉROS", index: "8" },
  { name: "MAÎTRE ET ÉLÈVE", index: "9" },
  { name: "LE RUGISSEMENT DE LA DESTRUCTION", index: "10" },
  { name: "UN VRAI CHEVALIER SACRÉ", index: "11" },
  { name: "UNE SINISTRE ENTREPRISE", index: "12" },
  { name: "PRIS AU PIÈGE", index: "13" },
  { name: "LE BÉLIER DE LA LUXURE", index: "14" },
  { name: "LES TALISMANS OBSCURS", index: "15" },
  { name: "LE DÉPART DE SIN", index: "16" },
  { name: "LE ROI DE LIONES", index: "17" },
  { name: "LA RENCONTRE DES CHEVALIERS DE LA PROPHÉTIE", index: "18" },
  { name: "LIONES EN FLAMMES", index: "19" },
  { name: "DOMPTER UN CHEVAL SAUVAGE", index: "20" },
  { name: "LES QUATRE CHEVALIERS CONTRE LES SERVITEURS DU CHAOS", index: "21" },
  { name: "DES COEURS BRÛLANTS ET GELÉS", index: "22" },
  { name: "LES CHEVALIERS SACRÉS ROYAUX CONTRE MELA-GALLAND", index: "23" },
  { name: "L'AVÈNEMENT", index: "24" },
  { name: "Autorité royale", index: "25" },
  { name: "Séparation", index: "26" },
];

export default names;
