const names = [
  { name: "Je suis Kuroko", index: "1" },
  { name: "Je suis très sérieux", index: "2" },
  { name: "C'est mieux si je ne peux pas gagner.", index: "3" },
  { name: "Prend garde à la contre-attaque !", index: "4" },
  { name: "Ton style de basket", index: "5" },
  { name: "Laisse-moi te dire deux choses", index: "6" },
  { name: "Vous allez voir quelque chose d'incroyables", index: "7" },
  { name: "Maintenant que j'y pense", index: "8" },
  { name: "Pour gagner.", index: "9" },
  { name: "Je ne veux pas l'avoir", index: "10" },
  { name: "Il ne s'agit pas de ça !", index: "11" },
  { name: '"La victoire", pour toi, c\'est quoi ?', index: "12" },
  { name: "J'y croyais", index: "13" },
  { name: "Comme deux gouttes d'eau", index: "14" },
  { name: "Laisse-moi rire", index: "15" },
  { name: "Quand faut y aller...", index: "16" },
  { name: "Un ramassis de tarés", index: "17" },
  { name: "Abandonner, ça jamais !", index: "18" },
  { name: "Vers de nouveaux défis", index: "19" },
  { name: "On dit pas « je veux » !", index: "20" },
  { name: "C'est parti !", index: "21" },
  { name: "Même si ça doit me prendre toute une vie", index: "22" },
  { name: "Immature !", index: "23" },
  { name: "Arrêtez de vous faire des films !", index: "24" },
  { name: "Mon basket et le tien", index: "25" },
  { name: "Une rencontre inattendue", index: "26" },
  { name: "Rendez-vous à la Winter Cup !", index: "27" },
  { name: "Renaissance !", index: "28" },
  { name: "Une seule réponse possible", index: "29" },
  { name: "On t'attendait", index: "30" },
  { name: "Il y a un moment que je les ai dépassées", index: "31" },
  { name: "Abandonne !", index: "32" },
  { name: "Le Club de basket-ball du lycée Seirin !", index: "33" },
  { name: "Je vais te battre !", index: "34" },
  { name: "Confiance !", index: "35" },
  { name: "Ras-le-bol !", index: "36" },
  { name: "On compte sur votre indulgence", index: "37" },
  { name: "Je te le jure", index: "38" },
  { name: "Vains efforts", index: "39" },
  { name: "Grisé", index: "40" },
  { name: "On va gagner ici et maintenant !", index: "41" },
  { name: "On remet ça ?", index: "41.5" },
  { name: "On croit tous en lui", index: "42" },
  { name: "Je perdrai pas", index: "43" },
  { name: "Apprends-moi", index: "44" },
  { name: "Comment voulez-vous que ce soit simple ?", index: "45" },
  { name: "Nos premiers points !", index: "46" },
  { name: "Mon choix est fait !", index: "47" },
  { name: "Je refuse de perdre", index: "48" },
  { name: "J'en ai marre", index: "49" },
  { name: "On va gagner !", index: "50" },
  { name: "Je joue à fond, c'est tout", index: "51" },
  { name: "C'est à moi", index: "52" },
  { name: "Dégage de ma route !", index: "53" },
  { name: "Je les prends !", index: "54" },
  { name: "Je n'en connais pas !", index: "55" },
  { name: "Je vous les offrirai !", index: "56" },
  { name: "J'en rirais presque !", index: "57" },
  { name: "La véritable lumière", index: "58" },
  { name: "Ne nous sous-estimez-pas !", index: "59" },
  { name: "Pour la victoire !", index: "60" },
  { name: "Cette fois sera la bonne !", index: "61" },
  { name: "S'il y a un joueur ultime...", index: "62" },
  { name: "Un jour de ciel bleu", index: "63" },
  { name: "Désolé...", index: "64" },
  { name: "C'est fini...", index: "65" },
  { name: "Qu'est-ce que la victoire ?", index: "66" },
  { name: "L'ultime Tip-Off !", index: "67" },
  { name: "On ne peut pas rêver mieux, non ?", index: "68" },
  { name: "Il n'y aura pas de miracle", index: "69" },
  { name: "La volonté d'être une ombre", index: "70" },
  { name: "Je suis au taquet, là !", index: "71" },
  { name: "Ceci est un avertissement", index: "72" },
  { name: "Pourquoi ne pas laisser tomber ?", index: "73" },
  { name: "C'était donc toi ?", index: "74" },
  { name: "Autant de fois que tu voudras", index: "75" },
];

export default names;
