const names = [
  { index: "1", name: "Le jour où je suis devenu un Shinigami" },
  { index: "2", name: "Le Travail d’un Shinigami" },
  {
    index: "3",
    name: "Le Souhait du grand frère, le souhait de la petite sœur",
  },
  { index: "4", name: "Perroquet maudit" },
  { index: "5", name: "Bats l’ennemi invisible" },
  { index: "6", name: "Combat à mort : Ichigo contre Ichigo !" },
  { index: "7", name: "Salutations d’un garçon rembourré" },
  { index: "8", name: "17 juin, un souvenir de pluie" },
  { index: "9", name: "Ennemi imbattable" },
  { index: "10", name: "Attaque pendant le voyage en terre sacrée" },
  { index: "11", name: "Le Légendaire Quincy" },
  { index: "12", name: "Un doux bras droit" },
  { index: "13", name: "Fleur et Hollow" },
  { index: "14", name: "Retour en arrière, combat à mort !" },
  { index: "15", name: "Le Fameux Plan de Kon" },
  { index: "16", name: "Rencontre : Abarai Renji" },
  { index: "17", name: "Ichigo meurt !" },
  { index: "18", name: "Réclamation : La Puissance du Shinigami" },
  { index: "19", name: "Ichigo devient un Hollow" },
  { index: "20", name: "L’Ombre d’Ichimaru Gin" },
  { index: "21", name: "Entrez ! Le Monde des Shinigamis" },
  { index: "22", name: "L’homme qui déteste les Shinigamis" },
  { index: "23", name: "La Condamnation de Rukia avant le quatorzième jour" },
  { index: "24", name: "Rassemblement ! Les Treize Divisions" },
  { index: "25", name: "Pénétrer au centre d’une énorme bombe" },
  { index: "26", name: "Formation ! Le Plus Mauvais Grade" },
  { index: "27", name: "Lancer le coup de la mort" },
  { index: "28", name: "Orihime est prise pour cible" },
  { index: "29", name: "Percée ! Encerclé par le filet des Shinigamis" },
  { index: "30", name: "Le Combat de Renji" },
  { index: "31", name: "Résolu à tuer" },
  { index: "32", name: "Une étoile et un chien perdu" },
  { index: "33", name: "Miracle ! Le Mystérieux Nouveau Héros" },
  { index: "34", name: "Tragédie de l’aube" },
  { index: "35", name: "Meurtre d’Aizen ! L’obscurité qui approche" },
  { index: "36", name: "Zaraki Kenpachi approche !" },
  { index: "37", name: "La Raison du poing" },
  { index: "38", name: "Désespoir ! Zangetsu brisé" },
  { index: "39", name: "L’Homme de l’immortalité" },
  { index: "40", name: "Le Shinigami que Ganju a rencontré" },
  { index: "41", name: "Réunion : Ichigo et Rukia" },
  { index: "42", name: "Yoruichi, maître de la vitesse, danse !" },
  { index: "43", name: "Le Méprisable Shinigami" },
  { index: "44", name: "Ishida, les limites du pouvoir !" },
  { index: "45", name: "Surpasser les limites" },
  { index: "46", name: "Les Archives authentiques ! L’École des Shinigamis" },
  { index: "47", name: "Les Vengeurs" },
  { index: "48", name: "Hitsugaya hurle !" },
  { index: "49", name: "Le Cauchemar de Rukia" },
  { index: "50", name: "L’Éveil du lion" },
  { index: "51", name: "Le Jour du jugement" },
  {
    index: "52",
    name: "Renji, le serment de l’âme ! Rencontre mortelle avec Byakuya",
  },
  {
    index: "53",
    name: "La Tentation d’Ichimaru Gin. La Résolution de destruction",
  },
  { index: "54", name: "Un serment accompli ! Récupérer Rukia !" },
  {
    index: "55",
    name: "Le Shinigami le plus fort ! L’Ultime Confrontation entre maître et élève",
  },
  {
    index: "56",
    name: "Bataille supersonique ! Déterminer la déesse de la chevalerie !",
  },
  {
    index: "57",
    name: "Mille fleurs de cerisier écrasées ! Zangetsu passe à travers le ciel",
  },
  { index: "58", name: "Décachetez ! La Lame noire, la puissance miraculeuse" },
  {
    index: "59",
    name: "Conclusion du match mortel. Fierté blanche et désir noir",
  },
  {
    index: "60",
    name: "Réalité du désespoir, le poignard de l’assassin est brandi",
  },
  { index: "61", name: "Aizen vivant ! Horribles ambitions" },
  {
    index: "62",
    name: "Rassemblement ! La Plus Forte Organisation de Shinigamis",
  },
  { index: "63", name: "La Décision de Rukia, les sentiments d’Ichigo" },
  {
    index: "64",
    name: "Nouveau Trimestre scolaire. Renji arrive au monde des humains ?!",
  },
  { index: "65", name: "Terreur rampante. La Seconde Victime" },
  {
    index: "66",
    name: "Passons à travers ! Le Piège caché dans le labyrinthe",
  },
  { index: "67", name: "Jeu mortel ! Le Camarade manquant" },
  {
    index: "68",
    name: "La Véritable Identité du diable. Le secret qui est révélé",
  },
  { index: "69", name: "Bounts ! Les Chasseurs d’âmes !" },
  {
    index: "70",
    name: "Le Retour de Rukia ! La Renaissance de l’équipe de remplacement",
  },
  {
    index: "71",
    name: "Le Moment de la collision ! Une mauvaise main se profile près du Quincy !",
  },
  { index: "72", name: "Assaut de l’eau ! Évasion de l’hôpital fermé" },
  {
    index: "73",
    name: "Rassemblement à la Place de Fortune ! L’homme qui fait son mouvement !",
  },
  { index: "74", name: "Mémoires d’un clan éternellement vivant" },
  {
    index: "75",
    name: "Évènement bouleversant pour la 11e Division ! Le Shinigami qui sort de l’oubli",
  },
  { index: "76", name: "Explosion de force ! Freed contre Zangetsu !" },
  {
    index: "77",
    name: "Disparition de la rancune ! Le Shinigami que Kenpachi a tué !",
  },
  {
    index: "78",
    name: "Surprenantes révélations pour les treize Divisions ! La Vérité cachée dans l’histoire",
  },
  { index: "79", name: "La Décision de mourir de Yoshino" },
  {
    index: "80",
    name: "Assaut d’un incroyable ennemi ! Une minuscule dernière ligne de défense !",
  },
  { index: "81", name: "Hitsugaya réagit ! La Ville attaquée" },
  {
    index: "82",
    name: "Ichigo contre Daruku ! Arrivée progressive de l’obscurité",
  },
  { index: "83", name: "L’Ombre grise. Le Secret des poupées" },
  {
    index: "84",
    name: "Rupture dans l’équipe de remplacement ?! La Trahison de Rukia",
  },
  { index: "85", name: "Le Combat des larmes ! Rukia contre Orihime !" },
  { index: "86", name: "Rangiku danse ! Tranche l’ennemi invisible" },
  {
    index: "87",
    name: "Byakuya convoqué ! Les treize Divisions s’organisent !",
  },
  {
    index: "88",
    name: "Annihilation des lieutenants ?! Piège dans la caverne souterraine",
  },
  { index: "89", name: "Revanche ?! Ishida contre Nemu !" },
  { index: "90", name: "Abarai Renji, l’âme du Bankai !" },
  { index: "91", name: "Shinigami et Quincy, les pouvoirs retrouvés !" },
  { index: "92", name: "De retour dans le monde des Shinigami !" },
  {
    index: "93",
    name: "L’Assaut des Bounts ! Chaos dans les treize Divisions",
  },
  {
    index: "94",
    name: "La Décision de Hitsugaya ! L’heure de la confrontation approche",
  },
  {
    index: "95",
    name: "Byakuya dans la bataille ! La danse des fleurs de cerisiers qui déchire le vent",
  },
  {
    index: "96",
    name: "Ichigo, Byakuya, Kariya, le combat des trois extrêmes !",
  },
  {
    index: "97",
    name: "Hitsugaya passe à l’attaque ! Abattre les ennemis dans la forêt",
  },
  { index: "98", name: "Clash ! Zaraki Kenpachi contre Ichinose Maki !" },
  { index: "99", name: "Shinigami contre Shinigami ! Une puissance écrasante" },
  { index: "100", name: "Soi Fon meurt ?! La Dernière Unité mobile secrète" },
  { index: "101", name: "Le Bankai de Mayuri ! Sawatari, le clash des démons" },
  { index: "102", name: "Le Dernier Quincy ! L’Explosion du pouvoir" },
  { index: "103", name: "Ishida, les limites repoussées pour attaquer !" },
  { index: "104", name: "La Lutte de la 10e Division ! L’Éveil de Hyôrinmaru" },
  { index: "105", name: "Kariya ! Le Compte à rebours de l’explosion" },
  { index: "106", name: "Vie et Vengeance ! Ishida, l’ultime décision" },
  { index: "107", name: "L’Épée de la furie ! Le Moment de la destruction" },
  { index: "108", name: "La Lamentation du Bount ! La Confrontation finale" },
  { index: "109", name: "Ichigo et Rukia, pensées reflétées dans le ciel" },
  {
    index: "110",
    name: "Les affaires reprennent ! L’étudiant qui fout les chocottes",
  },
  { index: "111", name: "Le Choc ! La Vraie Apparence du père" },
  { index: "112", name: "Vizards et Arrancars" },
  {
    index: "113",
    name: "Le Prélude à l’apocalypse. L’Offensive des Arrancars !",
  },
  { index: "114", name: "Réunion : Ichigo, Rukia et les Shinigamis" },
  { index: "115", name: "Mission ! Les Shinigamis qui sont arrivés" },
  { index: "116", name: "Les Yeux du mal, encore Aizen" },
  {
    index: "117",
    name: "La bataille de Rukia commence ! La Lame blanche glaçante !",
  },
  { index: "118", name: "Le Bankai d’Ikkaku ! Le pouvoir qui brise tout !" },
  {
    index: "119",
    name: "L’Histoire secrète de l’équipe de Zaraki ! L’Homme chanceux",
  },
  { index: "120", name: "L’Éparpillement d’Hitsugaya. Hyôrinmaru brisé" },
  { index: "121", name: "Clash ! La Protection contre la souffrance" },
  { index: "122", name: "Vizard ! La Puissance réveillée" },
  { index: "123", name: "Ichigo, hollowfication totale ?!" },
  { index: "124", name: "Clash ! Bankai noir et Bankai blanc ?" },
  { index: "125", name: "Annonce urgente ! Le Plan terrifiant d’Aizen !" },
  {
    index: "126",
    name: "Uryû contre Ryûken ! Clash entre les Quincys père et fils",
  },
  { index: "127", name: "La Décision d’Urahara, les pensées d’Orihime" },
  {
    index: "128",
    name: "Le Cauchemar Arrancar ! L’équipe Hitsugaya entre en jeu !",
  },
  {
    index: "129",
    name: "La Descente en piquée du sombre émissaire : Le mal se propage !",
  },
  {
    index: "130",
    name: "L’Ennemi invisible ! L’Impitoyable décision de Hitsugaya",
  },
  {
    index: "131",
    name: "Les Larmes de Rangiku. Le Départ douloureux du frère et de la sœur",
  },
  { index: "132", name: "Hitsugaya, Karin et le Football" },
  { index: "133", name: "Ikkaku, l’entraîneur de Kendô" },
  { index: "134", name: "Le Beau Pâtissier, Yumichika !" },
  { index: "135", name: "Kon est dupé ! Rangiku sous surveillance" },
  { index: "136", name: "Guerre civile au Hueco Mundo ! La Mort d’Ulquiorra" },
  { index: "137", name: "La Bataille malveillante. Le Piège d’Aizen" },
  {
    index: "138",
    name: "Deuxième Déplacement du Hueco Mundo ! Hitsugaya contre Yammy !",
  },
  {
    index: "139",
    name: "Ichigo contre Grimmjow ! La Bataille de 11 secondes !",
  },
  {
    index: "140",
    name: "Le Projet d’Ulquiorra. Le moment où le soleil se lève",
  },
  { index: "141", name: "Adieu…, Kurosaki !" },
  { index: "142", name: "Ordre strict ! Interdiction de sauver Inoue Orihime" },
  { index: "143", name: "La Renaissance de Grimmjow" },
  { index: "144", name: "Ishida-Chad : L’Accélération d’un nouveau pouvoir" },
  { index: "145", name: "L’Espada se réunit ! L’Assemblée royale d’Aizen" },
  {
    index: "146",
    name: "Son nom est Nell ! L’Apparence de l’étrange Arrancar",
  },
  { index: "147", name: "Forêt de Menos ! La Recherche de la disparue Rukia" },
  { index: "148", name: "Le Shinigami qui venait du passé" },
  { index: "149", name: "L’Effondrement de la forêt" },
  { index: "150", name: "Revenir ici vivant" },
  {
    index: "151",
    name: "La Tempête hurlante ! Rencontre avec l’Arrancar dansant",
  },
  { index: "152", name: "Ichigo riposte ! Voici mon Bankai !" },
  { index: "153", name: "Recherche diabolique ! Le Plan de Szayel Aporro" },
  { index: "154", name: "Rukia et Kaien, réunion douloureuse" },
  { index: "155", name: "Rukia riposte ! Le Kidô désespéré" },
  { index: "156", name: "Ishida et Pesche, l’attaque unifiée de l’amitié" },
  { index: "157", name: "L’Atout d’Ishida, le faucheur d’âmes" },
  { index: "158", name: "Bras droit du géant, bras gauche du diable" },
  { index: "159", name: "Yasutora Chad meurt ! Les Larmes d’Orihime" },
  { index: "160", name: "Testament : Ton cœur est ici" },
  { index: "161", name: "Le Cruel Arrancar. La Provocation d’Ulquiorra" },
  { index: "162", name: "Le Rire de Szayel Aporro. Renji complètement piégé" },
  { index: "163", name: "Shinigami et Quincy, la folie de la bataille" },
  {
    index: "164",
    name: "La Stratégie d’Ishida. Les Vingt Secondes d’attaque-défense",
  },
  {
    index: "165",
    name: "Bouillantes intentions meurtrières ! La Joie de Grimmjow",
  },
  {
    index: "166",
    name: "Effort désespéré contre effort désespéré ! La Hollowmorphose d’Ichigo",
  },
  { index: "167", name: "Le Temps de la conclusion. La Fin de Grimmjow" },
  {
    index: "168",
    name: "Le Nouveau Capitaine apparait ! Son nom est Shûsuke Amagai",
  },
  {
    index: "169",
    name: "Nouveau Développement ! Un dangereux étudiant transféré apparaît !",
  },
  {
    index: "170",
    name: "Lutte désespérée sous le clair de lune. L’assassin mystérieux et son Zanpakutô",
  },
  {
    index: "171",
    name: "Kenryu, la profusion des florissantes fleurs cramoisies",
  },
  { index: "172", name: "Kibune part en guerre ! Le vent violent fait rage !" },
  {
    index: "173",
    name: "L’Apparition du grand mal ! Les Ténèbres dans la maison de Kasumiôji !",
  },
  { index: "174", name: "Brise la limite du miroir ! La Captivité d’Ichigo" },
  { index: "175", name: "La Vengeance de l’assassin. Ichigo est ciblé" },
  { index: "176", name: "Mystère ! L’épée qui consumait l’assassin" },
  { index: "177", name: "Le Retour de Rukia ! La lame qui se déchaîne !" },
  { index: "178", name: "Le Cauchemar révélé. Ichigo à l’intérieur du miroir" },
  { index: "179", name: "Confrontation !? Amagai contre les treize Divisions" },
  { index: "180", name: "La Décision de la princesse. La Mariée affligée" },
  {
    index: "181",
    name: "Le Déploiement de la 2e Division ! Ichigo est encerclé",
  },
  {
    index: "182",
    name: "La Véritable Force d’Amagai. Le Zanpakuto est libéré !",
  },
  { index: "183", name: "L’obscurité se déplace ! Le Vrai Visage de Kibune" },
  {
    index: "184",
    name: "Kira et Kibune, l’attaque et la défense de la 3e Division",
  },
  {
    index: "185",
    name: "Glace et Flamme ! La Lutte féroce : Amagai contre Hitsugaya !",
  },
  { index: "186", name: "Ordre de sortie ! Supprimez la maison de Kasumiôji" },
  { index: "187", name: "Ichigo fait rage ! Le Secret de l’assassin" },
  { index: "188", name: "Duel ! Amagai contre Ichigo !" },
  { index: "189", name: "La Fierté du Shinigami tombé" },
  { index: "190", name: "Arc Hueco Mundo : Reprise !" },
  { index: "191", name: "Le Banquet effrayant. Le Théâtre de Szayel Aporro" },
  {
    index: "192",
    name: "Une beauté participe à la bataille, le secret de Nell ?!",
  },
  { index: "193", name: "L’Irrésistible spectacle de marionnettes de terreur" },
  { index: "194", name: "Le Passé de Nell" },
  { index: "195", name: "L’Union ultime ! Le Sérieux de Pesche" },
  { index: "196", name: "La plus forte armée des Shinigamis apparaît !" },
  { index: "197", name: "Le Bankai de Byakuya. La Colère tranquille" },
  { index: "198", name: "Les Deux Scientifiques. Le Piège de Mayuri" },
  { index: "199", name: "Sainte naissance. La Résurrection de Szayel Aporro" },
  { index: "200", name: "Le Corps le plus dur ?! Nnoitra se met en colère" },
  { index: "201", name: "Nnoitra libéré ! La Prolifération des armes" },
  {
    index: "202",
    name: "Conclusion de violents combats ! Qui est le plus fort ?",
  },
  { index: "203", name: "Réunion à Karakura ! Aizen contre les Shinigamis !" },
  { index: "204", name: "Le Seppuku d’Ichigo ! Stratégie de persuasion" },
  { index: "205", name: "Fureur ! Le Tournoi de football des Shinigamis !" },
  {
    index: "206",
    name: "Le chapitre du passé commence ! La Vérité, 110 ans plus tôt",
  },
  {
    index: "207",
    name: "Le Nouveau Capitaine de la 12e division, Urahara Kisuke",
  },
  { index: "208", name: "Aizen et le Petit Génie" },
  { index: "209", name: "Muguruma de la 9e division part" },
  { index: "210", name: "Hiyori meurt ? Le Début de la tragédie" },
  { index: "211", name: "Trahison ! La Manœuvre secrète d’Aizen" },
  { index: "212", name: "Sauvetage d’Hirako ! Aizen contre Urahara" },
  {
    index: "213",
    name: "Karakurizer : Konsô le justicier. La Naissance du héros justicier",
  },
  {
    index: "214",
    name: "Karakurizer : Konsô le justicier. La Cape super-utile",
  },
  { index: "215", name: "Défendre Karakura ! L’Entrée des Shinigamis" },
  { index: "216", name: "L’Élite des quatre Shinigamis" },
  { index: "217", name: "Charlotte, le beau petit démon !" },
  { index: "218", name: "Le Combat désespéré de Kira" },
  { index: "219", name: "Le Shikai d’Hisagi ! Son nom est…" },
  { index: "220", name: "Ikkaku tombe ! Instant critique pour les Shinigamis" },
  { index: "221", name: "Combat de force ! Shinigami contre Espada" },
  {
    index: "222",
    name: "La Plus Puissante des confrontations !? Soi Fon et Ômaeda",
  },
  { index: "223", name: "Un corps surprenant ! Ggio libéré" },
  { index: "224", name: "Trois contre un ! La Crise de Rangiku" },
  {
    index: "225",
    name: "Les Vice-capitaines annihilés ! Le Terrifiant monstre diabolique",
  },
  {
    index: "226",
    name: "La Fin du combat féroce ? Vers une nouvelle bataille !",
  },
  { index: "227", name: "Merveilleuse Erreur" },
  { index: "228", name: "Été et Mer ! Le Festival des maillots de bain !" },
  {
    index: "229",
    name: "Pleurs de l’âme ? La Naissance d’un nouveau Shinigami !",
  },
  { index: "230", name: "Un nouvel ennemi ! Le Zanpakutô matérialisé" },
  { index: "231", name: "Byakuya, disparaissant avec les fleurs de cerisier" },
  { index: "232", name: "Sode no Shirayuki contre Rukia ! L’Illusion du cœur" },
  { index: "233", name: "Zangetsu devient un ennemi" },
  { index: "234", name: "Renji surpris !? Les Deux Zabimaru" },
  { index: "235", name: "Clash ! Hisagi contre Kazeshini" },
  { index: "236", name: "Libération ! Le Nouveau Getsuga Tenshô" },
  { index: "237", name: "Soi Fon, entourant le Zanpakutō" },
  { index: "238", name: "Amitié ? Haine ? Haineko et Tobiume" },
  {
    index: "239",
    name: "Le Réveil de Hyôrinmaru ! Le Combat acharné d’Hitsugaya",
  },
  { index: "240", name: "La Trahison de Byakuya !" },
  { index: "241", name: "Pour la fierté ! Byakuya contre Renji" },
  { index: "242", name: "Shinigami et Zanpakutô, sortie totale" },
  { index: "243", name: "Duel ! Ichigo contre Senbonzakura !" },
  { index: "244", name: "L’homme tant attendu… Kenpachi apparaît !" },
  {
    index: "245",
    name: "Il faut poursuivre Byakuya ! Confusion dans le Gotei 13",
  },
  {
    index: "246",
    name: "Mission spéciale ! À la rescousse du capitaine-commandant Yamamoto !",
  },
  {
    index: "247",
    name: "Les Shinigamis dupés ! La crise d’un monde qui s’effondre",
  },
  {
    index: "248",
    name: "Dragon de glace et dragon de feu ! La confrontation des plus puissants !",
  },
  {
    index: "249",
    name: "Le bankai de Senbonzakura ! La bataille du monde des vivants",
  },
  { index: "250", name: "Cet homme, pour le bien des Kuchiki" },
  { index: "251", name: "Histoire obscure ! Le plus mauvais Shinigami nait" },
  { index: "252", name: "Byakuya, la vérité sur sa trahison" },
  { index: "253", name: "La vraie identité de Muramasa est révélée" },
  {
    index: "254",
    name: "Byakuya et Renji, de retour dans la sixième division",
  },
  {
    index: "255",
    name: "Chapitre final : Les histoires inconnues des Zanpakutô",
  },
  {
    index: "256",
    name: "La colère de Byakuya ! La chute de la famille Kuchiki",
  },
  {
    index: "257",
    name: "Un nouvel ennemi ! La vraie nature des épées bestiales",
  },
  { index: "258", name: "Serpent errant, singe torturé" },
  { index: "259", name: "Terreur ! Le monstre qui se cache sous terre" },
  { index: "260", name: "Conclusion !? Hisagi contre Kazeshini !" },
  {
    index: "261",
    name: "La personne aux capacités inconnues ! Orihime est prise pour cible",
  },
  { index: "262", name: "Haineko crie ! Les tragiques épées bestiales" },
  { index: "263", name: "Emprisonnement ?! Senbonzakura et Zabimaru" },
  { index: "264", name: "Bataille de femmes ? Nanao contre Katen Kyôkotsu !" },
  {
    index: "265",
    name: "Évolution ?! La merveille du final des épées bestiales",
  },
  { index: "266", name: "Ichigo contre Ulquiorra, réouverture" },
  {
    index: "267",
    name: "Les Cœurs connectés. Le Poing gauche préparé à la mort",
  },
  { index: "268", name: "Haine et Jalousie, le dilemme d’Orihime" },
  { index: "269", name: "Ichigo et Uryu, liés dos à dos" },
  {
    index: "270",
    name: "Les Prémices du désespoir… Ichigo, la lame inaccessible",
  },
  { index: "271", name: "Ichigo meurt. Orihime, les pleurs de tristesse" },
  { index: "272", name: "Ichigo contre Ulquiorra, conclusion" },
  { index: "273", name: "La Furie du requin, Hallibel se libère" },
  {
    index: "274",
    name: "Hitsugaya, les funérailles des 1000 fleurs du paradis de glace",
  },
  {
    index: "275",
    name: "Le souffle de la mort approche, le roi qui règne sur la mort",
  },
  { index: "276", name: "La Mort en un coup, le bankai de Soi Fon" },
  { index: "277", name: "Paroxysme. Kyoraku contre Starrk" },
  { index: "278", name: "Le cauchemar revient… La Résurrection de l’Espada" },
  { index: "279", name: "Hirako et Aizen… La Réunion du destin" },
  { index: "280", name: "Hisagi et Tosen, le moment de la séparation" },
  { index: "281", name: "Couronne des mensonges, la rancœur de Barragan" },
  { index: "282", name: "Le Pouvoir de l’âme. L’Attaque des loups" },
  { index: "283", name: "Starrk, le combat solitaire" },
  { index: "284", name: "Chaîne de sacrifice, le passé de Hallibel" },
  { index: "285", name: "Cent ans de rancune. La Vengeance de Hiyori" },
  { index: "286", name: "Protéger Karakura. Ichigo, vers le monde réel" },
  { index: "287", name: "Chronique. Ichigo et la Lampe magique" },
  { index: "288", name: "L’Atout final. Ichigo, vers la bataille décisive" },
  { index: "289", name: "Byakuya contre Kenpachi. La mêlée commence" },
  {
    index: "290",
    name: "Pour l’amour de la justice. L’Homme qui a déserté les Shinigamis",
  },
  { index: "291", name: "Lutte désespérée contre Aizen. Le Shikai d’Hirako" },
  { index: "292", name: "Guerre totale. Aizen contre Shinigamis" },
  { index: "293", name: "Lame de la haine. La Colère d’Hitsugaya" },
  { index: "294", name: "Impossible d’attaquer. Genryūsai scellé" },
  { index: "295", name: "Tout n’est qu’un piège… Liens réalisés" },
  {
    index: "296",
    name: "La Choquante vérité… Le Mystérieux Pouvoir intérieur d’Ichigo",
  },
  { index: "297", name: "Extension de la lame. Ichigo contre Gin" },
  { index: "298", name: "Le Film des Shinigamis" },
  {
    index: "299",
    name: "Cérémonie d’ouverture. Chapitre des enfers : Prologue",
  },
  { index: "300", name: "Urahara apparaît. Stopper Aizen" },
  {
    index: "301",
    name: "Ichigo perd son esprit combatif. La Prédiction de Gin",
  },
  { index: "302", name: "L’Ultime Getsuga Tensho. L’Entraînement d’Ichigo" },
  {
    index: "303",
    name: "Le Monde réel et les Shinigamis. Épisode spécial nouvel an",
  },
  {
    index: "304",
    name: "Une autre chronique. Cette fois l’ennemi est un vrai monstre",
  },
  {
    index: "305",
    name: "L’Ami de Yachiru. L’Apparition du Shinigami de la justice",
  },
  { index: "306", name: "Protéger Ichigo contre Tensa Zangetsu" },
  { index: "307", name: "Situation urgente. La Nouvelle Évolution d’Aizen" },
  { index: "308", name: "Adieu… Rangiku" },
  {
    index: "309",
    name: "La confrontation prend fin. L’ultime Getsuga Tensho est libéré",
  },
  {
    index: "310",
    name: "La Résolution d’Ichigo. Le Prix de la bataille féroce",
  },
  { index: "311", name: "Le Soul détective. Le Karakuraizer réapparait" },
  {
    index: "312",
    name: "L’Inauguration du tout nouveau capitaine de la 2e division",
  },
  { index: "313", name: "L’Homme aux commandes de la 11e division" },
  { index: "314", name: "Kon l’a vu. Le Secret d’une jolie femme de bureau" },
  {
    index: "315",
    name: "L’Ami de Yachiru. L’Apparition du Shinigami de la justice",
  },
  { index: "316", name: "Les Vacances de Hitsugaya Toshiro" },
  { index: "317", name: "Incident inhabituel au Seireitei" },
  { index: "318", name: "Renji contre Rukia. Batailles entre camarades" },
  {
    index: "319",
    name: "Le Filet de capture d’Ichigo. S’échapper de la Soul Society",
  },
  { index: "320", name: "Gotei 13, réunion dans le monde réel" },
  {
    index: "321",
    name: "Épreuve de force face à soi-même, Ikkaku contre Ikkaku",
  },
  { index: "322", name: "Rukia contre Rukia" },
  { index: "323", name: "Protéger Nozomi. La Détermination d’Ichigo" },
  { index: "324", name: "Reprendre le Seireitei. Les Capitaines en action" },
  { index: "325", name: "Hitsugaya contre Byakuya" },
  { index: "326", name: "Deux Hinamori, la détermination de Hitsugaya" },
  {
    index: "327",
    name: "La Fierté de la famille Kuchiki. Byakuya contre Byakuya",
  },
  { index: "328", name: "Vaincre Kageroza. Shinigami, guerre totale" },
  { index: "329", name: "La Recherche interdite… Le Secret caché de Nozomi" },
  { index: "330", name: "Je veux vivre… Le Zanpakutô de Nozomi" },
  { index: "331", name: "Pour combattre. Le Réveil de Nozomi" },
  {
    index: "332",
    name: "Le Plus Mauvais Reigai, apparition dans le monde réel",
  },
  { index: "333", name: "Détruire Nozomi. La Décision de Genryusai" },
  {
    index: "334",
    name: "Le Reiatsu diminuant. Ichigo, lutte mortelle contre son âme",
  },
  { index: "335", name: "Caché dans le Dangai. Un 2e Ichigo" },
  {
    index: "336",
    name: "À la poursuite de Kageroza. Infiltration dans le département de recherche technologique",
  },
  { index: "337", name: "Le Développeur des âmes modifiées" },
  { index: "338", name: "Les Sentiments de Kon, les sentiments de Nozomi" },
  { index: "339", name: "Protéger Ichigo. Le Lien de l’amitié" },
  {
    index: "340",
    name: "Reigai contre l’original, le combat féroce de la fierté",
  },
  { index: "341", name: "L’Armée d’invasion, conclusion finale" },
  { index: "342", name: "Merci" },
  {
    index: "343",
    name: "Lycéen de 3e année. Paré pour le début d’un nouveau chapitre",
  },
  {
    index: "344",
    name: "Un conflit au lycée. Ichigo et Uryû combattent ensemble",
  },
  {
    index: "345",
    name: "Uryû est attaqué, une menace se tisse autour de ses amis",
  },
  { index: "346", name: "L’Utilisateur du Fullbring, Ginjô Kûgo" },
  {
    index: "347",
    name: "Un effrayant danger dans la famille Kurosaki. La Confusion d’Ichigo",
  },
  {
    index: "348",
    name: "Le Pouvoir du badge du Shinigami remplaçant fait la fierté d’Ichigo",
  },
  { index: "349", name: "Prochaine cible, la main diabolique vise Orihime" },
  {
    index: "350",
    name: "L’homme qui a tué un shinigami remplaçant. Tsukishima se met en mouvement",
  },
  { index: "351", name: "Le Fullbring, le pouvoir détesté" },
  {
    index: "352",
    name: "L’Attaque de Tsukishima. L’Entrainement a été saboté",
  },
  { index: "353", name: "Ichigo maîtrise le Fullbring" },
  { index: "354", name: "Ichigo contre Ginjô dans l’espace du jeu" },
  {
    index: "355",
    name: "Les Shinigami entrent dans la bataille. Le Seireitei a aussi un Nouvel An spécial",
  },
  { index: "356", name: "Un ennemi ou un ami. Le Cœur invisible de Ginjō" },
  { index: "357", name: "La Capacité de la menace rampante, Tsukishima" },
  { index: "358", name: "L’Xcution a frappé Ginjō" },
  { index: "359", name: "Le Triste Combat. Ichigo contre Chad et Orihime" },
  { index: "360", name: "Ichigo contre Uryu. Qui est le traître" },
  { index: "361", name: "Une nouvelle apparence. Rencontre avec le Gotei 13" },
  { index: "362", name: "Retour d’Ichigo Kurosaki, le Shinigami remplaçant" },
  { index: "363", name: "Les Shinigami contre l’Xcution" },
  { index: "364", name: "Lutte désespérée. Les Pensées troubles de Byakuya" },
  {
    index: "365",
    name: "Ichigo contre Ginjô. Le Secret du badge de Shinigami remplaçant",
  },
  { index: "366", name: "L’histoire change mais le cœur reste inchangé" },
  { index: "367", name: "La Guerre sanglante" },
  { index: "368", name: "Les Premières Pierres" },
  { index: "369", name: "La Marche des Quincys" },
  { index: "370", name: "Tuer l’ombre" },
  { index: "371", name: "La Fureur de l’éclair" },
  { index: "372", name: "Le Brasier" },
  { index: "373", name: "Né des ténèbres" },
  { index: "374", name: "Le Projet Étoile Filante" },
  { index: "375", name: "La Chute" },
  { index: "376", name: "Le Combat" },
  { index: "377", name: "Tout sauf la pluie" },
  { index: "378", name: "Tout sauf la pluie, la vérité de juin" },
  { index: "379", name: "La Lame, c’est moi" },
  { index: "380", name: "Les Neufs Derniers Jours" },
  { index: "381", name: "La paix venue de l’ombre" },
  { index: "382", name: "La Violence fondamentale" },
  { index: "383", name: "Cœur de loup" },
  { index: "384", name: "Aux premières loges" },
  { index: "385", name: "Le Voile blanc" },
  { index: "386", name: "Le Tranchant" },
  { index: "387", name: "L’Étoile étiolée" },
  { index: "388", name: "L’Exposition des zombies" },
  { index: "389", name: "L’Exposition des zombies 2" },
  { index: "390", name: "Trop tôt pour crier victoire, trop tard pour savoir" },
  { index: "391", name: "Le Maitre" },
  { index: "392", name: "Noir" },
];

export default names;
