const episodes = [
  { name: "Cruauté", index: "1" },
  { name: "Urokodaki Sakonji, le formateur", index: "2" },
  { name: "Sabito et Makomo", index: "3" },
  { name: "La sélection finale", index: "4" },
  { name: "Chacun son acier", index: "5" },
  { name: "Le chasseur accompagné d'un démon", index: "6" },
  { name: "Kibutsuji Muzan", index: "7" },
  { name: "Le parfum du sang d'envoûtement", index: "8" },
  { name: "Les démons aux ballons et aux flèches", index: "9" },
  { name: "Nous resterons ensemble", index: "10" },
  { name: "La maison aux tambours", index: "11" },
  { name: "Zen'itsu dort, le sanglier montre les crocs", index: "12" },
  { name: "Ce à quoi il tient plus qu'à la vie", index: "13" },
  { name: "Le blason des glycines", index: "14" },
  { name: "Le mont Natagumo", index: "15" },
  { name: "Faire passer les autres avant soi", index: "16" },
  { name: "Parfaire une seule technique", index: "17" },
  { name: "Des liens factices", index: "18" },
  { name: "Le dieu du feu", index: "19" },
  { name: "Une famille improvisée", index: "20" },
  { name: "Violation du code", index: "21" },
  { name: "Le maître", index: "22" },
  { name: "La réunion des piliers", index: "23" },
  { name: "L'entraînement récupérateur", index: "24" },
  { name: "Tsuyuri Kanao, la successeuse", index: "25" },
  { name: "Nouvelle mission", index: "26" },
  { name: "Rengoku Kyôjurô, le pilier de la flamme", index: "27" },
  { name: "Un sommeil profond", index: "28" },
  { name: "Si c’était réel", index: "29" },
  { name: "Affront", index: "30" },
  { name: "À l’avant du train", index: "31" },
  { name: "Akaza", index: "32" },
  { name: "Enflamme ton âme", index: "33" },
  { name: "Uzui Tengen, le pilier du son", index: "34" },
  { name: "Infiltration au quartier des plaisirs", index: "35" },
  { name: "Qui es-tu ?", index: "36" },
  { name: "Cette nuit", index: "37" },
  { name: "Combattre avec panache !", index: "38" },
  { name: "Des souvenirs accumulés", index: "39" },
  { name: "Métamorphose", index: "40" },
  { name: "Union", index: "41" },
  { name: "Après avoir abattu une lune supérieure", index: "42" },
  { name: "Je n’abandonnerai jamais", index: "43" },
  { name: "À chaque réincarnation", index: "44" },
  { name: "Le rêve d'un étranger", index: "45" },
  { name: "Yoriichi modèle zéro", index: "46" },
  { name: "Le katana de plus de 300 ans", index: "47" },
  { name: "Merci, Tokitô", index: "48" },
  { name: "Le sabre écarlate", index: "49" },
  { name: "Tu veux devenir un pilier, non ?", index: "50" },
  { name: "Les véritables monstres", index: "51" },
  { name: "Le sens du prénom de Muichirô", index: "52" },
  { name: "Tokitô Muichirô, le pilier de la brume", index: "53" },
  { name: "Kanroji Mitsuri, le pilier de l'amour", index: "54" },
  { name: "Unis au point du jour", index: "55" },
  { name: "Pour vaincre Kibutsuji Muzan", index: "56" },
  { name: "La souffrance de Tomioka Giyû, pilier de l'eau", index: "57" },
  { name: "Tanjirô est rétabli et se joint à l'entraînement !", index: "58" },
];

export default episodes;
