const names = [
  { name: "Les voies du tigre sont impénétrables", index: "1" },
  { name: "La bombe", index: "2" },
  { name: "Yokohama Gangster Paradise", index: "3" },
  { name: "Le chagrin d'un fataliste", index: "4" },
  { name: "Murder on D Street", index: "5" },
  { name: "L'apôtre bleu", index: "6" },
  { name: "Chérir la maladie de l'idéal", index: "7" },
  { name: "Tuer et mourir", index: "8" },
  { name: "La beauté est une statue de pierre", index: "9" },
  { name: "Rashômon et le Tigre", index: "10" },
  { name: "Ce travail n'est pas fait pour elle", index: "11" },
  { name: "Continuellement poussé vers le passé", index: "12" },
  { name: "Une sombre époque", index: "13" },
  { name: "Là où on ne peut plus retourner", index: "14" },
  { name: "Un jour, j'aurai vue sur la mer", index: "15" },
  { name: "Le chien errant de la littérature", index: "16" },
  { name: "La triade des sociétés", index: "17" },
  { name: "The strategy of conflict", index: "18" },
  { name: "Will of tycoon", index: "19" },
  { name: "Le cerveau peut se tromper", index: "20" },
  { name: "Double Noir", index: "21" },
  {
    name: "Partie 1, Poe et Ranpo / Partie 2, La baleine blanche dans la mer céleste",
    index: "22",
  },
  { name: "Rashômon, le tigre et le dernier magnat", index: "23" },
  { name: "Si je peux enfin me débarrasser de ce fardeau", index: "24" },
  { name: "Le marcheur solitaire (OAV)", index: "25" },
  { name: "Dazai et Chûya à leur 15 ans", index: "26" },
  { name: "L'entrée du dieu furieux", index: "27" },
  { name: "Seul un diamant peut en polir un autre", index: "28" },
  { name: "Le crime est l'œuvre de Dieu", index: "29" },
  { name: "Slap the stick & addict", index: "30" },
  { name: "Partie 1, Cherrirs / Partie 2, Le portrait d’un père", index: "31" },
  { name: "Fitzgerald rising", index: "32" },
  { name: "L'assassin masqué", index: "33" },
  { name: "Cannibalisme (partie 1)", index: "34" },
  { name: "Cannibalisme (partie 2)", index: "35" },
  { name: "Cannibalisme (partie 3)", index: "36" },
  { name: "Echo – Funérailles", index: "37" },
  { name: "L'épéiste solitaire et le célèbre détective", index: "38" },
  {
    name: "Le monde visible est chimère, la réalité se trouve dans les rêves de la nuit",
    index: "39",
  },
  { name: "Les secrets de la fondation de l'Agence", index: "40" },
  { name: "Le meurtrier et le meurtre parfaits (1re partie)", index: "41" },
  { name: "Le meurtrier et le meurtre parfaits (2e partie)", index: "42" },
  { name: "Sunday tragedy", index: "43" },
  { name: "Dogs hunt dogs", index: "44" },
  { name: "Toi et moi, enfants du péché", index: "45" },
  { name: "Rêve de papillon", index: "46" },
  { name: "L'amertume de ceux qui n'ont pas d'ailes", index: "47" },
  { name: "Chronique d'une évasion", index: "48" },
  { name: "Bungô Hound Dogs", index: "49" },
  { name: "Skyfall", index: "50" },
  { name: "Le plus puissant", index: "51" },
  { name: "Toutes les réponses", index: "52" },
  { name: "Hero vs. Criminal", index: "53" },
  { name: "Hero war, gang war", index: "54" },
  { name: "Aux portes du ciel - Partie 1", index: "55" },
  { name: "Aux portes du ciel - Partie 2", index: "56" },
  { name: "Aux portes du ciel - Partie 3", index: "57" },
  { name: "La terre des inhumains - Partie 1", index: "58" },
  { name: "La terre des inhumains - Partie 2", index: "59" },
  { name: "La terre des inhumains - Partie 3", index: "60" },
  { name: "Adieu crépusculaire", index: "61" },
];

export default names;
