const names = [
  { name: "Symptôme – Mutation", index: "01" },
  { name: "Départ – Départ pour le front", index: "02" },
  { name: "Vers Mars – Vers l'astre funeste", index: "03" },
  { name: "Guerre – Guerre totale", index: "04" },
  { name: "Exceptionnel Deux – Enfants prodiges", index: "05" },
  { name: "2 Minutes – Dans les deux minutes", index: "06" },
  { name: "Crabe – Vaillant soldat", index: "07" },
  { name: "Der Zitteraal – L'Être électrique", index: "08" },
  { name: "Trop triste pour mourir – Orage pluvieux", index: "09" },
  { name: "Désir – Souhait", index: "10" },
  { name: "Boxeur – Boxeur", index: "11" },
  { name: "Étoile filante - Raison et déraison", index: "12" },
  { name: "Terra for Mars - Ici et là-bas", index: "13" },
  { name: "2ND GENERATION - Le duo exceptionnel", index: "14" },
  { name: "CENTURY OF RAISING ARMS - La colère du capitaine", index: "15" },
  { name: "FRIEND HERE - Rencontre alliée", index: "16" },
  { name: "TRIPLE COMBAT - Affrontement à trois", index: "17" },
  { name: "MAN ON A MISSION - Le père et le soldat", index: "18" },
  { name: "STRATEGY AND TACTICS - Stratégie et armement", index: "19" },
  { name: "HAPPY BIRTHDAY - Le premier jour", index: "20" },
  { name: "WEB OF BEND - Le filet du chasseur", index: "21" },
  { name: "THE FOREMOST - Le premier du classement", index: "22" },
  { name: "NO PLACE TO HIDE - La colonie", index: "23" },
  { name: "SILENCE OR VIOLENCE - Le poing du silence", index: "24" },
  { name: "STRENGTH OF WEAKEST - L'âme de ceux qui n'ont rien", index: "25" },
  { name: "THE 12 SECONDS - Révolution en 12 secondes", index: "26" },
];

export default names;
