const names = [
  { index: "1", name: "Le grand départ" },
  { index: "2", name: "Les premiers pas" },
  { index: "3", name: "Le nuage supersonique de Tortue Géniale" },
  { index: "4", name: "Le grand malfaisant" },
  { index: "5", name: "Yamcha, l’enfant terrible du désert" },
  { index: "6", name: "Un drôle de bandit" },
  { index: "7", name: "La montagne mystérieuse" },
  { index: "8", name: "L’onde de choc du grand maître" },
  { index: "9", name: "Les carottes sont cuites" },
  { index: "10", name: "On a volé les boules de cristal" },
  { index: "11", name: "Le réveil du dragon" },
  { index: "12", name: "Le monstre de la pleine lune" },
  { index: "13", name: "La métamorphose de Sangoku" },
  { index: "14", name: "L’apparition d’un rival" },
  { index: "15", name: "Une fille mystérieuse" },
  { index: "16", name: "Les premiers tests" },
  { index: "17", name: "Entraînement intensif" },
  { index: "18", name: "Entraînement selon Tortue Géniale" },
  { index: "19", name: "Le grand championnat" },
  { index: "20", name: "Que le meilleur gagne" },
  { index: "21", name: "Le colosse" },
  { index: "22", name: "Yamcha contre Jackie Chun" },
  { index: "23", name: "Sangoku contre le dragon volant" },
  { index: "24", name: "Le combat désespéré de Krilin" },
  { index: "25", name: "Quand le combat devient aérien" },
  { index: "26", name: "Le combat final" },
  { index: "27", name: "Sangoku en pleine crise" },
  { index: "28", name: "La finale" },
  { index: "29", name: "Le lac magique" },
  { index: "30", name: "La boule aux quatre étoiles" },
  { index: "31", name: "Vive le marié" },
  { index: "32", name: "20000 lieues sous les sables" },
  { index: "33", name: "La légende du dragon" },
  { index: "34", name: "Le général en chef ne plaisante pas" },
  { index: "35", name: "Sangoku dans le grand nord" },
  { index: "36", name: "Le combat du sergent métallique" },
  { index: "37", name: "Ninja Murazaki fait son entrée" },
  { index: "38", name: "Cinq Murazakis contre Sangoku" },
  { index: "39", name: "Le robot au grand cœur" },
  { index: "40", name: "La bête immonde" },
  { index: "41", name: "Le dernier jour de la tour de contrôle" },
  { index: "42", name: "Le secret du docteur Flatt" },
  { index: "43", name: "Sangoku découvre la ville" },
  { index: "44", name: "Sangoku retrouve ses amis" },
  { index: "45", name: "Busky la féline" },
  { index: "46", name: "Bulma revient de loin" },
  { index: "47", name: "Sur une île de Tortue Géniale" },
  { index: "48", name: "Le général Blue passe à l’attaque" },
  { index: "49", name: "Une grotte miraculeuse" },
  { index: "50", name: "Les pièges des pirates" },
  { index: "51", name: "Le robot pirate" },
  { index: "52", name: "Le trésor existe" },
  { index: "53", name: "La grotte aux mille dangers" },
  { index: "54", name: "Sauve qui peut" },
  { index: "55", name: "Vers les villages des jouets mécaniques" },
  { index: "56", name: "Comme sur un petit nuage" },
  { index: "57", name: "Arale contre le Ruban Rouge" },
  { index: "58", name: "Les habitants de la terre sainte" },
  { index: "59", name: "Le redoutable Taopaïpaï passe à l’action" },
  { index: "60", name: "Sangoku se mesure à Taopaïpaï" },
  { index: "61", name: "Le maître des maîtres" },
  { index: "62", name: "L’eau sacrée" },
  { index: "63", name: "Le héros est de retour" },
  { index: "64", name: "La défaite de Taopaïpaï" },
  { index: "65", name: "En route pour le quartier général" },
  { index: "66", name: "L’armée du Ruban Rouge est en déroute" },
  { index: "67", name: "La fin du commandant Red" },
  { index: "68", name: "La dernière boule de cristal" },
  { index: "69", name: "Baba" },
  { index: "70", name: "Les cinq adversaires" },
  { index: "71", name: "La fosse du diable" },
  { index: "72", name: "Yamcha frôle la mort" },
  { index: "73", name: "Le pouvoir mortel du diable" },
  { index: "74", name: "Le cinquième homme" },
  { index: "75", name: "Un mystérieux adversaire" },
  { index: "76", name: "L’adversaire se démasque" },
  { index: "77", name: "Les tactiques de Pilaf" },
  { index: "78", name: "Le divin dragon revient" },
  { index: "79", name: "Une gourde maléfique" },
  { index: "80", name: "Le match du roi" },
  { index: "81", name: "Sangoku chez les démons" },
  { index: "82", name: "Le cerglier ailé" },
  { index: "83", name: "En route pour le grand tournoi des arts martiaux" },
  { index: "84", name: "Le champion toutes catégories" },
  { index: "85", name: "Les éliminatoires" },
  { index: "86", name: "Les huit meilleurs" },
  { index: "87", name: "Yamcha contre Tenshinhan" },
  { index: "88", name: "Le grand tournoi d’art martiaux" },
  { index: "89", name: "Rencontre de la pleine lune" },
  { index: "90", name: "La revanche de Taopaïpaï" },
  { index: "91", name: "Une idée de génie" },
  { index: "92", name: "Sangoku contre Ballouc" },
  { index: "93", name: "Deux adversaires de grand talent" },
  { index: "94", name: "Une décision inattendue" },
  { index: "95", name: "Sangoku contre Krilin" },
  { index: "96", name: "Les meilleurs coups de Krilin" },
  { index: "97", name: "Le match final" },
  { index: "98", name: "Une attaque de haute volée" },
  { index: "99", name: "Une fausse victoire" },
  { index: "100", name: "La dernière chance" },
  { index: "101", name: "La grande finale" },
  { index: "102", name: "Un plan diabolique" },
  { index: "103", name: "Le temps de la terreur" },
  { index: "104", name: "Sangoku revient à la vie" },
  { index: "105", name: "L’homme des bois" },
  { index: "106", name: "Une nouvelle mission" },
  { index: "107", name: "À la mémoire de Krilin" },
  { index: "108", name: "Satan se montre" },
  { index: "109", name: "Sangoku contre Satan Petit Cœur" },
  { index: "110", name: "Le dernier espoir" },
  { index: "111", name: "Le dernier combat de Tortue Géniale" },
  { index: "112", name: "À la quête de l’éternelle jeunesse" },
  { index: "113", name: "La première étape" },
  { index: "114", name: "Au sommet de la tour" },
  { index: "115", name: "Le labyrinthe de glace" },
  { index: "116", name: "Tortue Géniale réapparaît" },
  { index: "117", name: "Sangoku se réincarne" },
  { index: "118", name: "La détermination de Tenshinhan" },
  { index: "119", name: "Tenshinhan rencontre Satan" },
  { index: "120", name: "La colère de Sangoku" },
  { index: "121", name: "Un combat difficile" },
  { index: "122", name: "La fin de Satan" },
  { index: "123", name: "À la recherche du bâton magique" },
  { index: "124", name: "Le temple dans les nuages" },
  { index: "125", name: "Dieu apparaît" },
  { index: "126", name: "La résurrection du dragon" },
  { index: "127", name: "Plus rapide que l’éclair" },
  { index: "128", name: "Un adversaire imaginaire" },
  { index: "129", name: "Voyage" },
  { index: "130", name: "L’apprentissage" },
  { index: "131", name: "Quand chacun poursuit sa quête" },
  { index: "132", name: "La colère du volcan" },
  { index: "133", name: "Les retrouvailles" },
  { index: "134", name: "La coupe du monde des arts martiaux" },
  { index: "135", name: "Les huit meilleurs candidats" },
  { index: "136", name: "Le maître ignorant" },
  { index: "137", name: "Sangoku se marie" },
  { index: "138", name: "Shen, un candidat peu ordinaire" },
  { index: "139", name: "Sangoku contre Tenshinhan, deuxième rencontre" },
  { index: "140", name: "Entraînement très spécial" },
  { index: "141", name: "Tous pour un, un pour tous" },
  { index: "142", name: "Shen contre Petit Cœur Junior" },
  { index: "143", name: "Pour l’avenir du monde" },
  { index: "144", name: "Le dernier combat" },
  { index: "145", name: "Le géant du tournoi" },
  { index: "146", name: "La loyauté de Sangoku" },
  { index: "147", name: "Une épreuve difficile" },
  { index: "148", name: "La victoire finale" },
  { index: "149", name: "L’éventail magique" },
  { index: "150", name: "Le mangeur de feu" },
  { index: "151", name: "Chichi femme idéale" },
  { index: "152", name: "Le mont des cinq éléments" },
  { index: "153", name: "Dans les flammes de l’enfer" },
];

export default names;
