const episodes = [
  { name: "Lesson 1", index: "1" },
  { name: "Lesson 2", index: "2" },
  { name: "Lesson 3", index: "3" },
  { name: "Lesson 4", index: "4" },
  { name: "Lesson 5", index: "5" },
  { name: "Lesson 6", index: "6" },
  { name: "Lesson 7", index: "7" },
  { name: "Lesson 8", index: "8" },
  { name: "Lesson 9", index: "9" },
  { name: "Lesson 10", index: "10" },
  { name: "Lesson 11", index: "11" },
  { name: "Lesson 12", index: "12" },
  { name: "Lesson 13", index: "13" },
  { name: "Lesson 14", index: "14" },
  { name: "Lesson 15", index: "15" },
  { name: "Lesson 16", index: "16" },
  { name: "Lesson 17", index: "17" },
  { name: "Lesson 18", index: "18" },
  { name: "Lesson 19", index: "19" },
  { name: "Lesson 20", index: "20" },
  { name: "Lesson 21", index: "21" },
  { name: "Lesson 22", index: "22" },
  { name: "Lesson 23", index: "23" },
  { name: "Lesson 24", index: "24" },
  { name: "Lesson 25", index: "25" },
  { name: "Lesson 26", index: "26" },
  { name: "Lesson 27", index: "27" },
  { name: "Lesson 28", index: "28" },
  { name: "Lesson 29", index: "29" },
  { name: "Lesson 30", index: "30" },
  { name: "Lesson 31", index: "31" },
  { name: "Lesson 32", index: "32" },
  { name: "Lesson 33", index: "33" },
  { name: "Lesson 34", index: "34" },
  { name: "Lesson 35", index: "35" },
  { name: "Lesson 36", index: "36" },
  { name: "Lesson 37", index: "37" },
  { name: "Lesson 38", index: "38" },
  { name: "Lesson 39", index: "39" },
  { name: "Lesson 40", index: "40" },
  { name: "Lesson 41", index: "41" },
  { name: "Lesson 42", index: "42" },
  { name: "Lesson 43", index: "43" },
];

export default episodes;
