const episodes = [
  { name: "Défier le soleil", index: "1" },
  { name: "Le corps d'un condamné", index: "2" },
  { name: "Maman…", index: "3" },
  { name: "Le trafiquant d'âmes", index: "4" },
  { name: "L'homme au bras bionique", index: "5" },
  { name: "L'examen d'entrée", index: "6" },
  { name: "Le cri de la chimère", index: "7" },
  { name: "La Pierre Philosophale", index: "8" },
  { name: "Au service du peuple", index: "9" },
  { name: "La voleuse fantôme", index: "10" },
  { name: "Faux frères - 1re partie", index: "11" },
  { name: "Faux frères - 2e partie", index: "12" },
  { name: "Flamme vs Fullmetal", index: "13" },
  { name: "Le bras droit destructeur", index: "14" },
  { name: "Le massacre d'Ishbal", index: "15" },
  { name: "Ce qu'on a perdu", index: "16" },
  { name: "La maison familiale", index: "17" },
  { name: "Les notes de Marcoh", index: "18" },
  { name: "Toute la vérité", index: "19" },
  { name: "Âme de gardien", index: "20" },
  { name: "La lueur rouge", index: "21" },
  { name: "Les Homonculus", index: "22" },
  { name: "Cœur d'acier", index: "23" },
  { name: "Souvenirs enracinés", index: "24" },
  { name: "Cérémonie d'adieu", index: "25" },
  { name: "Au pays des auto-mails", index: "26" },
  { name: "Maître", index: "27" },
  { name: "Un est tout, tout est un", index: "28" },
  { name: "Un enfant innocent", index: "29" },
  { name: "Attaque du QG Sud", index: "30" },
  { name: "Le péché", index: "31" },
  { name: "Dante", index: "32" },
  { name: "Al se fait enlever", index: "33" },
  { name: "La théorie de Greed", index: "34" },
  { name: "Retrouvailles", index: "35" },
  { name: "Tueurs-nés", index: "36" },
  { name: "L'alchimiste de flamme", index: "37" },
  { name: "Le lit de la rivière", index: "38" },
  { name: "Guerre civile dans l’Est", index: "39" },
  { name: "La cicatrice", index: "40" },
  { name: "La sainte", index: "41" },
  { name: "De nom inconnu", index: "42" },
  { name: "Chien errant", index: "43" },
  { name: "Hohenheim le Lumineux", index: "44" },
  { name: "Cœur corrompu", index: "45" },
  { name: "Transmutation humaine", index: "46" },
  { name: "Sceller un Homunculus", index: "47" },
  { name: "Adieu", index: "48" },
  { name: "Derrière la porte", index: "49" },
  { name: "La mort", index: "50" },
  { name: "Un monde imparfait", index: "51" },
];

export default episodes;
