const names = [
  { index: "1", name: "Une fin et un début" },
  { index: "2", name: "Le club de volley-ball de Karasuno" },
  { index: "3", name: "Le plus puissant allié" },
  { index: "4", name: "La vue du sommet" },
  { index: "5", name: "Le stress des gens timides" },
  { index: "6", name: "Une équipe intrigante" },
  { index: "7", name: "Contre le 'grand roi'" },
  { index: "8", name: "Le champion de l'équipe" },
  { index: "9", name: "La passe au champion" },
  { index: "10", name: "Admiration" },
  { index: "11", name: "Détermination" },
  { index: "12", name: "Retrouvailles entre Chats et Corbeaux" },
  { index: "13", name: "Rival" },
  { index: "14", name: "Des adversaires redoutables" },
  { index: "15", name: "Résurrection" },
  { index: "16", name: "Gagnants et perdants" },
  { index: "17", name: "Le mur de fer" },
  { index: "18", name: "Des arrières couverts" },
  { index: "19", name: "Le chef d'orchestre" },
  { index: "20", name: "Oikawa Tōru n’est pas un génie" },
  { index: "21", name: "La force d'un aîné" },
  { index: "22", name: "Évolution" },
  { index: "23", name: "Ce qui va changer le cours du jeu" },
  { index: "24", name: "Le roi solitaire n'est plus" },
  { index: "25", name: "Le troisième jour" },
  { index: "26", name: "Let's go, Tokyo !" },
  { index: "27", name: "Rayons de soleil" },
  { index: "28", name: "Le 'villageois B'" },
  { index: "29", name: "Le champion central" },
  { index: "30", name: "Avidité" },
  { index: "31", name: "Tempo" },
  { index: "32", name: "Lever de lune" },
  { index: "33", name: "Héros illusoire" },
  { index: "34", name: "Contre le 'parapluie'" },
  { index: "35", name: "Rouages" },
  { index: "36", name: "Au-dessus" },
  { index: "37", name: "Début du match" },
  { index: "38", name: "Une force pure et simple" },
  { index: "39", name: "En pleine croissance" },
  { index: "40", name: "Terrain de jeu" },
  { index: "41", name: "Aux suivants" },
  { index: "42", name: "La lutte d'un froussard" },
  { index: "43", name: "Les perdants" },
  {
    index: "44",
    name: "Le mur de fer s’élèvera autant de fois que nécessaire",
  },
  { index: "45", name: "Balayés" },
  { index: "46", name: "Démolisseur" },
  { index: "47", name: "La lutte d'un ancien froussard" },
  { index: "48", name: "Une 'équipe'" },
  { index: "49", name: "Changement extrême" },
  { index: "50", name: "Déclaration de guerre" },
  { index: "51", name: "Présentation" },
  { index: "52", name: "La menace 'gauchère'" },
  { index: "53", name: "GUESS MONSTER" },
  { index: "54", name: "Halo lunaire" },
  { index: "55", name: "L'individuel vs le collectif" },
  { index: "56", name: "La réaction chimique d'une rencontre" },
  { index: "57", name: "Ressentiment" },
  { index: "58", name: "Un type détestable" },
  { index: "59", name: "Les fous de volley" },
  { index: "60", name: "Bataille de concepts" },
  { index: "61", name: "Les présentations" },
  { index: "62", name: "Désorienté" },
  { index: "63", name: "Point de vue" },
  { index: "64", name: "La facilité" },
  { index: "65", name: "Affamé" },
  { index: "66", name: "Exaltation" },
  { index: "67", name: "Retour" },
  { index: "68", name: "Challenger" },
  { index: "69", name: "Dernière soirée" },
  { index: "70", name: "En première ligne" },
  { index: "71", name: "Tout s'enchaîne" },
  { index: "72", name: "Une image saisissant" },
  { index: "73", name: "Le 2e jour" },
  { index: "74", name: "Rhythme" },
  { index: "75", name: "Chercher et trouver" },
  { index: "76", name: "Cœur brisé" },
  { index: "77", name: "Chats contre singes" },
  { index: "78", name: "Pris au piège" },
  { index: "79", name: "Les plus forts challengeurs" },
  { index: "80", name: "Le capitaine" },
  { index: "81", name: "Le héros" },
  { index: "82", name: "Piton" },
  { index: "83", name: "Naissance d'un roi silencieux" },
  { index: "84", name: "Le festin des monstres" },
  { index: "85", name: "La terre promise" },
];

export default names;
