const episodes = [
  { name: "La métamorphose de Sangoku", index: "1" },
  { name: "La fine équipe", index: "2" },
  { name: "Une drôle de planète", index: "3" },
  { name: "L'ennemi no 1", index: "4" },
  { name: "Le départ", index: "5" },
  { name: "La planète des animaux géants", index: "6" },
  { name: "Une mystérieuse moustache", index: "7" },
  { name: "L'antre de l'enfer", index: "8" },
  { name: "Au voleur", index: "9" },
  { name: "La danse de l'espace", index: "10" },
  { name: "La malédiction de Ludé", index: "11" },
  { name: "Le fouet du diable", index: "12" },
  { name: "Le cauchemar continue", index: "13" },
  { name: "La stratégie du mutant", index: "14" },
  { name: "La troisième boule de cristal", index: "15" },
  { name: "Le secret de Gigi", index: "16" },
  { name: "Pan aux commandes", index: "17" },
  { name: "La colère de Sangoku", index: "18" },
  { name: "Le transfert de Trunks", index: "19" },
  { name: "Les murs qui ne restent pas en place", index: "20" },
  { name: "Sangoku tombe dans le piège", index: "21" },
  { name: "Le bébé mutant", index: "22" },
  { name: "Sauvetage dans l'espace", index: "23" },
  { name: "L'habit ne fait pas le moine", index: "24" },
  { name: "Le bébé mutant débarque sur Terre", index: "25" },
  { name: "Le combat des deux frères", index: "26" },
  { name: "L'intervention de Végéta", index: "27" },
  { name: "Le retour", index: "28" },
  { name: "L'horrible trahison", index: "29" },
  { name: "Une sacrée surprise", index: "30" },
  { name: "Entre deux mondes", index: "31" },
  { name: "Une vieille connaissance", index: "32" },
  { name: "Le retour du grand singe", index: "33" },
  { name: "La surprise", index: "34" },
  { name: "Le niveau 4", index: "35" },
  { name: "Retournement de situation", index: "36" },
  { name: "L'eau sacrée", index: "37" },
  { name: "Guérisons en chaîne", index: "38" },
  { name: "La fin du bébé-mutant", index: "39" },
  { name: "Le retour de Petit Cœur", index: "40" },
  { name: "Un nouveau tournoi", index: "41" },
  { name: "Les anciens ennemis", index: "42" },
  { name: "Ascenseur pour l'enfer", index: "43" },
  { name: "La fusion des deux clones", index: "44" },
  { name: "La stratégie de Petit-Cœur", index: "45" },
  { name: "Une transformation providentielle", index: "46" },
  { name: "La colère de la veuve", index: "47" },
  { name: "L'imposteur", index: "48" },
  { name: "Le premier dragon", index: "49" },
  { name: "Le second dragon", index: "50" },
  { name: "La troisième épreuve", index: "51" },
  { name: "Le dragon aux sept étoiles", index: "52" },
  { name: "Pan en mauvaise posture", index: "53" },
  { name: "Le cinquième dragon", index: "54" },
  { name: "Végéta s'en mêle", index: "55" },
  { name: "Le feu et la glace", index: "56" },
  { name: "Le dragon à une étoile", index: "57" },
  { name: "Échec au prince ", index: "58" },
  { name: "La contre-attaque", index: "59" },
  { name: "La chance tourne", index: "60" },
  { name: "L'ultime fusion", index: "61" },
  { name: "Le dernier allié", index: "62" },
  { name: "Le sauvetage de l'univers", index: "63" },
  { name: "Au revoir Sangoku", index: "64" },
];

export default episodes;
