const names = [
  { name: "Le Plus Grand Détective du siècle", index: "1" },
  { name: "Le Commencement", index: "2" },
  { name: "Méfiez-vous des stars", index: "3" },
  { name: "Le Poisson lumineux", index: "4" },
  { name: "La Bombe roulante", index: "5" },
  { name: "Le Meurtre de la Saint-Valentin", index: "6" },
  { name: "Le Mystérieux expéditeur", index: "7" },
  { name: "Meurtre au musée", index: "8" },
  { name: "Festival fatal", index: "9" },
  { name: "Conan marque un but", index: "10" },
  { name: "Sonate pour crime au clair de lune", index: "11" },
  { name: "L’Enlèvement d’Ayumi", index: "12" },
  { name: "Le Meurtre déconcertant", index: "13" },
  { name: "Un message à déchiffrer", index: "14" },
  { name: "Un cadavre a disparu", index: "15" },
  { name: "Le Meurtre du collectionneur d’antiquités", index: "16" },
  { name: "Cambriolage au supermarché", index: "17" },
  { name: "La Mariée de juin", index: "18" },
  { name: "Meurtre dans l’ascenseur", index: "19" },
  { name: "La Maison hantée", index: "20" },
  { name: "Meurtre sur un plateau", index: "21" },
  {
    name: "Les meurtriers en série embarquent sur le Luxury Liner",
    index: "22",
  },
  {
    name: "Les meurtriers en série embarquent sur le Luxury Liner",
    index: "23",
  },
  { name: "La Mystérieuse amnésique", index: "24" },
  { name: "Enlèvement contre rançon", index: "25" },
  { name: "John et l’Assassinat", index: "26" },
  { name: "La Réunion de classe de Kogoro", index: "27" },
  { name: "La Réunion de classe de Kogoro", index: "28" },
  { name: "Meurtre en direct", index: "29" },
  { name: "Un alibi parfait", index: "30" },
  { name: "Meurtre au studio de télévision", index: "31" },
  { name: "Meurtre au coffee shop", index: "32" },
  { name: "Rendez-vous mortel", index: "33" },
  { name: "L’Homme aux bandelettes", index: "34" },
  { name: "L’Homme aux bandelettes", index: "35" },
  { name: "L’affaire du meurtre du lundi à 19h30", index: "36" },
  { name: "Meurtre au cactus", index: "37" },
  { name: "La Fête du Feu", index: "38" },
  { name: "Le Meurtre de l’héritière", index: "39" },
  { name: "Le Meurtre de l’héritière", index: "40" },
  { name: "L’Affaire du drapeau en lambeaux", index: "41" },
  { name: "Meurtre au karaoké", index: "42" },
  { name: "Le Kidnapping de Conan Edogawa", index: "43" },
  { name: "L’Anniversaire de monsieur Hotta", index: "44" },
  { name: "Le Masque de beauté", index: "45" },
  { name: "Meurtre en montagne", index: "46" },
  { name: "Affaire de haut-vol", index: "47" },
  { name: "Meurtre d’un diplomate", index: "48" },
  { name: "Meurtre d’un diplomate", index: "49" },
  { name: "Meurtre à la bibliothèque", index: "50" },
  { name: "Meurtre au club house", index: "51" },
  { name: "Le Démon du monastère", index: "52" },
  { name: "L’Affaire de l’arme mystérieuse", index: "53" },
  { name: "La Mystérieuse organisation", index: "54" },
  { name: "Itinéraire impossible", index: "55" },
  { name: "Poisson lune", index: "56" },
  { name: "Sur les traces de Sherlock Holmes", index: "57" },
  { name: "Sur les traces de Sherlock Holmes", index: "58" },
  { name: "Une première fatale", index: "59" },
  { name: "Une dessinatrice pleine de talent", index: "60" },
  { name: "Le Vaisseau fantôme", index: "61" },
  { name: "Le Vaisseau fantôme", index: "62" },
  { name: "Un monstre peut en cacher un autre", index: "63" },
  { name: "Les Trois Empreintes", index: "64" },
  { name: "Les Crabes et la Baleine", index: "65" },
  { name: "Meurtre dans l’obscurité", index: "66" },
  { name: "Coup de théâtre", index: "67" },
  { name: "Le Mystère du baron noir", index: "68" },
  { name: "Le Mystère du baron noir", index: "69" },
  { name: "Le Mystère du baron noir", index: "70" },
  { name: "Filature ratée", index: "71" },
  { name: "Un meurtre pour trois", index: "72" },
  { name: "Meurtre sur l’épave", index: "73" },
  { name: "Le Mystère de Jinnai", index: "74" },
  { name: "Meurtre d’un créancier", index: "75" },
  { name: "Conan contre le Kid Cat Burglar", index: "76" },
  { name: "Un mariage jeté au feu", index: "77" },
  { name: "Un mariage jeté au feu", index: "78" },
  { name: "Cambriolage à la banque", index: "79" },
  { name: "L’Artiste clochard", index: "80" },
  { name: "L’Enlèvement", index: "81" },
  { name: "L’Enlèvement", index: "82" },
  { name: "Meurtre sans cadavre", index: "83" },
  { name: "Vacances à la neige", index: "84" },
  { name: "Vacances à la neige", index: "85" },
  { name: "Changer le cours des choses", index: " 86" },
  { name: "Les Grues sauvages d’Hokkaido", index: "87" },
  { name: "Le Meurtre de la villa Dracula", index: "88" },
  { name: "Le Meurtre de la villa Dracula", index: "89" },
  { name: "Meurtre au parfum", index: "90" },
  { name: "Le Voleur hospitalisé", index: "91" },
  { name: "Mortelle randonnée", index: "92" },
  { name: "Mortelle randonnée", index: "93" },
  { name: "Une silhouette dans la nuit", index: "94" },
  { name: "Un rendez-vous raté", index: "95" },
  { name: "Le Clou du spectacle", index: "96" },
  { name: "Vin mortel", index: "97" },
  { name: "Le Meurtre du céramiste", index: "98" },
  { name: "Le Meurtre du céramiste", index: "99" },
  { name: "Souvenir du premier amour", index: "100" },
  { name: "Souvenir du premier amour", index: "101" },
  { name: "Le Meurtre de l’acteur des films de samouraïs", index: "102" },
  { name: "Le Meurtre de l’acteur des films de samouraïs", index: "103" },
  { name: "La Maison aux pendules", index: "104" },
  { name: "La Maison aux pendules", index: "105" },
  { name: "Photos de meurtre", index: "106" },
  { name: "Le Taupe Master", index: "107" },
  { name: "Le Taupe Master", index: "108" },
  { name: "La Voiture fantôme", index: "109" },
  { name: "Meurtre à l’école de cuisine", index: "110" },
  { name: "Meurtre à l’école de cuisine", index: "111" },
  { name: "Le Fantôme de l’école", index: "112" },
  { name: "Plage en deuil", index: "113" },
  { name: "L’Affaire du serpent de mer", index: "114" },
  { name: "L’Affaire du serpent de mer", index: "115" },
  { name: "La Disparition du mystérieux écrivain", index: "116" },
  { name: "La Disparition du mystérieux écrivain", index: "117" },
  { name: "Meurtres en série à Osaka", index: "118" },
  { name: "Meurtre au fan club de Kamen Yaïba", index: "119" },
  { name: "Un meurtre au goût de miel", index: "120" },
  { name: "L’Affaire des deux sœurs", index: "121" },
  { name: "L’Affaire des deux sœurs", index: "122" },
  { name: "Le Kidnapping de Mlle Météo", index: "123" },
  { name: "Le Mystérieux assassin", index: "124" },
  { name: "Le Mystérieux assassin", index: "125" },
  { name: "Meurtre au théâtre", index: "126" },
  { name: "Meurtre au théâtre", index: "127" },
  { name: "Le dixième braquage des hommes en noir", index: "128" },
  { name: "La nouvelle élève", index: "129" },
  { name: "Menace de meurtre aveugle au stade", index: "130" },
  { name: "Menace de meurtre aveugle au stade", index: "131" },
  { name: "Magic Party", index: "132" },
  { name: "Magic Party", index: "133" },
  { name: "Magic Party", index: "134" },
  { name: "Meurtre sans arme", index: "135" },
  { name: "Le vieux château", index: "136" },
  { name: "Le vieux château", index: "137" },
  { name: "La dernière séance", index: "138" },
  { name: "La dernière séance", index: "139" },
  { name: "Mission : sauver Ayumi", index: "140" },
  { name: "Intrigue nuptiale", index: "141" },
  { name: "Intrigue nuptiale", index: "142" },
  { name: "La nuit des étoiles", index: "143" },
  { name: "Le meurtre de « l’étoile du Nord »", index: "144" },
  { name: "Le meurtre de « l’étoile du Nord »", index: "145" },
  { name: "L’histoire d’amour d’un détective", index: "146" },
  { name: "L’histoire d’amour d’un détective", index: "147" },
  { name: "L’affaire du tramway", index: "148" },
  { name: "Meurtre au parc d’attractions", index: "149" },
  { name: "Meurtre à la voiture piégée", index: "150" },
  { name: "Meurtre à la voiture piégée", index: "151" },
  { name: "La disparition du vieil homme", index: "152" },
  { name: "Dangereux été pour Sonoko", index: "153" },
  { name: "Dangereux été pour Sonoko", index: "154" },
  { name: "Un mystérieux suicide", index: "155" },
  { name: "L’histoire d’amour d’un détective 2", index: "156" },
  { name: "L’histoire d’amour d’un détective 2", index: "157" },
  { name: "La ligne sans fin", index: "158" },
  { name: "La légende de la mystérieuse 5ème pagode", index: "159" },
  { name: "La légende de la mystérieuse 5ème pagode", index: "160" },
  { name: "La mort arrive par les eaux", index: "161" },
  { name: "Meurtre dans les nuages", index: "162" },
  { name: "La lune, les étoiles et le soleil", index: "163" },
  { name: "La lune, les étoiles et le soleil", index: "164" },
  { name: "La disparition du Club des détectives junior", index: "165" },
  { name: "Le manoir de l’araignée", index: "166" },
  { name: "Le manoir de l’araignée", index: "167" },
  { name: "Le manoir de l’araignée", index: "168" },
  { name: "Le baiser de Venus", index: "169" },
  { name: "Un bain néfaste", index: "170" },
  { name: "Un bain néfaste", index: "171" },
  { name: "Le message de mort", index: "172" },
  { name: "Le message de mor", index: "173" },
  { name: "Meurtre sur le Symphony", index: "174" },
  { name: "L’homme qu’on a tué quatre fois", index: "175" },
  { name: "Les hommes en noir", index: "176" },
  { name: "Les hommes en noir", index: "177" },
  { name: "Les hommes en noir", index: "178" },
  { name: "Le camion fou", index: "179" },
  { name: "La chanson maléfique", index: "180" },
  { name: "La chanson maléfique", index: "181" },
  { name: "À la recherche des neuf portes", index: "182" },
  { name: "Recette dangereuse", index: "183" },
  { name: "La malédiction des masques", index: "184" },
  { name: "Meurtre d’un détective célèbre", index: "185" },
  { name: "Meurtre d’un détective célèbre", index: "186" },
  { name: "Coup de feu dans la nuit", index: "187" },
  { name: "Retour dangereux… Descente aux enfers", index: "188" },
  { name: "Retour dangereux… Le piège se referme", index: "189" },
  { name: "Retour dangereux… Le 3ème choix", index: "190" },
  { name: "Retour dangereux… Le chevalier noir", index: "191" },
  { name: "Retour dangereux… Le retour de Shinichi", index: "192" },
  { name: "Retour dangereux… Sur le lieu des serments", index: "193" },
  { name: "La boîte à musique", index: "194" },
  { name: "La boîte à musique", index: "195" },
  { name: "La première affaire de Ran", index: "196" },
  { name: "Mort d’un collectionneur", index: "197" },
  { name: "Mort d’un collectionneur", index: "198" },
  { name: "Kogoro accusé de meurtre", index: "199" },
  { name: "Kogoro accusé de meurtre", index: "200" },
  { name: "Le 10ème passager", index: "201" },
  { name: "Le 10ème passager", index: "202" },
  { name: "Les ailes noires d’Icare", index: "203" },
  { name: "Les ailes noires d’Icare", index: "204" },
  { name: "Romance au quartier général III", index: "205" },
  { name: "Romance au quartier général III", index: "206" },
  { name: "Élémentaire mon cher Conan", index: "207" },
  { name: "La malédiction", index: "208" },
  { name: "Chute libre en pleine montagne", index: "209" },
  { name: "Le palais aquatique aux cinq couleurs", index: "210" },
  { name: "Le palais aquatique aux cinq couleurs", index: "211" },
  { name: "La chasse à l’ours", index: "212" },
  { name: "La chasse à l’ours", index: "213" },
  { name: "Le mystère de la chambre rétro", index: "214" },
  { name: "La baie de la revanche", index: "215" },
  { name: "La baie de la revanche", index: "216" },
  { name: "Les secrets enfouis de Megure", index: "217" },
  { name: "Les secrets enfouis de Megure", index: "218" },
  {
    name: "La réunion des détectives ! Shinichi Kudo contre le Kid Cat Burglar",
    index: "219",
  },
  { name: "Un client mensonger 1re partie", index: "220" },
  { name: "Un client mensonger 2e partie", index: "221" },
  {
    name: "Ensuite, il n’y eut plus de sirènes 1re partie : L’affaire",
    index: "222",
  },
  {
    name: "Ensuite, il n’y eut plus de sirènes 2e partie : Les déductions",
    index: "223",
  },
  {
    name: "Ensuite, il n’y eut plus de sirènes 3e partie : La résolution",
    index: "224",
  },
  { name: "Le secret d’un business prospère", index: "225" },
  { name: "Le piège du jeu de combat", index: "226" },
  { name: "Le piège du jeu de combat", index: "227" },
  { name: "La classe de poterie meurtrière", index: "228" },
  { name: "La classe de poterie meurtrière", index: "229" },
  { name: "Le mystérieux passager", index: "230" },
  { name: "Le mystérieux passager", index: "231" },
  { name: "L’affaire de la chute d’un immeuble", index: "232" },
  { name: "La preuve n’a pas disparu", index: "233" },
  { name: "La preuve n’a pas disparu", index: "234" },
  { name: "La cave à vin fermée", index: "235" },
  { name: "La mystérieuse visite de la plage de Nanki", index: "236" },
  { name: "La mystérieuse visite de la plage de Nanki", index: "237" },
  { name: "L’affaire des 3 K d’Osaka", index: "238" },
  { name: "L’affaire des 3 K d’Osaka", index: "239" },
  { name: "L’affaire de la balle dans un train", index: "240" },
  { name: "L’affaire du transport dans un train", index: "241" },
  { name: "Le désastre de Genta", index: "242" },
  { name: "L’imposteur de Kogoro Mouri", index: "243" },
  { name: "L’imposteur de Kogoro Mouri", index: "244" },
  { name: "Coup de feu dans le Bâtiment du Tournesol", index: "245" },
  { name: "Le mystère du filet", index: "246" },
  { name: "Le mystère du filet", index: "247" },
  { name: "L’alibi de la forêt chassée", index: "248" },
  { name: "Le secret de la Star", index: "249" },
  { name: "Le secret de la Star", index: "250" },
  { name: "La tragédie à Ok Corral", index: "251" },
  { name: "Le kidnappeur dans la photo", index: "252" },
  { name: "Romance au quartier général IV", index: "253" },
  { name: "Romance au quartier général IV", index: "254" },
  { name: "Le 14ème concours de vers lié de Matsue Tamazo", index: "255" },
  { name: "Le 14ème concours de vers lié de Matsue Tamazo", index: "256" },
  { name: "La mystérieuse punition du ciel", index: "257" },
  { name: "L’homme de Chicago", index: "258" },
  { name: "L’homme de Chicago", index: "259" },
  { name: "Le restaurant tremblant", index: "260" },
  { name: "La légende de la nuit enneigée", index: "261" },
  { name: "La légende de la nuit enneigée", index: "262" },
  {
    name: "Le double mystère d’Osaka : Le Sabreur et le Château de Toyotomi (épisode special)",
    index: "263",
  },
  { name: "La salle de combat : Eri Kisaki VS Kogoro Mouri", index: "264" },
  { name: "La salle de combat : Eri Kisaki VS Kogoro Mouri", index: "265" },
  { name: "Le secret de la Saint Valentin", index: "266" },
  { name: "Le secret de la Saint Valentin", index: "267" },
  { name: "Le secret de la Saint Valentin", index: "268" },
  { name: "L’oubli du memento du crime", index: "269" },
  { name: "L’oubli du memento du crime", index: "270" },
  { name: "Le secret expédié par l’oubli", index: "271" },
  { name: "Le secret expédié par l’oubli", index: "272" },
  { name: "Le quiz d’Oba-San, le cas d’Indication de Fléchette", index: "273" },
  { name: "La vérité de la maison hantée", index: "274" },
  { name: "La vérité de la maison hantée", index: "275" },
  { name: "La disparition du bloc note du policier", index: "276" },
  {
    name: "Le Professeur d’Anglais contre le Détective de l’Ouest",
    index: "277",
  },
  {
    name: "Le Professeur d’Anglais contre le Détective de l’Ouest",
    index: "278",
  },
  { name: "Le labyrinthe de Hooligan", index: "279" },
  { name: "Le labyrinthe de Hooligan", index: "280" },
  { name: "Peu de témoins", index: "281" },
  {
    name: "L’eau mystérieuse coulant près de la pierre du jardin",
    index: "282",
  },
  {
    name: "L’eau mystérieuse coulant près de la pierre du jardin",
    index: "283",
  },
  { name: "Le quartier de Chine sous la pluie", index: "284" },
  { name: "Le quartier de Chine sous la pluie", index: "285" },
  { name: "Shinichi Kudo à New-York", index: "286" },
  { name: "Shinichi Kudo à New-York", index: "287" },
  { name: "Shinichi Kudo à New-York", index: "288" },
  { name: "Mitsuhiko, imposteur de la Forêt", index: "289" },
  { name: "Mitsuhiko, imposteur de la Forêt", index: "290" },
  {
    name: "L’isolement de l’île de la princesse et le palais du grand Dragon",
    index: "291",
  },
  {
    name: "L’isolement de l’île de la princesse et le palais du grand Dragon",
    index: "292",
  },
  {
    name: "L’isolement de l’île de la princesse et le palais du grand Dragon",
    index: "293",
  },
  { name: "L’éclat de l’amour et de la détermination", index: "294" },
  { name: "L’éclat de l’amour et de la détermination", index: "295" },
  { name: "La péniche au bout du choc", index: "296" },
  {
    name: "Cour de confrontation II : Eri Kisaki contre Kujo Reiko",
    index: "297",
  },
  {
    name: "Cour de confrontation II : Eri Kisaki contre Kujo Reiko",
    index: "298",
  },
  {
    name: "Le détroit de l’amitié de Kanmon et l’intention infernale",
    index: "299",
  },
  {
    name: "Le détroit de l’amitié de Kanmon et l’intention infernale",
    index: "300",
  },
  { name: "L’affection du bonheur et du malheur", index: "301" },
  { name: "L’affection du bonheur et du malheur", index: "302" },
  { name: "Le retour de la victime", index: "303" },
  {
    name: "Le QG de la Police Métropolitaine tremble — Les 12 millions d’otages (épisode spécial)",
    index: "304",
  },
  { name: "Le suspect invisible", index: "305" },
  { name: "Le suspect invisible", index: "306" },
  { name: "L’empreinte sombre", index: "307" },
  { name: "L’empreinte sombre", index: "308" },
  { name: "Contact avec l’Organisation des Hommes en Noir", index: "309" },
  { name: "Contact avec l’Organisation des Hommes en Noir", index: "310" },
  { name: "Contact avec l’Organisation des Hommes en Noir", index: "311" },
  {
    name: "Le festival des poupées teintes au coucher du soleil",
    index: "312",
  },
  {
    name: "Le festival des poupées teintes au coucher du soleil",
    index: "313",
  },
  { name: "La cloture cassée de l’observatoire", index: "314" },
  { name: "La place exposée au soleil", index: "315" },
  { name: "Le masque du héros terni", index: "316" },
  { name: "Le masque du héros terni", index: "317" },
  { name: "L’affaire du cigare du fortuné", index: "318" },
  { name: "L’affaire du cigare du fortuné", index: "319" },
  { name: "L’art du Ninja", index: "320" },
  { name: "Le ravisseur disparu de la voiture", index: "321" },
  { name: "Le ravisseur disparu de la voiture", index: "322" },
  { name: "La situation désespérée de Heiji Hattori", index: "323" },
  { name: "La situation désespérée de Heiji Hattori", index: "324" },
  { name: "Le cheval rouge dans les flammes", index: "325" },
  { name: "Le cheval rouge dans les flammes", index: "326" },
  { name: "Le cheval rouge dans les flammes", index: "327" },
  { name: "Le mystère de l’anniversaire du vin", index: "328" },
  { name: "Amitié bafouée", index: "329" },
  { name: "Amitié bafouée", index: "330" },
  { name: "Le curry piquant suspect", index: "331" },
  { name: "Le curry piquant suspect", index: "332" },
  { name: "Les princesses identiques", index: "333" },
  { name: "Les princesses identiques", index: "334" },
  { name: "Le secret du film Touto", index: "335" },
  { name: "Le secret du film Touto", index: "336" },
  { name: "Les circonstances cachées de l’accident", index: "337" },
  { name: "Les quatre Porsche", index: "338" },
  { name: "Les quatre Porsche", index: "339" },
  { name: "Le secret caché dans les toilettes", index: "340" },
  { name: "Le secret caché dans les toilettes", index: "341" },
  {
    name: "La nouvelle mariée de Huis Dix Bosch (épisode special)",
    index: "342",
  },
  { name: "Le piège de la superette", index: "343" },
  { name: "Le piège de la superette", index: "344" },
  { name: "Confrontation avec l’organisation (épisode spécial)", index: "345" },
  { name: "Retrouvez la marque sur les fesses", index: "346" },
  { name: "Retrouvez la marque sur les fesses", index: "347" },
  { name: "L’Amour, un Fantôme et l’héritage mondial", index: "348" },
  { name: "L’Amour, un Fantôme et l’héritage mondial", index: "349" },
  { name: "L’oubli du téléphone cellulaire", index: "350" },
  { name: "L’oubli du téléphone cellulaire", index: "351" },
  { name: "La tragédie du tournoi de clôture", index: "352" },
  { name: "La tragédie du tournoi de clôture", index: "353" },
  { name: "Un petit client", index: "354" },
  { name: "Un petit client", index: "355" },
  {
    name: "Le miracle de la promenade en plein air de Kaitô Kid (épisode special)",
    index: "356",
  },
  { name: "« Chéri » est une illusion du Printemps", index: "357" },
  { name: "Romance au quartier général V", index: "358" },
  { name: "Romance au quartier général V", index: "359" },
  { name: "Un scarabée printanier mystérieux", index: "360" },
  { name: "L’histoire fantomatique du Lycée Teitan", index: "361" },
  { name: "L’histoire fantomatique du Lycée Teitan", index: "362" },
  { name: "La ville des corbeaux", index: "363" },
  { name: "Le double meurtre", index: "364" },
  { name: "Le double meurtre", index: "365" },
  { name: "Une chambre secrète ouverte sur la mer", index: "366" },
  { name: "Une chambre secrète ouverte sur la mer", index: "367" },
  { name: "La maison aux friandises, l’antre d’une sorcière", index: "368" },
  { name: "Le suspens d’un homme chanceux", index: "369" },
  { name: "S’échappant dans un jeu", index: "370" },
  { name: "Un parcours sans contestation", index: "371" },
  { name: "Un parcours sans contestation", index: "372" },
  { name: "Le piège empoisonné de l’araignée", index: "373" },
  { name: "Plus secret qu’une étoile", index: "374" },
  { name: "Plus secret qu’une étoile", index: "375" },
  { name: "Quinze heures, dernier délai", index: "376" },
  { name: "Momotarou, une mystérieuse visite", index: "377" },
  { name: "Momotarou, une mystérieuse visite", index: "378" },
  {
    name: "Le Kimono « sleeved » caché à la source d’eau chaude durant une nuit enneigée",
    index: "379",
  },
  {
    name: "Le Kimono « sleeved » caché à la source d’eau chaude durant une nuit enneigée",
    index: "380",
  },
  { name: "A qui la vedette de la déduction ?", index: "381" },
  { name: "A qui la vedette de la déduction ?", index: "382" },
  {
    name: "Miracle au stade de baseball Koshien ! Les concurrents font face au Démon de l’Ombre (épisode special)",
    index: "383",
  },
  { index: "384 : La cible est Kogoro Mouri" },
  { name: "La dissonance du Stradivarius", index: "385" },
  { name: "La dissonance du Stradivarius", index: "386" },
  { name: "La dissonance du Stradivarius", index: "387" },
  { name: "Kogoro s’enivre à Satsuma", index: "388" },
  { name: "Kogoro s’enivre à Satsuma", index: "389" },
  { name: "Romance au quartier général VI", index: "390" },
  { name: "Romance au quartier général VI", index: "391" },
  { name: "La mystérieuse différence de taille de 20 cm", index: "392" },
  { name: "Un mystérieux kidnapping", index: "393" },
  { name: "Le manoir du Big Jewel", index: "394" },
  { name: "Le manoir du Big Jewel", index: "395" },
  { name: "Le manoir du Big Jewel", index: "396" },
  { name: "Un jus aigre-doux", index: "397" },
  { name: "La requête d’une étrange famille", index: "398" },
  { name: "La requête d’une étrange famille", index: "399" },
  { name: "Les soupçons de Ran", index: "400" },
  { name: "Le voleur de bijoux pris en flagrant délit", index: "401" },
  { name: "Le voleur de bijoux pris en flagrant délit", index: "402" },
  { name: "Le mystérieux château de l’ange", index: "403" },
  { name: "Le mystérieux château de l’ange", index: "404" },
  { name: "Un message de mort incompréhensible", index: "405" },
  { name: "La déduction magique de Conan et Heiji", index: "406" },
  { name: "La déduction magique de Conan et Heiji", index: "407" },
  { name: "La déduction magique de Conan et Heiji", index: "408" },
  { name: "Une étape simultanée et un enlèvement", index: "409" },
  { name: "Une étape simultanée et un enlèvement", index: "410" },
  { name: "Le lieu saint Shinto, le surprenant code de Torri", index: "411" },
  { name: "Le lieu saint Shinto, le surprenant code de Torri", index: "412" },
  { name: "Le mystère du crime presque parfait", index: "413" },
  {
    name: "Les Détectives Junior à la poursuite de l’oiseau bleu",
    index: "414",
  },
  {
    name: "L’apparition du mauvais esprit pendant un jour de malchance",
    index: "415",
  },
  {
    name: "L’apparition du mauvais esprit pendant un jour de malchance",
    index: "416",
  },
  {
    name: "L’apparition du mauvais esprit pendant un jour de malchance",
    index: "417",
  },
  { name: "Le grenier de la maison de Beika", index: "418" },
  { name: "L’épée du serpent à huit têtes", index: "419" },
  { name: "L’épée du serpent à huit têtes", index: "420" },
  { name: "Le premier amour de la couleur du Ginkgo", index: "421" },
  { name: "Le premier amour de la couleur du Ginkgo", index: "422" },
  { name: "Les détectives et les 4 frères Aomushi", index: "423" },
  { name: "Photo numérique du clown", index: "424" },
  {
    name: "Black Impact : Quand le bras de l’Organisation vous atteint (épisode spécial)",
    index: "425",
  },
  { name: "Une lettre d’amour pour Ran", index: "426" },
  { name: "Le grand secret du chemin de l’école", index: "427" },
  { name: "Le grand secret du chemin de l’école", index: "428" },
  { name: "Deux personnes qui ne peuvent revenir", index: "429" },
  { name: "Deux personnes qui ne peuvent revenir", index: "430" },
  { name: "Romance au quartier général VII", index: "431" },
  { name: "Romance au quartier général VII", index: "432" },
  { name: "Conan, un étrange enfant", index: "433" },
  { name: "L’accomplissement du célèbre Cool Dog", index: "434" },
  { name: "L’interview des Détectives Junior", index: "435" },
  { name: "L’interview des Détectives Junior", index: "436" },
  {
    name: "Aya Ueto et Shinichi : La promesse d’il y a quatre ans",
    index: "437",
  },
  { name: "La poursuite d’un courrier poisson", index: "438" },
  {
    name: "Et ce serait agréable si tout le monde disparaissait",
    index: "439",
  },
  { name: "L’extrême limite de la voiture de cascade", index: "440" },
  { name: "Le Ahh en fin de vie", index: "441" },
  { name: "L’homme obstrué par la charpente d’acier", index: "442" },
  { name: "Ramassage de coquillage par marée soupirante", index: "443" },
  { name: "Ramassage de coquillage par marée soupirante", index: "444" },
  { name: "Le secret du Russian Blue", index: "445" },
  { name: "La fenêtre occidentale scellée", index: "446" },
  { name: "Le fenêtre occidentale scellée", index: "447" },
  { name: "L’affaire du Saury aux yeux noirs", index: "448" },
  {
    name: "Romance au quartier général : Le faux mariage (épisode special)",
    index: "449",
  },
  { name: "Tour VS magie", index: "450" },
  { name: "Tour VS magie", index: "451" },
  {
    name: "La mystérieuse personne de Konpira (épisode special)",
    index: "452",
  },
  {
    name: "Une réunion d’avant-première de l’amitié et du destin",
    index: "453",
  },
  { name: "Résultat inversé", index: "454" },
  { name: "Résultat inversé", index: "455" },
  { name: "Le mystère que nous aimons", index: "456" },
  { name: "Le mouchoir rouge de Sonoko", index: "457" },
  { name: "Le mouchoir rouge de Sonoko", index: "458" },
  {
    name: "Une mystérieuse personne, l’homme des règlements stricts",
    index: "459",
  },
  { name: "La grande stratégie de la classe 1-B", index: "460" },
  { name: "La page manquante", index: "461" },
  { name: "L’ombre de l’Organisation Noire : Le jeune témoin", index: "462" },
  {
    name: "L’ombre de l’Organisation Noire : L’étrange illumination",
    index: "463",
  },
  {
    name: "L’ombre de l’Organisation Noire : Le mystère de la récompense",
    index: "464",
  },
  {
    name: "L’ombre de l’Organisation Noire : La brillante étoile de perle",
    index: "465",
  },
  { name: "Le bonhomme de neige indestructible", index: "466" },
  { name: "Le bonhomme de neige indestructible", index: "467" },
  { name: "Mystère près d’un étang", index: "468" },
  { name: "Kaitô Kid et les 4 chefs-d’œuvre", index: "469" },
  { name: "Kaitô Kid et les 4 chefs d’œuvre", index: "470" },
  { name: "L’incontrôlable voiture de location", index: "471" },
  { name: "Les aventures du jeune Shinichi Kudo", index: "472" },
  { name: "Les aventures du jeune Shinichi Kudo", index: "473" },
  { name: "L’amour de Maître Eri Kisaki", index: "474" },
  { name: "Grand prix d’infortune", index: "475" },
  { name: "Le shoot de Genta", index: "476" },
  { name: "Le shoot de Genta", index: "477" },
  { name: "30 minutes réelles", index: "478" },
  { name: "Trois jours avec Heiji Hattori (épisode special)", index: "479" },
  { name: "Un alibi jaune", index: "480" },
  { name: "La coutellerie de la sorcière des montagnes", index: "481" },
  { name: "La coutellerie de la sorcière des montagnes", index: "482" },
  { name: "Le policier disparu", index: "483" },
  { name: "L’emplacement de la photographie noire", index: "484" },
  { name: "L’emplacement de la photographie noire", index: "485" },
  { name: "Appelant le chat de droite à gauche", index: "486" },
  {
    name: "Romance au quartier général VIII : la bague de fiançailles (épisode special)",
    index: "487",
  },
  {
    name: "Le démon des studios de télévision (épisode special)",
    index: "488",
  },
  {
    name: "Cour de confrontation III : un avocat comme témoin oculaire",
    index: "489",
  },
  {
    name: "Heiji Hattori vs Shinichi Kudô – Duel de déduction sur la piste de ski (épisode special)",
    index: "490",
  },
  {
    name: "La confrontation du rouge et du noir : Le commencement",
    index: "491",
  },
  { name: "Confrontation Rouge contre Noir : Les liens du sang", index: "492" },
  { name: "Confrontation Rouge contre Noir : Exclamation", index: "493" },
  { name: "Confrontation Rouge contre Noir : Hadès", index: "494" },
  { name: "Confrontation Rouge contre Noir : Coma", index: "495" },
  { name: "Confrontation Rouge contre Noir : Invasion", index: "496" },
  { name: "Confrontation Rouge contre Noir : Réveil", index: "497" },
  { name: "Confrontation Rouge contre Noir : Troubles", index: "498" },
  { name: "Confrontation Rouge contre Noir : Déguisement", index: "499" },
  { name: "Confrontation Rouge contre Noir : Testament", index: "500" },
  { name: "Confrontation Rouge contre Noir : Soupçons", index: "501" },
  { name: "Confrontation Rouge contre Noir : Innocence", index: "502" },
  { name: "Confrontation Rouge contre Noir : Prêt à mourir", index: "503" },
  {
    name: "Confrontation Rouge contre Noir : Tué dans l’exercice de ses fonctions",
    index: "504",
  },
  { name: "Le témoignage de Maître Eri Kisaki", index: "505" },
  { name: "Le témoignage de Maître Eri Kisaki", index: "506" },
  { name: "Angle mort dans un Karaoké", index: "507" },
  { name: "Angle mort dans un Karaoké", index: "508" },
  { name: "Rouge, Blanc, Jaune et les Détectives Junior", index: "509" },
  { name: "Conan contre le Mystère du code W", index: "510" },
  {
    name: "Comparaison de déduction : Shinichi contre Okiya Subaru",
    index: "511",
  },
  { name: "L’horoscope cassé", index: "512" },
  { name: "Un café à l’envie de meurtre", index: "513" },
  { name: "Un café à l’envie de meurtre", index: "514" },
  {
    name: "La téléportation magique de Kaitô Kid (épisode special)",
    index: "515",
  },
  {
    name: "Fuurinkazan — Le mystérieux guerrier en armure (épisode special)",
    index: "516",
  },
  { name: "La fin du Fuurinkazan, l’Ombre et la Foudre", index: "517" },
  { name: "Voyage surprise ! La restauration de Meiji", index: "518" },
  { name: "Voyage surprise ! La restauration de Meiji", index: "519" },
  { name: "L’accusation au vin rouge", index: "520" },
  { name: "Le meurtrier est Shinichi Kudo (épisode spécial)", index: "521" },
  {
    name: "Le véritable visage de Shinichi et les larmes de Ran (épisode special)",
    index: "522",
  },
  { name: "Ce qu’elle veut vraiment demander", index: "523" },
  { name: "L’étincelle bleue de la haine", index: "524" },
  { name: "L’étincelle bleue de la haine", index: "525" },
  { name: "L’étincelle bleue de la haine", index: "526" },
  { name: "La malice masquée", index: "527" },
  { name: "Une énigme résolue par la douceur", index: "528" },
  { name: "Une énigme résolue par la douceur", index: "529" },
  { name: "Ce que cache la légende urbaine", index: "530" },
  { name: "Ce que cache la légende urbaine", index: "531" },
  { name: "La cicatrice du premier amour", index: "532" },
  { name: "La cicatrice qui évoque le passé", index: "533" },
  { name: "Une nouvelle cicatrice et l’homme qui siffle", index: "534" },
  {
    name: "Une vieille cicatrice et l’esprit d’un Agent de Police",
    index: "535",
  },
  { name: "Le secret du chef-d’œuvre disparu", index: "536" },
  { name: "Kaitô Kid contre le plus robuste des coffres", index: "537" },
  { name: "Kaitô Kid contre le plus robuste des coffres", index: "538" },
  { name: "L’héritage d’un imbécile", index: "539" },
  {
    name: "Le jour où Kogoro Mouri cessa son activité de détective",
    index: "540",
  },
  {
    name: "Le jour où Kogoro Mouri cessa son activité de détective",
    index: "541",
  },
  { name: "Le poisson disparu du rocher Ikkaku ", index: "542" },
  { name: "Le poisson disparu du rocher Ikkaku", index: "543" },
  { name: "La main qui joue en désaccord", index: "544" },
  { name: "La Sorcière qui étouffait dans le brouillard", index: "545" },
  { name: "La Sorcière qui étouffait dans le brouillard", index: "546" },
  { name: "Deux jours avec le coupable (Première journée)", index: "547" },
  { name: "Deux jours avec le coupable (Deuxième journée)", index: "548" },
  { name: "Le mystère des sushis tournants", index: "549" },
  { name: "Le mystère des sushis tournants", index: "550" },
  { name: "Le coupable est le père de Genta", index: "551" },
  { name: "Le coupable est le père de Genta", index: "552" },
  { name: "La salle d’interrogatoire", index: "553" },
  { name: "Le voyage mystérieux de la cigogne", index: "554" },
  { name: "Le voyage mystérieux de la cigogne", index: "555" },
  { name: "L’intersection de la peur", index: "556" },
  { name: "Voyage avec un couple dangereux", index: "557" },
  { name: "La Maison de la Mort et le Mur Rouge (L’invitation)", index: "558" },
  { name: "La Maison de la Mort et le Mur Rouge (Dans la main)", index: "559" },
  {
    name: "La Maison de la Mort et le Mur Rouge (Le défunt Koumei)",
    index: "560",
  },
  {
    name: "La Maison de la Mort et le Mur Rouge (Stratégie du Fort vide)",
    index: "561",
  },
  { index: "562. L’enlèvement de l’arc-en-ciel" },
  {
    name: "Les Détectives Junior contre le gang des braqueurs (Tumulte)",
    index: "563",
  },
  {
    name: "Les Détectives Junior contre le gang des braqueurs (Silence)",
    index: "564",
  },
  { name: "Le témoin qui n’a rien vu", index: "565" },
  { name: "Le partenaire est Santa-san", index: "566" },
  { name: "Un meurtre lors d’un bain en plein air", index: "567" },
  { name: "L’Inspecteur Shiratori et les souvenirs de Sakura", index: "568" },
  { name: "L’Inspecteur Shiratori et les souvenirs de Sakura", index: "569" },
  { name: "Le crime aucune preuves", index: "570" },
  { name: "Chasse au trésor dans un entrepôt hanté", index: "571" },
  { name: "Chasse au trésor dans un entrepôt hanté", index: "572" },
  { name: "À la recherche d’un talisman disgracié", index: "573" },
  { name: "À la recherche d’un talisman disgracié", index: "574" },
  { name: "L’alibi de la robe noire", index: "575" },
  { name: "L’alibi de la robe noire", index: "576" },
  { name: "La vérité dévoilée par les lucioles", index: "577" },
  { name: "Présage d’un appel à l’alerte rouge", index: "578" },
  { name: "La suggestion du treizième homme en noir", index: "579" },
  { name: "Le temps limité de l’approche des hommes en noir", index: "580" },
  { name: "La cible teinte en rouge", index: "581" },
  { name: "Le zombie mourant la nuit", index: "582" },
  { name: "Les amours du professeur Kobayashi", index: "583" },
  { name: "Le cœur brisé de l’inspecteur Shiratori", index: "584" },
  {
    name: "Surmonter le temps des amours avec les cerisiers en fleur",
    index: "585",
  },
  { name: "La corne de Kirin a disparu dans l’obscurité", index: "586" },
  {
    name: "Le Kid face aux quatre esprits des Détectives Junior",
    index: "587",
  },
  { name: "Le piège du toit de la ferme", index: "588" },
  { name: "Le pire des anniversaires", index: "589" },
  { name: "Le pire des anniversaires", index: "590" },
  { name: "La maison-aquarium", index: "591" },
  { name: "L’affaire du singe et du râteau du festival du coq", index: "592" },
  { name: "L’affaire du singe et du râteau du festival du coq", index: "593" },
  { name: "Voyage surprise à Hiroshima", index: "594" },
  { name: "Voyage surprise à Miyajima", index: "595" },
  { name: "Effondrement d’un alibi", index: "596" },
  { name: "Le scénario de la chambre close fumante", index: "597" },
  { name: "Le scénario de la chambre close fumante", index: "598" },
  { name: "L’ami de la justice", index: "599" },
  { name: "Le rêve de la Kappa", index: "600" },
  { name: "Le rêve de la Kappa", index: "601" },
  { name: "Le diable caché sur le court de tennis", index: "602" },
  {
    name: "L’affaire de la séance de spiritisme dans la double salle verrouillée",
    index: "603",
  },
  {
    name: "L’affaire de la séance de spiritisme dans la double salle verrouillée",
    index: "604",
  },
  {
    name: "L’affaire de la séance de spiritisme dans la double salle verrouillée",
    index: "605",
  },
  { name: "Cour de Confrontation IV : Le Juge Kobayashi Sumiko", index: "606" },
  { name: "Cour de Confrontation IV : Le Juge Kobayashi Sumiko", index: "607" },
  { name: "Le jour blanc de la trahison", index: "608" },
  { name: "Le jour blanc de la trahison", index: "609" },
  { name: "La victime est Shinichi Kudo", index: "610" },
  { name: "Château Inubushi, la flamme du Chien démon", index: "611" },
  { name: "Château Inubushi, la flamme du Chien démon", index: "612" },
  { name: "Château Inubushi, la flamme du Chien démon", index: "613" },
  { name: "Le secret du journal du musicien", index: "614" },
  { name: "Le secret du journal du musicien", index: "615" },
  {
    name: "Le livre des révélations de Holmes (Le disciple de Holmes)",
    index: "616",
  },
  {
    name: "Le livre des révélations de Holmes (L’amour c’est zéro)",
    index: "617",
  },
  { name: "Le livre des révélations de Holmes (Satan)", index: "618" },
  { name: "Le livre des révélations de Holmes (Code break)", index: "619" },
  {
    name: "Le livre des révélations de Holmes (La reine des courts de tennis)",
    index: "620",
  },
  {
    name: "Le livre des révélations de Holmes (zéro est le commencement)",
    index: "621",
  },
  { name: "Situation d’urgence 252", index: "622" },
  { name: "Situation d’urgence 252", index: "623" },
  { name: "La vidéo d’un premier amour", index: "624" },
  { name: "Le hurlement venant de la salle d’opération", index: "625" },
  { name: "Le hurlement venant de la salle d’opération", index: "626" },
  {
    name: "La bataille entre Conan et Kaitou Kid pour le trésor de Ryoma",
    index: "627",
  },
  {
    name: "La bataille entre Conan et Kaitou Kid pour le trésor de Ryoma",
    index: "628",
  },
  { name: "L’affaire du tournage de la vidéo promotionnelle", index: "629" },
  { name: "L’affaire du tournage de la vidéo promotionnelle", index: "630" },
  { name: "Ce que l’horloge florale savait", index: "631" },
  { name: "L’épée du gardien du temps", index: "632" },
  { name: "L’épée du gardien du temps", index: "633" },
  { name: "La scène du crime est un restaurant étroit", index: "634" },
  { name: "Méfiez-vous du régime alimentaire", index: "635" },
  { name: "L’affaire de la leçon la plus précieuse au monde", index: "636" },
  { name: "L’affaire de la leçon la plus précieuse au monde", index: "637" },
  {
    name: "Résoudre le mystère dans le palais des feuilles d’automne",
    index: "638",
  },
  {
    name: "Résoudre le mystère dans le palais des feuilles d’automne",
    index: "639",
  },
  { name: "La tournée des huit pièces de souvenirs (Okayama)", index: "640" },
  { name: "La tournée des huit pièces de souvenirs (Kurashiki)", index: "641" },
  { name: "Moment critique lors d’une partie de karuta", index: "642" },
  { name: "Moment critique lors d’une partie de karuta", index: "643" },
  { name: "Des ramen si bons qu’on en mourrait", index: "644" },
  { name: "Des ramen si bons qu’on en mourrait", index: "645" },
  { name: "Épreuve de déductions entre détectives", index: "646" },
  { name: "Épreuve de déductions entre détectives", index: "647" },
  {
    name: "Prise d’otage à l’agence du détective Mri — Déclenchement",
    index: "648",
  },
  {
    name: "Prise d’otage à l’agence du détective Mri — Embuscade",
    index: "649",
  },
  { name: "Prise d’otage à l’agence du détective Mri — Final", index: "650" },
  {
    name: "Conan contre Heiji, l’épreuve de déductions entre les détectives de l’Est et de l’Ouest",
    index: "651",
  },
  { name: "Mélange de poison et d’illusion", index: "652" },
  { name: "Mélange de poison et d’illusion", index: "653" },
  { name: "Mélange de poison et d’illusion", index: "654" },
  { name: "Mélange de poison et d’illusion", index: "655" },
  { name: "Le site-web vidéo du professeur", index: "656" },
  { name: "Le site-web vidéo du professeur", index: "657" },
  { name: "Le piège brûlant du chocolat", index: "658" },
  { name: "Enquête commune avec un premier amour", index: "659" },
  { name: "Enquête commune avec un premier amour", index: "660" },
  { name: "Kogor est une bonne personne", index: "661" },
  { name: "Kogor est une bonne personne", index: "662" },
  { name: "Chassez la lucane cerf-volant de Miyama", index: "663" },
  { name: "La victoire du courageux chien Cœur 2", index: "664" },
  { name: "Un K initial suspect", index: "665" },
  { name: "Un intimidateur un soir de pluie", index: "666" },
  { name: "Veille de mariage", index: "667" },
  { name: "Veille de mariage", index: "668" },
  { name: "Le trésor de la tour des ténèbres", index: "669" },
  { name: "Le trésor de la tour des ténèbres", index: "670" },
  { name: "La nuit des détectives — Incident", index: "671" },
  { name: "La nuit des détectives — Enlèvement", index: "672" },
  { name: "La nuit des détectives — Raisonnement", index: "673" },
  { name: "La nuit des détectives — Bourbon", index: "674" },
  { name: "À un millimètre de l’impardonnable", index: "675" },
  { name: "À un millimètre de l’impardonnable", index: "676" },
  { name: "La plage de sable sans empreintes", index: "677" },
  { name: "Le mystère du Théâtre Nagasaki — L’ére Bakumatsu", index: "678" },
  { name: "Le mystère du Théâtre Nagasaki — L’ére de nos jours", index: "679" },
  { name: "Rhapsodie du cactus", index: "680" },
  {
    name: "La retransmission d’un amour périlleux : Début de la retransmission",
    index: "681",
  },
  {
    name: "La retransmission d’un amour périlleux : Situation désespérée",
    index: "682",
  },
  {
    name: "La retransmission d’un amour périlleux : Irruption sur scène",
    index: "683",
  },
  { name: "Mousse, vapeur et fumée", index: "684" },
  { name: "Mousse, vapeur et fumée", index: "685" },
  { name: "Une voiture transportant une bombe à retardement", index: "686" },
  { name: "L’insoluble piège congelé", index: "687" },
  { name: "L’inspecteur Takagi a trouvé 30 millions de Yens", index: "688" },
  { name: "Le message d’un client", index: "689" },
  { name: "L’affaire non-résolue de Ysaku Kud", index: "690" },
  { name: "L’affaire non-résolue de Ysaku Kud", index: "691" },
  {
    name: "La route de nuit des fleurs de cerisiers de la rivière Sumida",
    index: "692",
  },
  {
    name: "La route de nuit des fleurs de cerisiers de la rivière Sumida",
    index: "693",
  },
  {
    name: "Les confiseries japonaises disparues dans l’ancien magasin",
    index: "694",
  },
  { name: "Les roses du vignoble", index: "695" },
  {
    name: "La conspiration du ravageur des par-terres de fleurs",
    index: "696",
  },
  { name: "La fenêtre de l’école pour femmes", index: "697" },
  { name: "Incroyable ! L’affaire du crash d’un OVNI", index: "698" },
  { name: "L’ombre approchant le secret d’Haibara", index: "699" },
  { name: "L’ombre approchant le secret d’Haibara", index: "700" },
  { name: "Mystery Train : Tous à bord", index: "701" },
  { name: "Mystery Train: Tunnel", index: "702" },
  { name: "Mystery Train: Intersection", index: "703" },
  { name: "Mystery Train: Terminus", index: "704" },
  { name: "Conan dans la pièce verrouillée", index: "705" },
  { name: "Résolution du mystère face à Bourbon", index: "706" },
  { name: "Le grand détective équipé", index: "707" },
  { name: "L’homme est tombé lentement", index: "708" },
  { name: "Une affaire troublante non confirmée", index: "709" },
  { name: "Ce que tout le monde a vu", index: "710" },
  { name: "Ce que tout le monde a vu", index: "711" },
  { name: "Heiji Hattori et le manoir du vampire", index: "712" },
  { name: "Heiji Hattori et le manoir du vampire", index: "713" },
  { name: "Heiji Hattori et le manoir du vampire", index: "714" },
  { name: "Heiji Hattori et le manoir du vampire", index: "715" },
  {
    name: "Le fantôme dansant dans la demeure des masques de Nô",
    index: "716",
  },
  {
    name: "Le fantôme dansant dans la demeure des masques de Nô",
    index: "717",
  },
  { name: "Une trajectoire endiablée", index: "718" },
  { name: "Ticket gagnant pour l’enfer", index: "719" },
  { name: "Un Mystery Tour près du feu et de l’eau", index: "720" },
  { name: "Un Mystery Tour près du feu et de l’eau", index: "721" },
  { name: "Un service de livraison doux et glacial", index: "722" },
  { name: "Un service de livraison doux et glacial", index: "723" },
  { name: "Kaito Kid et la Blush Mermaid", index: "724" },
  { name: "Kaito Kid et la Blush Mermaid", index: "725" },
  { name: "Un message de fortune annonciateur d’un malheur", index: "726" },
  { name: "Un coffre au trésor fruité", index: "727" },
  { name: "Un coffre au trésor fruité", index: "728" },
  { name: "Diamant, tableau et actrice célèbre", index: "729" },
  { name: "La silhouette était trop parfaite", index: "730" },
  { name: "Le voisin de la scène de crime est mon ex-petit ami", index: "731" },
  { name: "Le voisin de la scène de crime est mon ex-petit ami", index: "732" },
  { name: "Un festin pour deux coups de feu", index: "733" },
  {
    name: "SP31 – Les souvenirs de Jodie et le piège des fleurs de cerisiers",
    index: "734",
  },
  { name: "Une invitation codée", index: "735" },
  { name: "Le secret de la statue de Kogoro Mouri", index: "736" },
  { name: "Une promenade suspecte", index: "737" },
  { name: "Kogoro dans un bar", index: "738" },
  { name: "Kogoro dans un bar", index: "739" },
  { name: "Ran évanouie dans une salle de bain", index: "740" },
  { name: "Ran évanouie dans une salle de bain", index: "741" },
  { name: "La promesse de la J", index: "742" },
  { name: "Une réussite à deux coïncidences", index: "743" },
  { name: "Le suspect est Makoto Kyogoku", index: "744" },
  { name: "Le suspect est Makoto Kyogoku", index: "745" },
  { name: "Kaito Kid VS Makoto Kyogoku", index: "746" },
  { name: "Kaito Kid VS Makoto Kyogoku", index: "747" },
  { name: "L’histoire d’amour d’un détective 9 – Confession", index: "748" },
  { name: "L’histoire d’amour d’un détective 9 – Vérité", index: "749" },
  { name: "L’homme trahi par la mer", index: "750" },
  { name: "Le chat qui rétracte ses griffes", index: "751" },
  { name: "Le chat qui rétracte ses griffes", index: "752" },
  { name: "L’angle mort de la maison commune", index: "753" },
  { name: "La tragédie de la femme en rouge – Brouillard", index: "754" },
  { name: "La tragédie de la femme en rouge – Mauvais esprit", index: "755" },
  { name: "La tragédie de la femme en rouge – Vengeance", index: "756" },
  { name: "L’humoriste qui s’était rendu", index: "757" },
  { name: "L’humoriste qui s’était rendu", index: "758" },
  { name: "La fin inattendue d’un roman d’amour", index: "759" },
  { name: "La fin inattendue d’un roman d’amour", index: "760" },
  {
    name: "Le mystere de la Tour de Kaga Hyakumangoku – À Kanagawa",
    index: "761",
  },
  {
    name: "Le mystere de la Tour de Kaga Hyakumangoku – Aux sources thermales de Kaga",
    index: "762",
  },
  { name: "Conan et Heiji : Le code de l’amour", index: "763" },
  { name: "Conan et Heiji : Le code de l’amour", index: "764" },
  { name: "Teimuzu rivière Case cerf-volant", index: "765" },
  { name: "Teimuzu rivière Case cerf-volant", index: "766" },
  { name: "L’amant disparu dans la tempête de neige", index: "767" },
  { name: "L’affaire de l’emprisonnement de Ai Haibara", index: "768" },
  { name: "Le patient d’urgence gênant", index: "769" },
  { name: "Un goûter tendu", index: "770" },
  { name: "Un goûter tendu", index: "771" },
  { name: "L’affaire à l’aquarium de Shinichi Kudo", index: "772" },
  { name: "L’affaire à l’aquarium de Shinichi Kudo", index: "773" },
  { name: "La disparition du « Cri » de Munch", index: "774" },
  { name: "Le grand détective manipulé", index: "775" },
  { name: "Le grand détective manipulé", index: "776" },
  { name: "Detective Boys contre Silver Detectives", index: "777" },
  { name: "L’ange qui a disparu dans un mirage", index: "778" },
  { name: "Un prologue écarlate", index: "779" },
  { name: "Une poursuite écarlate", index: "780" },
  { name: "Une interrogation écarlate", index: "781" },
  { name: "Un retour écarlate", index: "782" },
  { name: "Une vérité écarlate", index: "783" },
  { name: "Bienvenue au Club Orihime", index: "784" },
  { name: "Le match de l’amour du Taiko Meijin", index: "785" },
  { name: "Le match de l’amour du Taiko Meijin", index: "786" },
  { name: "Mystère estival au fond d’une piscine", index: "787" },
  { name: "Mystère estival au fond d’une piscine", index: "788" },
  { name: "La reine de la météo", index: "789" },
  { name: "Bekapon et la promo qui tue", index: "790" },
  { name: "L’inspecteur Takagi menotté et en cavale", index: "791" },
  { name: "Les trois premiers témoins sur les lieux", index: "792" },
  { name: "Les trois premiers témoins sur les lieux", index: "793" },
  { name: "Kogoro Mouri Garde du corps", index: "794" },
  { name: "Le secret de la jeune femme disparue", index: "795" },
  { name: "La stratégie du couple inséparable", index: "796" },
  { name: "La déduction incohérente de la femme imaginaire", index: "797" },
  { name: "La cible mobile", index: "798" },
  {
    name: "La bataille de Déduction des Détectives Juniors dans la chambre close",
    index: "799",
  },
  { name: "A la poursuite de 100 millions de yens", index: "800" },
  { name: "Jeu de piste à Tottori", index: "801" },
  { name: "Jeu de piste à Tottori", index: "802" },
  { name: "Une prévention du feu semée d’embûches", index: "803" },
  { name: "Conan, Ebizô et le mystère d’un classique du kabuki", index: "804" },
  { name: "Conan, Ebizô et le mystère d’un classique du kabuki", index: "805" },
  { name: "L’illusion du ventriloque", index: "806" },
  { name: "L’illusion du ventriloque", index: "807" },
  { name: "L’Auberge du Kamaitachi", index: "808" },
  { name: "L’Auberge du Kamaitachi", index: "809" },
  { name: "La police départementale plongée dans les Ténèbres", index: "810" },
  { name: "La police départementale plongée dans les Ténèbres", index: "811" },
  { name: "La police départementale plongée dans les Ténèbres", index: "812" },
  { name: "L’ombre qui épiait Amuro", index: "813" },
  { name: "Le meurtre à huit clos d’une actrice blogueuse", index: "814" },
  { name: "Le meurtre à huit clos d’une actrice blogueuse", index: "815" },
  { name: "Un extra-terrestre gentil mais malchanceux", index: "816" },
  { name: "La fiancée disparue", index: "817" },
  { name: "La poursuite enragée de Kogoro", index: "818" },
  { name: "La poursuite enragée de Kogoro", index: "819" },
  { name: "Les sept suspects dans un hall d’attente", index: "820" },
  { name: "Le secret du temple Dongara", index: "821" },
  { name: "Un couple tendancieux et suspect", index: "822" },
  { name: "Un couple tendancieux et suspect", index: "823" },
  { name: "Les détectives juniors s’abritent de la pluie", index: "824" },
  { name: "La renversante affaire du parc à marées", index: "825" },
  { name: "Beauté, Mensonges et Secret", index: "826" },
  { name: "Des râmen si bons qu’on en mourrait", index: "827" },
  { name: "Des râmen si bons qu’on en mourrait", index: "828" },
  { name: "Le mystérieux garçon", index: "829" },
  { name: "Le chalet entouré de zombies", index: "830" },
  { name: "Le chalet entouré de zombies", index: "831" },
  { name: "Le chalet entouré de zombies", index: "832" },
  { name: "Un grand détective a aussi des faiblesses", index: "833" },
  { name: "L’homme qui mourra deux fois", index: "834" },
  { name: "L’homme qui mourra deux fois", index: "835" },
  { name: "Tension dans un girls band", index: "836" },
  { name: "Tension dans un girls band", index: "837" },
  { name: "Mystérieuse affaire au Fluffy Balloon", index: "838" },
  { name: "La voix de Tengu résonne", index: "839" },
  { name: "Le dernier cadeau", index: "840" },
  { name: "L’intersection pluvieuse", index: "841" },
  { name: "Au tournant d’une balade en amoureux", index: "842" },
  { name: "Les Détectives Boys dans le brouillard", index: "843" },
  { name: "Les Détectives Boys dans le brouillard", index: "844" },
  { name: "Conan, piégé dans le noir", index: "845" },
  { name: "Conan, piégé dans le noir", index: "846" },
  { name: "Inspecteur Chiba et l’épineuse affaire d’Ovni", index: "847" },
  { name: "Inspecteur Chiba et l’épineuse affaire d’Ovni", index: "848" },
  { name: "Mot de passe de la déclaration de mariage", index: "849" },
  { name: "Mot de passe de la déclaration de mariage", index: "850" },
  { name: "Tour des enfers en amoureux – Beppu", index: "851" },
  { name: "Tour des enfers en amoureux – Oita", index: "852" },
  { name: "Souvenirs du groupe de cerisiers (La petite Ran)", index: "853" },
  {
    name: "Souvenirs du groupe de cerisiers (Le petit Shinichi)",
    index: "854",
  },
  { name: "Mystère de la ceinture noire disparue", index: "855" },
  { name: "Secret d’un couple notoire", index: "856" },
  { name: "L’étrange carrefour du quartier Beika", index: "857" },
  { name: "L’étrange carrefour du quartier Beika", index: "858" },
  { name: "L’obscure route de montagne", index: "859" },
  { name: "Le piège du système de sécurité", index: "860" },
  { name: "Une Scène de crime à l’identique 17 ans après", index: "861" },
  { name: "Une Scène de crime à l’identique 17 ans après", index: "862" },
  { name: "Le Meurtre du détective de l’âme", index: "863" },
  { name: "Le Meurtre du détective de l’âme", index: "864" },
  { name: "Le Médisant Mainate", index: "865" },
  { name: "Scène de trahison", index: "866" },
  { name: "Scène de trahison", index: "867" },
  { name: "Librairie ancienne et sifflet de train", index: "868" },
  { name: "La Disparition de Conan au bord d’une falaise", index: "869" },
  { name: "La Disparition de Conan au bord d’une falaise", index: "870" },
  { name: "L’Affaire Nobunaga 450", index: "871" },
  {
    name: "Conan, Heiji et la légende du Nue – 1re partie : le cri",
    index: "872",
  },
  {
    name: "Conan, Heiji et la légende du Nue – 2e partie : les griffures",
    index: "873",
  },
  {
    name: "Conan, Heiji et la légende du Nue –  3e partie : la résolution",
    index: "874",
  },
  { name: "L’étrange statue bouddhique prophétique", index: "875" },
  { name: "Le Témoin mécanique", index: "876" },
  { name: "Destins croisés", index: "877" },
  { name: "L’Angle mort de la cabine", index: "878" },
  { name: "L’Angle mort de la cabine", index: "879" },
  { name: "Les Detectives Boys et le manoir hanté", index: "880" },
  { name: "Le Magicien des vagues", index: "881" },
  { name: "Le Magicien des vagues", index: "882" },
  { name: "Le Poseur de bombes sorti d’un livre", index: "883" },
  { name: "Le Poseur de bombes sorti d’un livre", index: "884" },
  { name: "Résolution d’énigme au café Poirot", index: "885" },
  { name: "Résolution d’énigme au café Poirot", index: "886" },
  { name: "Kid l’Insaisissable et la boîte mécanique", index: "887" },
  { name: "Kid l’Insaisissable et la boîte mécanique", index: "888" },
  { name: "La Nouvelle Maîtresse et le squelette", index: "889" },
  { name: "La Nouvelle Maîtresse et le squelette", index: "890" },
  { name: "Le Mystérieux Tour Bakumatsu-Ishin – Yamaguchi", index: "891" },
  { name: "Le Mystérieux Tour Bakumatsu-Ishin – Hagi", index: "892" },
  { name: "Le Mystère du restaurant étoilé", index: "893" },
  { name: "Numéro de déduction au restaurant d’à côté", index: "894" },
  { name: "Numéro de déduction au restaurant d’à côté", index: "895" },
  { name: "La Femme à la main blanche", index: "896" },
  { name: "La Femme à la main blanche", index: "897" },
  { name: "Les Gâteaux ont fondu !", index: "898" },
  { name: "Les vociférations du véritable assassin", index: "899" },
  { name: "Résolution d’énigme à huis clos", index: "900" },
  { name: "Le SOS de Mme Kisaki", index: "901" },
  { name: "Le SOS de Mme Kisaki", index: "902" },
  { name: "Deux êtres semblables en perpétuel désaccord", index: "903" },
  { name: "Deux cadavres et une seule vérité", index: "904" },
  { name: "Un témoignage livré sept ans plus tard", index: "905" },
  { name: "Un témoignage livré sept ans plus tard", index: "906" },
  { name: "L’ange gardien de la J", index: "907" },
  { name: "Une amitié emportée par une rivière", index: "908" },
  { name: "Le Mystère de la tente enflammée", index: "909" },
  { name: "Le Mystère de la tente enflammée", index: "910" },
  { name: "La requête de l’Inspecteur Megure", index: "911" },
  { name: "Les Detective Boys, modèles d’une toile", index: "912" },
  { name: "Le Kidnapping de Conan", index: "913" },
  { name: "Le Kidnapping de Conan", index: "914" },
  { name: "Sonoko Suzuki, la détective lycéenne", index: "915" },
  { name: "Le Tournoi de Kendo de l’Amour et du Mystère", index: "916" },
  { name: "Le Tournoi de Kendo de l’Amour et du Mystère", index: "917" },
  { name: "Course poursuite en mini-voiture de patrouille !", index: "918" },
  { name: "La réunion secrète du trio de lycéennes au café", index: "919" },
  { name: "La réunion secrète du trio de lycéennes au café", index: "920" },
  { name: "Le Covoiturage Meurtrier", index: "921" },
  { name: "La Disparition des Detective Boys", index: "922" },
  { name: "Un Jour sans Conan", index: "923" },
  { name: "Le Coucher du Soleil dans un Champ de Mandarines", index: "924" },
  { name: "Une dragonne de téléphone qui tenait au cœur", index: "925" },
  { name: "Une dragonne de téléphone qui tenait au cœur", index: "926" },
  { name: "Le voyage scolaire écarlate (épisode spécial)", index: "927" },
  { name: "Le voyage scolaire écarlate (épisode spécial)", index: "928" },
  { name: "La Femme se tenant à la Fenêtre", index: "929" },
  { name: "La Femme se tenant à la Fenêtre", index: "930" },
  {
    name: "Le Mystery Tour de Kitakysh Baignant dans la Lumière et dans l’Océan",
    index: "931",
  },
  {
    name: "Le Mystery Tour de Kitakysh Baignant dans la Lumière et dans l’Océan",
    index: "932",
  },
  { name: "L’Affaire du Kidnapping du Pur-Sang", index: "933" },
  { name: "L’Affaire du Kidnapping du Pur-Sang", index: "934" },
  { name: "Le voyant et ses trois clients", index: "935" },
  { name: "Foire alimentaire et conspiration", index: "936" },
  { name: "Le Poing fatal du géant Talos", index: "937" },
  { name: "Le Poing fatal du géant Talos", index: "938" },
  { name: "Une funeste collecte de fossiles", index: "939" },
  { name: "La petite amie disparue", index: "940" },
  { name: "Trouvez Maria", index: "941" },
  { name: "Trouvez Maria", index: "942" },
  { name: "Une « Fashion Week » du troisième âge", index: "943" },
  { name: "Le prix à payer pour un « j’aime »", index: "944" },
  { name: "Le prix à payer pour un « j’aime »", index: "945" },
  { name: "La larme des Borgia ou le joyau maudit", index: "946" },
  { name: "La larme des Borgia ou le joyau maudit", index: "947" },
  { name: "L’homme écrasé par un dinosaure", index: "948" },
  { name: "Conseils et confidences radiophoniques – le défi", index: "949" },
  {
    name: "Conseils et confidences radiophoniques – la solution",
    index: "950",
  },
  { name: "Librairie ancienne et sifflet de train II", index: "951" },
  { name: "L’Énigme du cocktail", index: "952" },
  { name: "L’Énigme du cocktail", index: "953" },
  { name: "L’Énigme du cocktail", index: "954" },
  { name: "Le Secret des “humano-insectes”", index: "955" },
  { name: "L’Énigme du bateau-bus", index: "956" },
  { name: "L’Énigme du bateau-bus", index: "957" },
  { name: "Le Caniche et le Fusil à pompe", index: "958" },
  { name: "Le Caniche et le Fusil à pompe", index: "959" },
  { name: "La veuve et les Detective Boys", index: "960" },
  { name: "L’étrange affaire du “camping glamour”", index: "961" },
  { name: "La grande conférence du détective Mouri", index: "962" },
  { name: "La grande conférence du détective Mouri", index: "963" },
  { name: "La grande conférence du détective Mouri", index: "964" },
  { name: "Gomera, le monstre géant, contre Kamen Yaiba", index: "965" },
  { name: "Gomera, le monstre géant, contre Kamen Yaiba", index: "966" },
  { name: "Gomera, le monstre géant, contre Kamen Yaiba", index: "967" },
  { name: "Gomera, le monstre géant, contre Kamen Yaiba", index: "968" },
  { name: "Tourisme, intrigue et héritière de Kaga", index: "969" },
  { name: "Tourisme, intrigue et héritière de Kaga", index: "970" },
  { name: "La sécurité routière prise pour cible", index: "971" },
  { name: "La sécurité routière prise pour cible", index: "972" },
  { name: "La sécurité routière prise pour cible", index: "973" },
  { name: "La sécurité routière prise pour cible", index: "974" },
  { name: "Une énigmatique disparition", index: "975" },
  { name: "Enquête et poursuite en taxi", index: "976" },
  { name: "L’aquarium brisé", index: "977" },
  { name: "L’affaire résolue de la rive opposée", index: "978" },
  { name: "Le détective se fait balader", index: "979" },
  { name: "L’appel du crime parfait", index: "980" },
  { name: "Bienvenue à l’auberge ‘Botchan’", index: "981" },
  { name: "Bienvenue à l’auberge ‘Botchan’", index: "982" },
  { name: "Kid contre Kômei: les lèvres prises pour cible", index: "983" },
  { name: "Kid contre Kômei: les lèvres prises pour cible", index: "984" },
  { name: "Les deux faces d’une personne", index: "985" },
  { name: "Les deux faces d’une personne", index: "986" },
  { name: "Une festive dissolution d’entreprise", index: "987" },
  { name: "Querelle de jeunes femmes", index: "988" },
  { name: "Le journal d’enquête d’Ayumi", index: "989" },
  { name: "Tragédie automatique", index: "990" },
  { name: "Tragédie automatique", index: "991" },
  { name: "Trouble au café traditionnel", index: "992" },
  { name: "Makoto Kyôgoku, le remplaçant", index: "993" },
  { name: "Makoto Kyôgoku, le remplaçant", index: "994" },
  { name: "Makoto Kyôgoku, le remplaçant", index: "995" },
  { name: "Faucon habile cache le crime", index: "996" },
  { name: "Conspiration au village du sourire", index: "997" },
  { name: "La poêle à frire de la haine", index: "998" },
  { name: "Une gentillesse malvenue", index: "999" },
  {
    name: "Le meurtre de la ‘Sonate au clair de lune (remake de l’épisode 11)",
    index: "1000",
  },
] as { name: string; index: string }[];

export default names;
