const names = [
  { name: "Départ", index: "01" },
  { name: "Tir ouvert", index: "02" },
  { name: "Pari", index: "03" },
  { name: "Échec", index: "04" },
  { name: "Décision mortelle", index: "05" },
  { name: "Montée et chute", index: "06" },
  { name: "Proclamation", index: "07" },
  { name: "Coup écrasant", index: "08" },
  { name: "Résurrection", index: "09" },
  { name: "Messager", index: "10" },
  { name: "Réjouissance", index: "11" },
  { name: "Chute", index: "12" },
  { name: "Monstre", index: "13" },
  { name: "Fantôme", index: "14" },
  { name: "Cieux", index: "15" },
  { name: "Fureur", index: "16" },
  { name: "Conversation", index: "17" },
  { name: "Joué", index: "18" },
  { name: "Limite", index: "19" },
  { name: "Dieu féroce", index: "20" },
  { name: "Le sang du cœur", index: "21" },
  { name: "Punition", index: "22" },
  { name: "Tromperie", index: "23" },
  { name: "Conditions", index: "24" },
  { name: "Blême", index: "25" },
  { name: "Rémanence", index: "26" },
  { name: "Enfer souterrain", index: "27" },
  { name: "Les règles du jeu", index: "28" },
  { name: "Morceaux de chance", index: "29" },
  { name: "Les débuts d'un retour", index: "30" },
  { name: "Abus et endurance", index: "31" },
  { name: "La tempête descend", index: "32" },
  { name: "Dés magiques", index: "33" },
  { name: "Réciprocité divine", index: "34" },
  { name: "Cheers, and…", index: "35" },
  { name: "Le dernier pari", index: "36" },
  { name: "Joie et lamentation", index: "37" },
  { name: "Le ciel tombe, un homme tombe", index: "38" },
  { name: "Un indice", index: "39" },
  { name: "La route du survivant (Récapitulatif de la série)", index: "40" },
  { name: "Tout un acte", index: "41" },
  { name: "Le rideau se lève", index: "42" },
  { name: "Frappes inutiles", index: "43" },
  { name: "Porte inflexible", index: "44" },
  { name: "Route vers un miracle", index: "45" },
  { name: "Écart de destin", index: "46" },
  { name: "Victoire assurée", index: "47" },
  { name: "Le pouvoir de l'argent", index: "48" },
  { name: "Sur la glace fine", index: "49" },
  { name: "Billes d'argent errantes", index: "50" },
  { name: "Larmes de ressentiment", index: "51" },
  { name: "L'avenir est entre nos mains…", index: "52" },
];

export default names;
