const names = [
  { name: "À ce soir !", index: "1" },
  { name: "Ce sont tous des animaux !", index: "2" },
  { name: "Jouons au président et au clochard", index: "3" },
  { name: "De quel signe est-elle ?", index: "4" },
  { name: "Je me trompais", index: "5" },
  { name: "Ça te gênerait qu'on vienne chez toi ?", index: "6" },
  { name: "Elle devient le printemps", index: "7" },
  { name: "Amusez-vous bien", index: "8" },
  { name: "Yuki est mon premier amour", index: "9" },
  { name: "C'est la Saint-Valentin, après tout", index: "10" },
  { name: "Quelle charmante auberge", index: "11" },
  { name: "Tu as l'air de bien t'amuser", index: "12" },
  { name: "Comment vas-tu ? Mon très cher frère !", index: "13" },
  { name: "C'est un secret", index: "14" },
  { name: "Pas vraiment", index: "15" },
  { name: "Ne marchez pas dessus !", index: "16" },
  { name: "C'est pour Uo !", index: "17" },
  { name: "L'important...", index: "18" },
  { name: "Veuillez m'excuser !", index: "19" },
  { name: "Pourquoi tu la ramasses vraiment ?", index: "20" },
  { name: "Je dois répondre aux provocations des ondes", index: "21" },
  { name: "Parce que ça m'a fait plaisir", index: "22" },
  { name: "Tu as l'air en forme...", index: "23" },
  { name: "Rentrons", index: "24" },
  { name: "L'été arrive bientôt", index: "25" },
  { name: "Ça faisait longtemps", index: "26" },
  { name: "On mangera des nouilles tous ensemble", index: "27" },
  { name: "Changeons-nous...", index: "28" },
  { name: "Je me suis fait larguer...", index: "29" },
  { name: "À moi les nouilles à l'igname !", index: "30" },
  { name: "Tu es bête, ou quoi ?", index: "31" },
  { name: "Commençons le concours de fendage de pastèques !", index: "32" },
  { name: "Je ne fais que dire la vérité", index: "33" },
  { name: "Ma précieuse...", index: "34" },
  { name: "« Qui »... êtes-vous ?", index: "35" },
  { name: "Ils ne sont qu'à moi", index: "36" },
  { name: "Tu as pleuré à ma place", index: "37" },
  { name: "Si tu veux !", index: "38" },
  { name: "Je n'ai plus qu'à mourir...", index: "39" },
  { name: "J'y vais", index: "40" },
  { name: "Tu lui demanderas ?", index: "41" },
  { name: "Je suis sûre que tu t'en créeras...", index: "42" },
  { name: "Si on s’embrassait ?", index: "43" },
  { name: "Il n'y en a aucun !", index: "44" },
  { name: "Est-ce que ça va ?", index: "45" },
  { name: "Je sais que c'est arrivé.", index: "46" },
  { name: "Moi, je ne veux pas de ça !", index: "47" },
  { name: "À peu près Cendrillon !", index: "48" },
  { name: "Machi, tu es là !", index: "49" },
  { name: "Je ne suis plus comme eux...", index: "50" },
  { name: "Organisons un nouveau banquet", index: "51" },
  { name: "C'est la pure et dure vérité", index: "52" },
  { name: "S'il pouvait neiger", index: "53" },
  { name: "Je suis rentrée...", index: "54" },
  { name: "Bref... Tu comprends, non ?", index: "55" },
  { name: "Mais quelle idiote", index: "56" },
  { name: "Eh oui, elle est vide", index: "57" },
  { name: "Là, tu me déçois...", index: "58" },
  { name: "Quel est votre nom ?", index: "59" },
  { name: "Je l'aime, tout simplement...", index: "60" },
  { name: "Adieu", index: "61" },
  { name: "Tu as été courageuse", index: "62" },
  { name: "Au revoir", index: "63" },
];

export default names;
